package schemaparity

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"sort"
	"strings"
	"testing"
)

// frozenBaselines pins the released v0.101.2 schema projections.
//
// These files are the RELEASED BASELINE. They are not a record of what the
// current tree serves, and regenerating them is not a fix -- it destroys the
// only committed description of what v0.101.2 looked like.
//
// That reading is not an opinion. It was measured across every consumer:
//
//	unifi/baseline_projection_test.go            const baselinePath, and its comment
//	                                             says "the released v0.101.2 projection"
//	internal/catalogparity/waves_test.go         releasedSchemaVersions() reads it
//	internal/catalogparity/wave_receipts_test.go pins receipt.SchemaSHA256 against it
//	provider-codegen/generate.go                 passes it to catalog-parity as -schema
//
// Four consumers read it as the released baseline. One line of one shell script
// -- catalog-build-schema.sh:148, which this package replaces -- compared it
// against the freshly built candidate and so read it as an expected output.
// That single misreading is what made the file look like it had two jobs.
//
// Six entries in provider-codegen/schema-changes/v0.101.2-to-next.json cite
// these paths BY NAME as the measured evidence for what released looked like.
// Regenerating the files does not merely lose information; it silently rewrites
// the evidence those declarations point at, while leaving the declarations
// reading as though they were still supported.
var frozenBaselines = map[string]string{
	"../../provider-contracts/schema/terraform-1.15.8.json": "e054aef83f2cf19c82968951342d3daf46b0b8071c15c5c076201aa0c5d93317",
	"../../provider-contracts/schema/tofu-1.12.1.json":      "73c4e1fab3ddc7f70dbdfc38ab117e504c5c71d8133c090e9ede0dc0851ff7f0",
}

// TestReleasedBaselineIsFrozen fails when a released projection changes.
//
// The message is long on purpose. A golden's usual failure text says the file
// changed and prints the command that regenerates it, which is the laundering
// path: the fastest way to a green build is to destroy the baseline, and the
// text recommends it. This one says what the file IS, who depends on that, and
// what re-baselining costs, so that regenerating is a decision rather than the
// obvious next step.
//
// PROVEN RED, restored afterwards. Setting format_version to "0.9-probe" in
// tofu-1.12.1.json turned this red with both digests printed and four named
// consumers in the message. Restored with `command cp -f` from a backup rather
// than by re-running the edit -- the shell here aliases cp to cp -i, which
// prompts and then silently does nothing, and a restore that quietly fails is
// how a probe becomes a commit.
func TestReleasedBaselineIsFrozen(t *testing.T) {
	for path, want := range frozenBaselines {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("%s: %v\n\nThis file is the released v0.101.2 schema baseline and four "+
				"packages read it. It is not generated by anything in this tree.", path, err)
			continue
		}
		sum := sha256.Sum256(raw)
		if got := hex.EncodeToString(sum[:]); got != want {
			t.Errorf(`%s changed.

  sha256 is   %s
  frozen at   %s

This file is the RELEASED v0.101.2 schema projection. It records what the
released provider served, and nothing in this tree regenerates it.

Four consumers depend on that meaning:
  unifi/baseline_projection_test.go             compares the built schema against it
  internal/catalogparity/waves_test.go          derives released schema versions from it
  internal/catalogparity/wave_receipts_test.go  pins every wave receipt's SchemaSHA256 to it
  provider-codegen/generate.go                  feeds it to catalog-parity as the -schema input

And six entries in provider-codegen/schema-changes/v0.101.2-to-next.json cite it
by path as the measured evidence for what released looked like.

IF THE BUILT SCHEMA DIFFERS FROM THIS FILE, THAT IS THE FINDING, NOT THE PROBLEM.
Declare the change in the schema-change ledger, naming the surface, attribute,
field and the exact old and new values, and argue why it cannot break an
existing configuration. An entry licenses one named transition.

REGENERATING THIS FILE IS NOT THAT. It rewrites the evidence six declarations
point at, leaving them reading as supported when their support is gone, and it
retunes four consumers to a baseline that is no longer the released one. The
only legitimate reason to change it is a deliberate re-baseline onto a NEW
released version, which also means a new ledger with a new from_version -- and
updating this digest is the smallest part of that work.`, path, got, want)
		}
	}
}

// TestFrozenBaselineGuardHasSubjects is the guard on the guard.
//
// A freeze check whose message says only "the file changed" trains the reader
// to regenerate. The whole value here is in what the message names, so an empty
// or truncated message would leave a check that fires correctly and still
// causes the damage it exists to prevent. Asserting the text keeps that from
// being edited away by someone tidying a long string.
func TestFrozenBaselineGuardHasSubjects(t *testing.T) {
	if len(frozenBaselines) != 2 {
		t.Fatalf("frozen baselines = %d, want both the terraform and tofu projections", len(frozenBaselines))
	}
	for path, digest := range frozenBaselines {
		if len(digest) != 64 {
			t.Errorf("%s: digest %q is not a sha256", path, digest)
		}
		if _, err := os.Stat(path); err != nil {
			t.Errorf("%s: frozen baseline is missing, so the guard asserts nothing: %v", path, err)
		}
	}
}

// TestCommittedDigestsDescribeTheFrozenContract recomputes every digest in
// build/m0/provider-schema-digests.json from the frozen contract.
//
// NOTHING IN THIS TREE WRITES THAT FILE. Outside tests its only mentions are
// comments, and roughly eighty consumers pass it as -baseline. An artifact with
// eighty readers, no producer and no check is the worst combination in the
// repository, and it held 95 recorded facts of which exactly one was asserted:
// the first version of this test checked canonical_schema_sha256 and then
// checked the 94-entry map only for len() != 0. Mutating a single per-surface
// digest left it green, which its own failure message admitted while passing.
//
// So all 94 are recomputed. The canonicalisation is the one the artifact was
// produced with -- compact JSON, keys sorted, no trailing newline, equivalent
// to `jq -cS '.<section>.<surface>' | sha256`, and 94 of 94 reproduce.
//
// SetEscapeHTML(false) is deliberate and currently unobservable: no description
// in the contract contains <, > or &, so both settings reproduce today. jq is
// the reference implementation and does not escape, so the day a description
// gains an ampersand this stays right instead of failing for a reason nobody
// would connect to the change.
func TestCommittedDigestsDescribeTheFrozenContract(t *testing.T) {
	const (
		contract = "../../provider-contracts/schema/terraform-1.15.8.json"
		digests  = "../../build/m0/provider-schema-digests.json"
	)
	raw, err := os.ReadFile(contract)
	if err != nil {
		t.Fatalf("read %s: %v", contract, err)
	}
	sum := sha256.Sum256(raw)
	wantCanonical := hex.EncodeToString(sum[:])

	blob, err := os.ReadFile(digests)
	if err != nil {
		t.Fatalf("read %s: %v", digests, err)
	}
	var recorded struct {
		CanonicalSHA256 string            `json:"canonical_schema_sha256"`
		SchemaSHA256    map[string]string `json:"schema_sha256"`
	}
	if err := json.Unmarshal(blob, &recorded); err != nil {
		t.Fatalf("parse %s: %v", digests, err)
	}
	if recorded.CanonicalSHA256 != wantCanonical {
		t.Errorf(`%s no longer describes %s.

  the contract hashes to    %s
  the digests file records  %s

These two committed artifacts are the released baseline together, and roughly
eighty consumers pass the digests as -baseline assuming they agree. Do not
silence this by regenerating: establish which artifact moved and why. The
released record is not supposed to move at all.`, digests, contract, wantCanonical, recorded.CanonicalSHA256)
	}

	var doc map[string]map[string]json.RawMessage
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("parse %s as sections: %v", contract, err)
	}
	// Most sections map surface name to schema. `provider` is NOT one of them:
	// it IS a schema, carrying block and version directly, and the digests file
	// records it under the bare key "provider". Discriminating on the presence
	// of a "block" key rather than on the name means a second provider-shaped
	// section would be handled without an edit -- and it is how the mismatch
	// announced itself, as 95 derived against 94 recorded rather than as a
	// digest that silently disagreed.
	derived := map[string]string{}
	digestOf := func(key string, body []byte) {
		var value any
		if err := json.Unmarshal(body, &value); err != nil {
			return
		}
		var buf bytes.Buffer
		enc := json.NewEncoder(&buf)
		enc.SetEscapeHTML(false)
		if err := enc.Encode(sortedValue(value)); err != nil {
			t.Fatalf("re-encode %s: %v", key, err)
		}
		h := sha256.Sum256(bytes.TrimRight(buf.Bytes(), "\n"))
		derived[key] = hex.EncodeToString(h[:])
	}
	for section, surfaces := range doc {
		if _, isSchema := surfaces["block"]; isSchema {
			whole, err := json.Marshal(surfaces)
			if err != nil {
				t.Fatalf("re-encode section %s: %v", section, err)
			}
			digestOf(section, whole)
			continue
		}
		for surface, body := range surfaces {
			digestOf(section+"."+surface, body)
		}
	}

	if len(derived) != len(recorded.SchemaSHA256) {
		t.Errorf("the contract yields %d surfaces and the digests file records %d; "+
			"one of them gained or lost a surface without the other",
			len(derived), len(recorded.SchemaSHA256))
	}
	var wrong []string
	for key, want := range recorded.SchemaSHA256 {
		got, ok := derived[key]
		switch {
		case !ok:
			wrong = append(wrong, key+" is recorded but the contract has no such surface")
		case got != want:
			wrong = append(wrong, key+" recorded "+want[:16]+"… but the contract yields "+got[:16]+"…")
		}
	}
	sort.Strings(wrong)
	if len(wrong) > 0 {
		t.Errorf(`%d of %d per-surface digest(s) no longer describe %s:

  %s

Each entry is the sha256 of that surface's subtree, compact with sorted keys.
A mismatch means the digests file and the contract disagree about what the
released provider served for that surface, and eighty consumers are reading
whichever one they happened to be handed.`,
			len(wrong), len(recorded.SchemaSHA256), contract, strings.Join(wrong, "\n  "))
	}
}

// sortedValue rebuilds a decoded document with map keys in sorted order.
//
// encoding/json already emits map keys sorted, so this is belt and braces
// rather than the mechanism -- it exists so that the canonicalisation is
// STATED here rather than inherited from an implementation detail that a Go
// release could quietly change.
func sortedValue(v any) any {
	switch t := v.(type) {
	case map[string]any:
		out := make(map[string]any, len(t))
		for k, vv := range t {
			out[k] = sortedValue(vv)
		}
		return out
	case []any:
		out := make([]any, len(t))
		for i, vv := range t {
			out[i] = sortedValue(vv)
		}
		return out
	default:
		return v
	}
}

// TestTheFrozenContractsAreTheOnesTheBaselineManifestPINS closes the seam the
// cutover opened.
//
// catalog-build-schema.sh compared the candidate's live projection against these
// two files by name, hardcoded, beside a baseline manifest that pins the same
// two CLI versions -- so a CLI bump moved one and not the other and nothing
// compared them. cmd/catalog-build-schema now DERIVES the path from the pinned
// version, which removes that split and creates a different way to be wrong: a
// version bumped in the manifest with no contract file beside it makes the gate
// fail on an unreadable path, in a manual pipeline, after two provider builds.
//
// This is that failure moved to push time, and it is the only part of the
// derivation a test can reach. The comparison itself needs both CLIs and two
// provider builds.
func TestTheFrozenContractsAreTheOnesTheBaselineManifestPINS(t *testing.T) {
	manifest, err := LoadBaselineManifest("../../build/m0/provider-baseline.json")
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range []struct{ cli, version string }{
		{"terraform", manifest.Clients.Terraform.Version},
		{"tofu", manifest.Clients.OpenTofu.Version},
	} {
		if c.version == "" {
			t.Errorf("the manifest pins no %s version, so the derived path would be %s-.json "+
				"and the gate would fail on an unreadable file rather than on a schema difference",
				c.cli, c.cli)
			continue
		}
		derived := "../../provider-contracts/schema/" + c.cli + "-" + c.version + ".json"
		if _, frozen := frozenBaselines[derived]; !frozen {
			t.Errorf("the manifest pins %s %s, so cmd/catalog-build-schema reads %s -- which is "+
				"not one of the frozen baselines this file guards.\n\n"+
				"    Either the CLI was bumped without adding its contract, or the contract was "+
				"added without pinning it. The two must move together: the derived file is the "+
				"released baseline the candidate is compared against, and a missing one turns a "+
				"schema gate into a file-not-found in a manual pipeline.", c.cli, c.version, derived)
		}
	}
}
