package schemaparity

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"testing"
)

// frozenBaselines pins the released v0.101.2 schema projections.
//
// These files are the RELEASED BASELINE. They are not a record of what the
// current tree serves, and regenerating them is not a fix -- it destroys the
// only committed description of what v0.101.2 looked like.
//
// That reading is not an opinion. It was measured across every consumer:
//
//	unifi/baseline_projection_test.go            const baselinePath, and its comment
//	                                             says "the released v0.101.2 projection"
//	internal/catalogparity/waves_test.go         releasedSchemaVersions() reads it
//	internal/catalogparity/wave_receipts_test.go pins receipt.SchemaSHA256 against it
//	provider-codegen/generate.go                 passes it to catalog-parity as -schema
//
// Four consumers read it as the released baseline. One line of one shell script
// -- catalog-build-schema.sh:148, which this package replaces -- compared it
// against the freshly built candidate and so read it as an expected output.
// That single misreading is what made the file look like it had two jobs.
//
// Six entries in provider-codegen/schema-changes/v0.101.2-to-next.json cite
// these paths BY NAME as the measured evidence for what released looked like.
// Regenerating the files does not merely lose information; it silently rewrites
// the evidence those declarations point at, while leaving the declarations
// reading as though they were still supported.
var frozenBaselines = map[string]string{
	"../../provider-contracts/schema/terraform-1.15.8.json": "e054aef83f2cf19c82968951342d3daf46b0b8071c15c5c076201aa0c5d93317",
	"../../provider-contracts/schema/tofu-1.12.1.json":      "73c4e1fab3ddc7f70dbdfc38ab117e504c5c71d8133c090e9ede0dc0851ff7f0",
}

// TestReleasedBaselineIsFrozen fails when a released projection changes.
//
// The message is long on purpose. A golden's usual failure text says the file
// changed and prints the command that regenerates it, which is the laundering
// path: the fastest way to a green build is to destroy the baseline, and the
// text recommends it. This one says what the file IS, who depends on that, and
// what re-baselining costs, so that regenerating is a decision rather than the
// obvious next step.
//
// PROVEN RED, restored afterwards. Setting format_version to "0.9-probe" in
// tofu-1.12.1.json turned this red with both digests printed and four named
// consumers in the message. Restored with `command cp -f` from a backup rather
// than by re-running the edit -- the shell here aliases cp to cp -i, which
// prompts and then silently does nothing, and a restore that quietly fails is
// how a probe becomes a commit.
func TestReleasedBaselineIsFrozen(t *testing.T) {
	for path, want := range frozenBaselines {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("%s: %v\n\nThis file is the released v0.101.2 schema baseline and four "+
				"packages read it. It is not generated by anything in this tree.", path, err)
			continue
		}
		sum := sha256.Sum256(raw)
		if got := hex.EncodeToString(sum[:]); got != want {
			t.Errorf(`%s changed.

  sha256 is   %s
  frozen at   %s

This file is the RELEASED v0.101.2 schema projection. It records what the
released provider served, and nothing in this tree regenerates it.

Four consumers depend on that meaning:
  unifi/baseline_projection_test.go             compares the built schema against it
  internal/catalogparity/waves_test.go          derives released schema versions from it
  internal/catalogparity/wave_receipts_test.go  pins every wave receipt's SchemaSHA256 to it
  provider-codegen/generate.go                  feeds it to catalog-parity as the -schema input

And six entries in provider-codegen/schema-changes/v0.101.2-to-next.json cite it
by path as the measured evidence for what released looked like.

IF THE BUILT SCHEMA DIFFERS FROM THIS FILE, THAT IS THE FINDING, NOT THE PROBLEM.
Declare the change in the schema-change ledger, naming the surface, attribute,
field and the exact old and new values, and argue why it cannot break an
existing configuration. An entry licenses one named transition.

REGENERATING THIS FILE IS NOT THAT. It rewrites the evidence six declarations
point at, leaving them reading as supported when their support is gone, and it
retunes four consumers to a baseline that is no longer the released one. The
only legitimate reason to change it is a deliberate re-baseline onto a NEW
released version, which also means a new ledger with a new from_version -- and
updating this digest is the smallest part of that work.`, path, got, want)
		}
	}
}

// TestFrozenBaselineGuardHasSubjects is the guard on the guard.
//
// A freeze check whose message says only "the file changed" trains the reader
// to regenerate. The whole value here is in what the message names, so an empty
// or truncated message would leave a check that fires correctly and still
// causes the damage it exists to prevent. Asserting the text keeps that from
// being edited away by someone tidying a long string.
func TestFrozenBaselineGuardHasSubjects(t *testing.T) {
	if len(frozenBaselines) != 2 {
		t.Fatalf("frozen baselines = %d, want both the terraform and tofu projections", len(frozenBaselines))
	}
	for path, digest := range frozenBaselines {
		if len(digest) != 64 {
			t.Errorf("%s: digest %q is not a sha256", path, digest)
		}
		if _, err := os.Stat(path); err != nil {
			t.Errorf("%s: frozen baseline is missing, so the guard asserts nothing: %v", path, err)
		}
	}
}
