package testaudit

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
)

// The two variables that drive an inventory rewrite.
//
// The asymmetry runs the OPPOSITE way to the golden inventories in package
// unifi, and the reason is the polarity of the thing being counted. There,
// adding a behaviour line is the ordinary case and dropping one is the
// regression, so a removal has to say its name. Here, a test that cannot fail
// is the defect: REMOVING an entry is the fix and must stay cheap, and ADDING
// one is a new test that cannot fail, which is the thing this exists to stop.
//
// Copying the other asymmetry would have inverted the guard while looking
// exactly like the house pattern.
const (
	updateEnv        = "UPDATE_TESTAUDIT"
	allowAdditionEnv = "UPDATE_TESTAUDIT_ALLOW_ADDITION"
)

const inventoryHeader = `# Test functions that CANNOT FAIL, one per line: file, name, shape.
#
# Generated by Test_unfailableTestInventory. Do not edit by hand.
#
#   empty-table   the table is empty, so the body never runs
#   skip-stub     an unconditional t.Skip: it names a behaviour and declines
#                 to test it, with no condition that could make it run
#   no-assertion  it calls the code under test and checks nothing. This one
#                 EXECUTES, so it produces coverage and a green PASS
#
# Removing a line is the fix and needs only UPDATE_TESTAUDIT=1. Adding one
# needs UPDATE_TESTAUDIT_ALLOW_ADDITION=1 as well, because a new entry here is
# a new test that cannot fail.
`

func repositoryRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate this source file, so the repository root cannot be resolved")
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(thisFile)))
}

func inventoryPath(t *testing.T) string {
	t.Helper()
	return filepath.Join(repositoryRoot(t), "internal", "testaudit", "unfailable-tests.txt")
}

// Test_unfailableTestInventory is the ratchet. It does not ask anyone to fix
// the tests that cannot fail; it asks that the number stop growing.
//
// PROVEN TO FAIL. Adding unifi/validators/zz_sweep_probe_test.go containing
//
//	func Test_sweepProbe_Create(t *testing.T) { t.Skip("requires terraform state machinery") }
//
// turned this red with "1 new test(s) that CANNOT FAIL:
// unifi/validators/zz_sweep_probe_test.go Test_sweepProbe_Create skip-stub".
// Removing the file returned it to green. Recorded here rather than in a commit
// body because a proof nobody can find from the check is a proof nobody checks.
func Test_unfailableTestInventory(t *testing.T) {
	root := repositoryRoot(t)
	path := inventoryPath(t)

	findings, err := Scan(root)
	if err != nil {
		t.Fatalf("scanning %s: %v", root, err)
	}

	got := make([]string, 0, len(findings))
	for _, f := range findings {
		got = append(got, f.String())
	}

	want, exists := readInventory(t, path)
	added, removed := diff(want, got)

	if os.Getenv(updateEnv) != "" {
		// A missing inventory is a first run, not a hundred and fifty
		// additions. Without this, seeding it would need the addition flag,
		// which is how people learn to set the addition flag by default.
		if len(added) > 0 && exists && os.Getenv(allowAdditionEnv) == "" {
			t.Fatal(additionRefusal(path, added))
		}
		body := inventoryHeader + strings.Join(got, "\n") + "\n"
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatalf("writing %s: %v", path, err)
		}
		t.Logf("wrote %d entries to %s", len(got), path)
		return
	}

	if len(added) > 0 {
		t.Error(additionRefusal(path, added))
	}
	if len(removed) > 0 {
		t.Errorf("%d test(s) in %s can now fail and are no longer in the tree:\n    %s\n\n"+
			"    That is the good direction. Refresh the inventory with %s=1.",
			len(removed), filepath.Base(path), strings.Join(removed, "\n    "), updateEnv)
	}
}

// additionRefusal names the entries. "Set another variable" tells the reader
// nothing about what they would be agreeing to.
func additionRefusal(path string, added []string) string {
	return fmt.Sprintf(
		"%d new test(s) that CANNOT FAIL:\n    %s\n\n"+
			"    Each of these will pass whatever the code under test does. A test\n"+
			"    named after a behaviour reads as coverage of it -- to the reviewer,\n"+
			"    to the release checklist, and to whoever next decides where the risk\n"+
			"    is. Six of the seven behaviours already known to be broken in this\n"+
			"    provider have a test named after them, and every one is in %s.\n\n"+
			"    Make the test assert something. If it genuinely cannot yet, delete it\n"+
			"    rather than skip it: a missing test is an absence a reader can see.\n"+
			"    If it must land as it is, say so with %s=1 alongside %s=1.",
		len(added), strings.Join(added, "\n    "), filepath.Base(path),
		allowAdditionEnv, updateEnv)
}

func readInventory(t *testing.T, path string) (lines []string, exists bool) {
	t.Helper()
	body, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, false
	}
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	for _, line := range strings.Split(string(body), "\n") {
		if line = strings.TrimRight(line, "\r"); line != "" && !strings.HasPrefix(line, "#") {
			lines = append(lines, line)
		}
	}
	return lines, true
}

func diff(want, got []string) (added, removed []string) {
	inWant := map[string]bool{}
	for _, w := range want {
		inWant[w] = true
	}
	inGot := map[string]bool{}
	for _, g := range got {
		inGot[g] = true
	}
	for _, g := range got {
		if !inWant[g] {
			added = append(added, g)
		}
	}
	for _, w := range want {
		if !inGot[w] {
			removed = append(removed, w)
		}
	}
	sort.Strings(added)
	sort.Strings(removed)
	return added, removed
}

// ---------------------------------------------------------------------------
// The analyzer's own proof that it can fail, and that it does not fire wrongly.
//
// A survey tool that over-reports is worse than none: one false positive in a
// list of a hundred and fifty is enough for a reader to stop trusting the list,
// and then the real entries go unread too. So the fixtures assert both
// directions, and the ones that must NOT be reported outnumber the ones that
// must.

func scanFixture(t *testing.T, name string) map[string]Kind {
	t.Helper()
	dir := filepath.Join("testdata", name)
	findings, err := Scan(dir)
	if err != nil {
		t.Fatalf("scanning %s: %v", dir, err)
	}
	byName := map[string]Kind{}
	for _, f := range findings {
		byName[f.Name] = f.Kind
	}
	return byName
}

func Test_scanReportsTheThreeShapes(t *testing.T) {
	got := scanFixture(t, "unfailable")

	want := map[string]Kind{
		"TestNothingHappens":    NoAssertion,
		"TestEmptyTable":        EmptyTable,
		"TestPopulatedButMute":  NoAssertion,
		"TestUnconditionalSkip": SkipStub,
	}
	for name, kind := range want {
		if got[name] != kind {
			t.Errorf("%s: reported %q, want %q", name, got[name], kind)
		}
	}
}

func Test_scanDoesNotReportATestThatCanFail(t *testing.T) {
	got := scanFixture(t, "failable")

	// Every one of these can fail. Any of them appearing is a false positive,
	// and the helper cases are the ones that matter: a test whose only
	// assertion is one call away is the common shape in this repository.
	for _, name := range []string{
		"TestDirectAssertion",
		"TestViaHelper",
		"TestViaHelperChain",
		"TestViaRequire",
		"TestSubtestAsserts",
		"TestConditionalSkipStillRuns",
		"TestTableWithCases",
	} {
		if kind, reported := got[name]; reported {
			t.Errorf("%s can fail but was reported as %q", name, kind)
		}
	}
}

// Test_scanIsNotVacuous guards the two tests above. Both would pass if Scan
// returned nothing at all -- the first only checks named entries, the second
// only checks absence -- so the fixture must be shown to produce findings.
func Test_scanIsNotVacuous(t *testing.T) {
	if n := len(scanFixture(t, "unfailable")); n == 0 {
		t.Fatal("the unfailable fixture produced no findings, so the shape assertions above prove nothing")
	}
	if n := len(scanFixture(t, "failable")); n != 0 {
		t.Fatalf("the failable fixture produced %d finding(s); it exists to have none", n)
	}
}

func Test_additionRefusalNamesTheEntries(t *testing.T) {
	message := additionRefusal("internal/testaudit/unfailable-tests.txt",
		[]string{"unifi/thing_test.go\tTest_thing_Create\tskip-stub"})

	for _, want := range []string{
		"Test_thing_Create",    // the entry itself
		"unfailable-tests.txt", // which inventory
		allowAdditionEnv,       // how to proceed deliberately
		"delete it",            // the remedy that is better than a skip
	} {
		if !strings.Contains(message, want) {
			t.Errorf("the refusal does not mention %q:\n%s", want, message)
		}
	}
}

func Test_diffSeparatesAdditionsFromRemovals(t *testing.T) {
	added, removed := diff([]string{"a", "b"}, []string{"b", "c"})
	if len(added) != 1 || added[0] != "c" {
		t.Errorf("added = %v, want [c]", added)
	}
	if len(removed) != 1 || removed[0] != "a" {
		t.Errorf("removed = %v, want [a]", removed)
	}
}
