// Command metadata-contract-gen freezes the practitioner-visible name of every
// surface, keyed by the Go type that serves it.
//
// WHY THIS EXISTS AS A GENERATOR. Forty-three hand-written tests asserted one
// fact each -- that a named receiver's Metadata sets a named TypeName. Most did
// it in an eleven-line body; some used a forty-three-line table for the same
// single assertion. The assertion is worth keeping and the forty-three copies
// of the scaffolding around it are not.
//
// AND IT IS NOT SUBSUMED BY THE AGREEMENT CHECK, which was the first thing I
// checked. TestEveryGeneratedSurfaceIsServedUnderItsDeclaredName compares the
// SET of served names against the SET declared by go:generate directives. Two
// facts survive only here:
//
//   - PER RECEIVER. Set membership cannot see two receivers swapping each
//     other's names, and unifi_ap_group is served by both a resource and a data
//     source, so the set stays identical through the swap.
//   - THE LITERAL ITSELF. Renaming a surface in the directive AND in Metadata
//     together leaves the sets agreeing. That is a practitioner-visible break
//     and nothing else in the tree would report it.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	dir := flag.String("dir", "unifi", "directory of provider sources to read")
	out := flag.String("output", "", "file to write the frozen contract to")
	flag.Parse()
	if *out == "" {
		fail("-output is required")
	}

	frozen, err := derive(*dir)
	if err != nil {
		fail("%v", err)
	}
	// A generator that finds nothing must not write an empty contract: the
	// driver would then have nothing to compare and would pass by checking
	// nothing at all.
	if len(frozen) == 0 {
		fail("no surface set a TypeName in %s, so the contract would be empty", *dir)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/metadata-contract-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "// Package metadatacontract freezes the practitioner-visible type name of\n")
	fmt.Fprintf(&buf, "// every surface, keyed by the Go type that serves it.\n")
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "// A row here is a promise to practitioners: rename a surface and the driver\n")
	fmt.Fprintf(&buf, "// in unifi/ reports it by receiver name. Regenerating this file is how that\n")
	fmt.Fprintf(&buf, "// promise is deliberately broken, which is the point -- it makes a rename a\n")
	fmt.Fprintf(&buf, "// visible diff in a frozen contract rather than an edit to one line of Go.\n")
	fmt.Fprintf(&buf, "package metadatacontract\n\n")
	fmt.Fprintf(&buf, "// FrozenTypeNames maps a receiver's Go type name to the type name it serves.\n")
	fmt.Fprintf(&buf, "var FrozenTypeNames = map[string]string{\n")
	keys := make([]string, 0, len(frozen))
	for k := range frozen {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%q: %q,\n", k, frozen[k])
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fail("formatting the generated contract: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o750); err != nil {
		fail("%v", err)
	}
	if err := os.WriteFile(*out, src, 0o600); err != nil {
		fail("%v", err)
	}
	fmt.Fprintf(os.Stderr, "metadata-contract-gen: froze %d surface name(s) into %s\n", len(frozen), *out)
}

// derive finds, for each receiver with a Metadata method, the literal suffix it
// appends to the provider type name.
func derive(dir string) (map[string]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	frozen := map[string]string{}
	fset := token.NewFileSet()
	for _, entry := range entries {
		name := entry.Name()
		// Test files are skipped for the same reason schemabehaviour skips
		// them: a fixture in a test is not a surface the provider serves.
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", name, err)
		}
		for _, decl := range file.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Name.Name != "Metadata" || fd.Recv == nil || len(fd.Recv.List) == 0 {
				continue
			}
			recv := receiverName(fd.Recv.List[0].Type)
			if recv == "" {
				continue
			}
			suffix, ok := typeNameSuffix(fd.Body)
			if !ok {
				continue
			}
			if existing, clash := frozen[recv]; clash && existing != suffix {
				return nil, fmt.Errorf("%s sets two different type names, %q and %q", recv, existing, suffix)
			}
			frozen[recv] = suffix
		}
	}
	return frozen, nil
}

func receiverName(e ast.Expr) string {
	if star, ok := e.(*ast.StarExpr); ok {
		e = star.X
	}
	if id, ok := e.(*ast.Ident); ok {
		return id.Name
	}
	return ""
}

// typeNameSuffix reads the name a Metadata method serves, in the two forms the
// provider actually uses:
//
//	resp.TypeName = req.ProviderTypeName + "_x"   -> unifi_x   (every surface)
//	resp.TypeName = "unifi"                       -> unifi     (the provider)
//
// BOTH FORMS REQUIRE THE ASSIGNMENT TARGET TO BE .TypeName. An earlier version
// matched any assignment whose right-hand side concatenated a string, which
// would have frozen whatever unrelated expression happened to appear first in a
// longer Metadata body.
func typeNameSuffix(body *ast.BlockStmt) (string, bool) {
	var found string
	var ok bool
	ast.Inspect(body, func(n ast.Node) bool {
		assign, is := n.(*ast.AssignStmt)
		if !is || len(assign.Rhs) != 1 || len(assign.Lhs) != 1 {
			return true
		}
		target, is := assign.Lhs[0].(*ast.SelectorExpr)
		if !is || target.Sel.Name != "TypeName" {
			return true
		}
		switch rhs := assign.Rhs[0].(type) {
		case *ast.BinaryExpr:
			if rhs.Op != token.ADD {
				return true
			}
			lit, is := rhs.Y.(*ast.BasicLit)
			if !is || lit.Kind != token.STRING {
				return true
			}
			suffix, err := strconv.Unquote(lit.Value)
			if err != nil {
				return true
			}
			found, ok = "unifi"+suffix, true
			return false
		case *ast.BasicLit:
			if rhs.Kind != token.STRING {
				return true
			}
			name, err := strconv.Unquote(rhs.Value)
			if err != nil {
				return true
			}
			found, ok = name, true
			return false
		}
		return true
	})
	return found, ok
}

func fail(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "metadata-contract-gen: "+format+"\n", a...)
	os.Exit(1)
}
