// Command list-resource-gen turns the listresources member of a provider code
// specification into Go.
//
// Emits exactly one schema shape (0-2 string attributes, one filter block) and
// refuses anything else by name -- a new shape must force a decision here, not a silent render.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type specification struct {
	ListResources []listResource `json:"listresources"`
}

type listResource struct {
	Name   string     `json:"name"`
	Schema listSchema `json:"schema"`
}

type listSchema struct {
	Attributes          []attribute `json:"attributes"`
	Blocks              []block     `json:"blocks"`
	MarkdownDescription string      `json:"markdown_description"`
}

type attribute struct {
	Name   string        `json:"name"`
	String *stringSchema `json:"string"`
}

type stringSchema struct {
	ComputedOptionalRequired string `json:"computed_optional_required"`
	Description              string `json:"description"`
}

type block struct {
	Name       string      `json:"name"`
	ListNested *listNested `json:"list_nested"`
}

type listNested struct {
	NestedObject nestedObject `json:"nested_object"`
	Description  string       `json:"description"`
}

type nestedObject struct {
	Attributes []attribute `json:"attributes"`
}

func main() { os.Exit(run(os.Args[1:], os.Stderr)) }

func run(args []string, stderr io.Writer) int {
	flags := flag.NewFlagSet("list-resource-gen", flag.ContinueOnError)
	flags.SetOutput(stderr)
	input := flags.String("input", "", "provider code specification carrying a listresources member")
	output := flags.String("output", "", "directory for the generated file")
	pkg := flags.String("package", "", "package name for the generated file")
	if err := flags.Parse(args); err != nil {
		return 2
	}
	if *input == "" || *output == "" || *pkg == "" {
		fmt.Fprintln(stderr, "input, output and package are required")
		return 2
	}

	data, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	var document specification
	if err := json.Unmarshal(data, &document); err != nil {
		fmt.Fprintf(stderr, "parse %s: %v\n", *input, err)
		return 1
	}
	if len(document.ListResources) == 0 {
		fmt.Fprintf(stderr, "%s carries no listresources member; nothing to generate\n", *input)
		return 1
	}

	source, err := render(*pkg, document.ListResources)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	formatted, err := format.Source(source)
	if err != nil {
		fmt.Fprintf(stderr, "generated source does not parse: %v\n---\n%s\n", err, source)
		return 1
	}
	if err := os.MkdirAll(*output, 0o755); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	// Matches tfplugingen-framework's own filename shape for a resource, so a
	// list surface's generated code sits where the convention says to look for it.
	name := strings.ReplaceAll(document.ListResources[0].Name, "-", "_") + "_list_resource_gen.go"
	if err := os.WriteFile(filepath.Join(*output, name), formatted, 0o644); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	return 0
}

func render(pkg string, surfaces []listResource) ([]byte, error) {
	out := &bytes.Buffer{}
	fmt.Fprintf(out, "// Code generated by cmd/list-resource-gen. DO NOT EDIT.\n\npackage %s\n\n", pkg)
	fmt.Fprintf(out, "import (\n\t%q\n\n\t%q\n)\n",
		"context", "github.com/hashicorp/terraform-plugin-framework/list/schema")

	for _, surface := range surfaces {
		function := exportedName(surface.Name) + "ListResourceSchema"
		fmt.Fprintf(out, "\nfunc %s(ctx context.Context) schema.Schema {\n", function)
		fmt.Fprintf(out, "\treturn schema.Schema{\n")
		if surface.Schema.MarkdownDescription != "" {
			fmt.Fprintf(out, "\t\tMarkdownDescription: %q,\n", surface.Schema.MarkdownDescription)
		}
		if err := renderAttributes(out, surface, "\t\t", surface.Schema.Attributes); err != nil {
			return nil, err
		}
		if err := renderBlocks(out, surface); err != nil {
			return nil, err
		}
		fmt.Fprintf(out, "\t}\n}\n")
	}
	return out.Bytes(), nil
}

func renderAttributes(out *bytes.Buffer, surface listResource, indent string, attributes []attribute) error {
	if len(attributes) == 0 {
		return nil
	}
	fmt.Fprintf(out, "%sAttributes: map[string]schema.Attribute{\n", indent)
	for _, entry := range sortedAttributes(attributes) {
		if entry.String == nil {
			return fmt.Errorf(
				"%s: attribute %q is not a string; every list config attribute in this estate is one, "+
					"so a new type is a decision rather than a case to add silently",
				surface.Name, entry.Name)
		}
		disposition, err := dispositionField(surface.Name, entry.Name, entry.String.ComputedOptionalRequired)
		if err != nil {
			return err
		}
		fmt.Fprintf(out, "%s\t%q: schema.StringAttribute{\n", indent, entry.Name)
		if entry.String.Description != "" {
			fmt.Fprintf(out, "%s\t\tMarkdownDescription: %q,\n", indent, entry.String.Description)
		}
		fmt.Fprintf(out, "%s\t\t%s: true,\n%s\t},\n", indent, disposition, indent)
	}
	fmt.Fprintf(out, "%s},\n", indent)
	return nil
}

func renderBlocks(out *bytes.Buffer, surface listResource) error {
	if len(surface.Schema.Blocks) == 0 {
		return nil
	}
	fmt.Fprintf(out, "\t\tBlocks: map[string]schema.Block{\n")
	for _, entry := range sortedBlocks(surface.Schema.Blocks) {
		if entry.ListNested == nil {
			return fmt.Errorf(
				"%s: block %q is not list-nested; every list config block in this estate is",
				surface.Name, entry.Name)
		}
		fmt.Fprintf(out, "\t\t\t%q: schema.ListNestedBlock{\n", entry.Name)
		fmt.Fprintf(out, "\t\t\t\tNestedObject: schema.NestedBlockObject{\n")
		if err := renderAttributes(out, surface, "\t\t\t\t\t", entry.ListNested.NestedObject.Attributes); err != nil {
			return err
		}
		fmt.Fprintf(out, "\t\t\t\t},\n\t\t\t},\n")
	}
	fmt.Fprintf(out, "\t\t},\n")
	return nil
}

// dispositionField refuses an unrecognised disposition rather than emitting no
// field, which would compile as an attribute that's neither required nor optional.
func dispositionField(surface, attribute, disposition string) (string, error) {
	switch disposition {
	case "required":
		return "Required", nil
	case "optional":
		return "Optional", nil
	case "computed":
		return "Computed", nil
	case "computed_optional":
		return "Optional", nil
	default:
		return "", fmt.Errorf("%s: attribute %q declares disposition %q, which has no field",
			surface, attribute, disposition)
	}
}

// exportedName turns unifi_firewall_zone into UnifiFirewallZone.
func exportedName(surface string) string {
	parts := strings.Split(surface, "_")
	for index, part := range parts {
		if part == "" {
			continue
		}
		parts[index] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func sortedAttributes(in []attribute) []attribute {
	out := append([]attribute(nil), in...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func sortedBlocks(in []block) []block {
	out := append([]block(nil), in...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}
