// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type apGroupKitModel struct {
	ID         types.String   `tfsdk:"id"`
	Site       types.String   `tfsdk:"site"`
	DeviceMacs types.Set      `tfsdk:"device_macs"`
	Name       types.String   `tfsdk:"name"`
	Timeouts   timeouts.Value `tfsdk:"timeouts"`
}

// apGroupGenFields is every unifi_ap_group attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func apGroupGenFields() []resourcekit.Field[apGroupKitModel, ui.APGroup] {
	return []resourcekit.Field[apGroupKitModel, ui.APGroup]{
		resourcekit.StringField[apGroupKitModel, ui.APGroup]{
			Wire:  "name",
			Model: func(m *apGroupKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.APGroup) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
	}
}
