// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type bgpKitModel struct {
	ID             types.String   `tfsdk:"id"`
	Site           types.String   `tfsdk:"site"`
	Description    types.String   `tfsdk:"description"`
	Enabled        types.Bool     `tfsdk:"enabled"`
	Config         types.String   `tfsdk:"config"`
	UploadFileName types.String   `tfsdk:"upload_file_name"`
	ASN            types.Int64    `tfsdk:"asn"`
	Peers          types.List     `tfsdk:"peers"`
	RouterID       types.String   `tfsdk:"router_id"`
	Timeouts       timeouts.Value `tfsdk:"timeouts"`
}

// bgpGenFields is every unifi_bgp attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func bgpGenFields() []resourcekit.Field[bgpKitModel, ui.BGPConfig] {
	return []resourcekit.Field[bgpKitModel, ui.BGPConfig]{
		resourcekit.StringField[bgpKitModel, ui.BGPConfig]{
			Wire:  "description",
			Model: func(m *bgpKitModel) *types.String { return &m.Description },
			SDK:   func(s *ui.BGPConfig) *string { return &s.Description },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[bgpKitModel, ui.BGPConfig]{
			Wire:  "enabled",
			Model: func(m *bgpKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.BGPConfig) *bool { return &s.Enabled },
		},
		resourcekit.StringField[bgpKitModel, ui.BGPConfig]{
			Wire:  "uploaded_file_name",
			Model: func(m *bgpKitModel) *types.String { return &m.UploadFileName },
			SDK:   func(s *ui.BGPConfig) *string { return &s.UploadedFileName },
			Elide: resourcekit.KeepZero,
		},
	}
}
