// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type clientQosRateKitModel struct {
	ID             types.String   `tfsdk:"id"`
	Site           types.String   `tfsdk:"site"`
	Name           types.String   `tfsdk:"name"`
	QoSRateMaxDown types.Int64    `tfsdk:"qos_rate_max_down"`
	QoSRateMaxUp   types.Int64    `tfsdk:"qos_rate_max_up"`
	Timeouts       timeouts.Value `tfsdk:"timeouts"`
}

// clientQosRateGenFields is every unifi_client_qos_rate attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func clientQosRateGenFields() []resourcekit.Field[clientQosRateKitModel, ui.ClientGroup] {
	return []resourcekit.Field[clientQosRateKitModel, ui.ClientGroup]{
		resourcekit.StringField[clientQosRateKitModel, ui.ClientGroup]{
			Wire:  "name",
			Model: func(m *clientQosRateKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.ClientGroup) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[clientQosRateKitModel, ui.ClientGroup]{
			Wire:     "qos_rate_max_down",
			Model:    func(m *clientQosRateKitModel) *types.Int64 { return &m.QoSRateMaxDown },
			SDK:      func(s *ui.ClientGroup) **int64 { return &s.QOSRateMaxDown },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[clientQosRateKitModel, ui.ClientGroup]{
			Wire:     "qos_rate_max_up",
			Model:    func(m *clientQosRateKitModel) *types.Int64 { return &m.QoSRateMaxUp },
			SDK:      func(s *ui.ClientGroup) **int64 { return &s.QOSRateMaxUp },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
	}
}
