// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-nettypes/hwtypes"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type clientKitModel struct {
	ID                  types.String       `tfsdk:"id"`
	Site                types.String       `tfsdk:"site"`
	Blocked             types.Bool         `tfsdk:"blocked"`
	DisplayName         types.String       `tfsdk:"display_name"`
	FixedAPMAC          hwtypes.MACAddress `tfsdk:"fixed_ap_mac"`
	FixedIP             types.String       `tfsdk:"fixed_ip"`
	Hostname            types.String       `tfsdk:"hostname"`
	LastIP              types.String       `tfsdk:"last_ip"`
	LocalDNSRecord      types.String       `tfsdk:"local_dns_record"`
	MAC                 hwtypes.MACAddress `tfsdk:"mac"`
	Name                types.String       `tfsdk:"name"`
	Groups              types.List         `tfsdk:"groups"`
	Note                types.String       `tfsdk:"note"`
	NetworkID           types.String       `tfsdk:"network_id"`
	AllowExisting       types.Bool         `tfsdk:"allow_existing"`
	QoSRate             types.Object       `tfsdk:"qos_rate"`
	SkipForgetOnDestroy types.Bool         `tfsdk:"skip_forget_on_destroy"`
	Timeouts            timeouts.Value     `tfsdk:"timeouts"`
}

// clientGenFields is every unifi_client attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func clientGenFields() []resourcekit.Field[clientKitModel, ui.Client] {
	return []resourcekit.Field[clientKitModel, ui.Client]{
		resourcekit.BoolPtrField[clientKitModel, ui.Client]{
			Wire:  "blocked",
			Model: func(m *clientKitModel) *types.Bool { return &m.Blocked },
			SDK:   func(s *ui.Client) **bool { return &s.Blocked },
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "display_name",
			Model: func(m *clientKitModel) *types.String { return &m.DisplayName },
			SDK:   func(s *ui.Client) *string { return &s.DisplayName },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "fixed_ip",
			Model: func(m *clientKitModel) *types.String { return &m.FixedIP },
			SDK:   func(s *ui.Client) *string { return &s.FixedIP },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "hostname",
			Model: func(m *clientKitModel) *types.String { return &m.Hostname },
			SDK:   func(s *ui.Client) *string { return &s.Hostname },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "last_ip",
			Model: func(m *clientKitModel) *types.String { return &m.LastIP },
			SDK:   func(s *ui.Client) *string { return &s.LastIP },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "local_dns_record",
			Model: func(m *clientKitModel) *types.String { return &m.LocalDNSRecord },
			SDK:   func(s *ui.Client) *string { return &s.LocalDNSRecord },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "name",
			Model: func(m *clientKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.Client) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "note",
			Model: func(m *clientKitModel) *types.String { return &m.Note },
			SDK:   func(s *ui.Client) *string { return &s.Note },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[clientKitModel, ui.Client]{
			Wire:  "virtual_network_override_id",
			Model: func(m *clientKitModel) *types.String { return &m.NetworkID },
			SDK:   func(s *ui.Client) *string { return &s.VirtualNetworkOverrideID },
			Elide: resourcekit.KeepZero,
		},
	}
}
