// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type contentFilteringKitModel struct {
	ID         types.String   `tfsdk:"id"`
	Site       types.String   `tfsdk:"site"`
	AllowList  types.List     `tfsdk:"allow_list"`
	BlockList  types.List     `tfsdk:"block_list"`
	Categories types.List     `tfsdk:"categories"`
	ClientMacs types.List     `tfsdk:"client_macs"`
	Enabled    types.Bool     `tfsdk:"enabled"`
	Name       types.String   `tfsdk:"name"`
	NetworkIDs types.List     `tfsdk:"network_ids"`
	SafeSearch types.List     `tfsdk:"safe_search"`
	Schedule   types.Object   `tfsdk:"schedule"`
	Timeouts   timeouts.Value `tfsdk:"timeouts"`
}

type contentFilteringScheduleModel struct {
	Mode types.String `tfsdk:"mode"`
}

var contentFilteringScheduleAttrTypes = map[string]attr.Type{
	"mode": types.StringType,
}

// contentFilteringGenFields is every unifi_content_filtering attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func contentFilteringGenFields() []resourcekit.Field[contentFilteringKitModel, ui.ContentFiltering] {
	return []resourcekit.Field[contentFilteringKitModel, ui.ContentFiltering]{
		resourcekit.StringListField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "allow_list",
			Model: func(m *contentFilteringKitModel) *types.List { return &m.AllowList },
			SDK:   func(s *ui.ContentFiltering) *[]string { return &s.AllowList },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringListField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "block_list",
			Model: func(m *contentFilteringKitModel) *types.List { return &m.BlockList },
			SDK:   func(s *ui.ContentFiltering) *[]string { return &s.BlockList },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringListField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "categories",
			Model: func(m *contentFilteringKitModel) *types.List { return &m.Categories },
			SDK:   func(s *ui.ContentFiltering) *[]string { return &s.Categories },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringListField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "client_macs",
			Model: func(m *contentFilteringKitModel) *types.List { return &m.ClientMacs },
			SDK:   func(s *ui.ContentFiltering) *[]string { return &s.ClientMACs },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "enabled",
			Model: func(m *contentFilteringKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.ContentFiltering) *bool { return &s.Enabled },
		},
		resourcekit.StringField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "name",
			Model: func(m *contentFilteringKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.ContentFiltering) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringListField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "network_ids",
			Model: func(m *contentFilteringKitModel) *types.List { return &m.NetworkIDs },
			SDK:   func(s *ui.ContentFiltering) *[]string { return &s.NetworkIDs },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringListField[contentFilteringKitModel, ui.ContentFiltering]{
			Wire:  "safe_search",
			Model: func(m *contentFilteringKitModel) *types.List { return &m.SafeSearch },
			SDK:   func(s *ui.ContentFiltering) *[]string { return &s.SafeSearch },
			Elide: resourcekit.NullZero,
		},
	}
}
