// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-nettypes/hwtypes"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type deviceKitModel struct {
	ID                         types.String         `tfsdk:"id"`
	Site                       types.String         `tfsdk:"site"`
	Adopted                    types.Bool           `tfsdk:"adopted"`
	BandsteeringMode           types.String         `tfsdk:"bandsteering_mode"`
	ConfigNetwork              types.Object         `tfsdk:"config_network"`
	Disabled                   types.Bool           `tfsdk:"disabled"`
	FlowctrlEnabled            types.Bool           `tfsdk:"flowctrl_enabled"`
	JumboframeEnabled          types.Bool           `tfsdk:"jumboframe_enabled"`
	LcmBrightness              types.Int64          `tfsdk:"lcm_brightness"`
	LcmBrightnessOverride      types.Bool           `tfsdk:"lcm_brightness_override"`
	LcmIdleTimeout             timetypes.GoDuration `tfsdk:"lcm_idle_timeout"`
	LcmIdleTimeoutOverride     types.Bool           `tfsdk:"lcm_idle_timeout_override"`
	LcmNightModeBegins         types.String         `tfsdk:"lcm_night_mode_begins"`
	LcmNightModeEnds           types.String         `tfsdk:"lcm_night_mode_ends"`
	LedOverride                types.String         `tfsdk:"led_override"`
	LedOverrideColor           types.String         `tfsdk:"led_override_color"`
	LedOverrideColorBrightness types.Int64          `tfsdk:"led_override_color_brightness"`
	Locked                     types.Bool           `tfsdk:"locked"`
	MAC                        hwtypes.MACAddress   `tfsdk:"mac"`
	MeshStaVapEnabled          types.Bool           `tfsdk:"mesh_sta_vap_enabled"`
	MgmtNetworkID              types.String         `tfsdk:"mgmt_network_id"`
	Model                      types.String         `tfsdk:"model"`
	Name                       types.String         `tfsdk:"name"`
	OutdoorModeOverride        types.String         `tfsdk:"outdoor_mode_override"`
	OutletEnabled              types.Bool           `tfsdk:"outlet_enabled"`
	OutletOverrides            types.List           `tfsdk:"outlet_overrides"`
	PoeMode                    types.String         `tfsdk:"poe_mode"`
	RadioTable                 types.List           `tfsdk:"radio_table"`
	State                      types.Int64          `tfsdk:"state"`
	STPPriority                types.Int64          `tfsdk:"stp_priority"`
	STPVersion                 types.String         `tfsdk:"stp_version"`
	SwitchVLANEnabled          types.Bool           `tfsdk:"switch_vlan_enabled"`
	Type                       types.String         `tfsdk:"type"`
	Volume                     types.Int64          `tfsdk:"volume"`
	XBaresipPassword           types.String         `tfsdk:"x_baresip_password"`
	AllowAdoption              types.Bool           `tfsdk:"allow_adoption"`
	ForgetOnDestroy            types.Bool           `tfsdk:"forget_on_destroy"`
	PortOverride               types.Set            `tfsdk:"port_override"`
	Timeouts                   timeouts.Value       `tfsdk:"timeouts"`
}

// deviceGenFields is every unifi_device attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func deviceGenFields() []resourcekit.Field[deviceKitModel, ui.Device] {
	return []resourcekit.Field[deviceKitModel, ui.Device]{
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "adopted",
			Model: func(m *deviceKitModel) *types.Bool { return &m.Adopted },
			SDK:   func(s *ui.Device) *bool { return &s.Adopted },
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "bandsteering_mode",
			Model: func(m *deviceKitModel) *types.String { return &m.BandsteeringMode },
			SDK:   func(s *ui.Device) *string { return &s.BandsteeringMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "disabled",
			Model: func(m *deviceKitModel) *types.Bool { return &m.Disabled },
			SDK:   func(s *ui.Device) *bool { return &s.Disabled },
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "flowctrl_enabled",
			Model: func(m *deviceKitModel) *types.Bool { return &m.FlowctrlEnabled },
			SDK:   func(s *ui.Device) *bool { return &s.FlowctrlEnabled },
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "jumboframe_enabled",
			Model: func(m *deviceKitModel) *types.Bool { return &m.JumboframeEnabled },
			SDK:   func(s *ui.Device) *bool { return &s.JumboframeEnabled },
		},
		resourcekit.Int64PtrField[deviceKitModel, ui.Device]{
			Wire:     "lcm_brightness",
			Model:    func(m *deviceKitModel) *types.Int64 { return &m.LcmBrightness },
			SDK:      func(s *ui.Device) **int64 { return &s.LcmBrightness },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "lcm_brightness_override",
			Model: func(m *deviceKitModel) *types.Bool { return &m.LcmBrightnessOverride },
			SDK:   func(s *ui.Device) *bool { return &s.LcmBrightnessOverride },
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "lcm_idle_timeout_override",
			Model: func(m *deviceKitModel) *types.Bool { return &m.LcmIdleTimeoutOverride },
			SDK:   func(s *ui.Device) *bool { return &s.LcmIDleTimeoutOverride },
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "lcm_night_mode_begins",
			Model: func(m *deviceKitModel) *types.String { return &m.LcmNightModeBegins },
			SDK:   func(s *ui.Device) *string { return &s.LcmNightModeBegins },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "lcm_night_mode_ends",
			Model: func(m *deviceKitModel) *types.String { return &m.LcmNightModeEnds },
			SDK:   func(s *ui.Device) *string { return &s.LcmNightModeEnds },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "led_override",
			Model: func(m *deviceKitModel) *types.String { return &m.LedOverride },
			SDK:   func(s *ui.Device) *string { return &s.LedOverride },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "led_override_color",
			Model: func(m *deviceKitModel) *types.String { return &m.LedOverrideColor },
			SDK:   func(s *ui.Device) *string { return &s.LedOverrideColor },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[deviceKitModel, ui.Device]{
			Wire:  "led_override_color_brightness",
			Model: func(m *deviceKitModel) *types.Int64 { return &m.LedOverrideColorBrightness },
			SDK:   func(s *ui.Device) **int64 { return &s.LedOverrideColorBrightness },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "locked",
			Model: func(m *deviceKitModel) *types.Bool { return &m.Locked },
			SDK:   func(s *ui.Device) *bool { return &s.Locked },
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "mesh_sta_vap_enabled",
			Model: func(m *deviceKitModel) *types.Bool { return &m.MeshStaVapEnabled },
			SDK:   func(s *ui.Device) *bool { return &s.MeshStaVapEnabled },
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "mgmt_network_id",
			Model: func(m *deviceKitModel) *types.String { return &m.MgmtNetworkID },
			SDK:   func(s *ui.Device) *string { return &s.MgmtNetworkID },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "model",
			Model: func(m *deviceKitModel) *types.String { return &m.Model },
			SDK:   func(s *ui.Device) *string { return &s.Model },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "name",
			Model: func(m *deviceKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.Device) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "outdoor_mode_override",
			Model: func(m *deviceKitModel) *types.String { return &m.OutdoorModeOverride },
			SDK:   func(s *ui.Device) *string { return &s.OutdoorModeOverride },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "outlet_enabled",
			Model: func(m *deviceKitModel) *types.Bool { return &m.OutletEnabled },
			SDK:   func(s *ui.Device) *bool { return &s.OutletEnabled },
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "poe_mode",
			Model: func(m *deviceKitModel) *types.String { return &m.PoeMode },
			SDK:   func(s *ui.Device) *string { return &s.PoeMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[deviceKitModel, ui.Device]{
			Wire:  "stp_priority",
			Model: func(m *deviceKitModel) *types.Int64 { return &m.STPPriority },
			SDK:   func(s *ui.Device) **int64 { return &s.StpPriority },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "stp_version",
			Model: func(m *deviceKitModel) *types.String { return &m.STPVersion },
			SDK:   func(s *ui.Device) *string { return &s.StpVersion },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[deviceKitModel, ui.Device]{
			Wire:  "switch_vlan_enabled",
			Model: func(m *deviceKitModel) *types.Bool { return &m.SwitchVLANEnabled },
			SDK:   func(s *ui.Device) *bool { return &s.SwitchVLANEnabled },
		},
		resourcekit.Int64PtrField[deviceKitModel, ui.Device]{
			Wire:  "volume",
			Model: func(m *deviceKitModel) *types.Int64 { return &m.Volume },
			SDK:   func(s *ui.Device) **int64 { return &s.Volume },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[deviceKitModel, ui.Device]{
			Wire:  "x_baresip_password",
			Model: func(m *deviceKitModel) *types.String { return &m.XBaresipPassword },
			SDK:   func(s *ui.Device) *string { return &s.BaresipPassword },
			Elide: resourcekit.KeepZero,
		},
	}
}
