// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type dhcpOptionKitModel struct {
	ID       types.String   `tfsdk:"id"`
	Site     types.String   `tfsdk:"site"`
	Code     types.String   `tfsdk:"code"`
	Name     types.String   `tfsdk:"name"`
	Signed   types.Bool     `tfsdk:"signed"`
	Type     types.String   `tfsdk:"type"`
	Width    types.Int64    `tfsdk:"width"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

// dhcpOptionGenFields is every unifi_dhcp_option attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func dhcpOptionGenFields() []resourcekit.Field[dhcpOptionKitModel, ui.DHCPOption] {
	return []resourcekit.Field[dhcpOptionKitModel, ui.DHCPOption]{
		resourcekit.StringField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "code",
			Model: func(m *dhcpOptionKitModel) *types.String { return &m.Code },
			SDK:   func(s *ui.DHCPOption) *string { return &s.Code },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "name",
			Model: func(m *dhcpOptionKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.DHCPOption) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "signed",
			Model: func(m *dhcpOptionKitModel) *types.Bool { return &m.Signed },
			SDK:   func(s *ui.DHCPOption) *bool { return &s.Signed },
		},
		resourcekit.StringField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "type",
			Model: func(m *dhcpOptionKitModel) *types.String { return &m.Type },
			SDK:   func(s *ui.DHCPOption) *string { return &s.Type },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:     "width",
			Model:    func(m *dhcpOptionKitModel) *types.Int64 { return &m.Width },
			SDK:      func(s *ui.DHCPOption) **int64 { return &s.Width },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
	}
}
