// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/listresource_dhcp_option"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_dhcp_option"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type dhcpOptionKitModel struct {
	ID       types.String   `tfsdk:"id"`
	Site     types.String   `tfsdk:"site"`
	Code     types.String   `tfsdk:"code"`
	Name     types.String   `tfsdk:"name"`
	Signed   types.Bool     `tfsdk:"signed"`
	Type     types.String   `tfsdk:"type"`
	Width    types.Int64    `tfsdk:"width"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

// dhcpOptionGenFields is every unifi_dhcp_option attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func dhcpOptionGenFields() []resourcekit.Field[dhcpOptionKitModel, ui.DHCPOption] {
	return []resourcekit.Field[dhcpOptionKitModel, ui.DHCPOption]{
		resourcekit.StringField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "code",
			Model: func(m *dhcpOptionKitModel) *types.String { return &m.Code },
			SDK:   func(s *ui.DHCPOption) *string { return &s.Code },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "name",
			Model: func(m *dhcpOptionKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.DHCPOption) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "signed",
			Model: func(m *dhcpOptionKitModel) *types.Bool { return &m.Signed },
			SDK:   func(s *ui.DHCPOption) *bool { return &s.Signed },
		},
		resourcekit.StringField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:  "type",
			Model: func(m *dhcpOptionKitModel) *types.String { return &m.Type },
			SDK:   func(s *ui.DHCPOption) *string { return &s.Type },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[dhcpOptionKitModel, ui.DHCPOption]{
			Wire:     "width",
			Model:    func(m *dhcpOptionKitModel) *types.Int64 { return &m.Width },
			SDK:      func(s *ui.DHCPOption) **int64 { return &s.Width },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
	}
}

func dhcpOptionKitSpec() resourcekit.Spec[dhcpOptionKitModel, ui.DHCPOption] {
	return resourcekit.Spec[dhcpOptionKitModel, ui.DHCPOption]{
		TypeName: "dhcp_option",
		Subject:  "DHCP Option",
		IDWire:   "_id",
		New:      func() *ui.DHCPOption { return &ui.DHCPOption{} },
		ID:       func(m *dhcpOptionKitModel) *types.String { return &m.ID },
		Site:     func(m *dhcpOptionKitModel) *types.String { return &m.Site },
		Timeouts: func(m *dhcpOptionKitModel) *timeouts.Value { return &m.Timeouts },
		Fields:   dhcpOptionGenFields(),
		// Seeded here as well as in dhcpOptionKitBackend, because Configure
		// binds the real Backend and a unit test calling ToModel on an
		// unconfigured spec would otherwise dereference nil.
		Backend: resourcekit.Backend[ui.DHCPOption]{
			GetID: func(s *ui.DHCPOption) string { return s.ID },
			SetID: func(s *ui.DHCPOption, id string) { s.ID = id },
		},
	}
}

func dhcpOptionKitSchema() resourcekit.SchemaSpec {
	return resourcekit.SchemaSpec{
		Resource: resource_dhcp_option.DhcpOptionResourceSchema,
		Timeouts: timeouts.Opts{Create: true, Read: true, Update: true, Delete: true},
	}
}

func dhcpOptionKitList() resourcekit.ListSpec[ui.DHCPOption] {
	return resourcekit.ListSpec[ui.DHCPOption]{
		ConfigSchema: listresource_dhcp_option.DhcpOptionListResourceSchema,
		DisplayName: func(s *ui.DHCPOption) string {
			if s.Name != "" {
				return s.Name
			}
			return s.ID
		},
		Filters: map[string]func(*ui.DHCPOption) string{
			"name": func(s *ui.DHCPOption) string { return s.Name },
		},
	}
}

func dhcpOptionKitBackend(client *ui.ApiClient) resourcekit.Backend[ui.DHCPOption] {
	return resourcekit.Backend[ui.DHCPOption]{
		Create: func(ctx context.Context, site string, in *ui.DHCPOption) (*ui.DHCPOption, error) {
			return client.CreateDHCPOption(ctx, site, in)
		},
		Read: func(ctx context.Context, site, id string) (*ui.DHCPOption, error) {
			return client.GetDHCPOption(ctx, site, id)
		},
		UpdateFields: func(
			ctx context.Context, site string, in *ui.DHCPOption, fields ...string,
		) (*ui.DHCPOption, error) {
			return client.UpdateDHCPOptionFields(ctx, site, in, fields...)
		},
		Delete: func(ctx context.Context, site, id string) error {
			return client.DeleteDHCPOption(ctx, site, id)
		},
		List: func(ctx context.Context, site string) ([]ui.DHCPOption, error) {
			return client.ListDHCPOption(ctx, site)
		},
		GetID: func(s *ui.DHCPOption) string { return s.ID },
		SetID: func(s *ui.DHCPOption, id string) { s.ID = id },
	}
}
