// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type dnsRecordKitModel struct {
	ID         types.String         `tfsdk:"id"`
	Site       types.String         `tfsdk:"site"`
	Enabled    types.Bool           `tfsdk:"enabled"`
	Name       types.String         `tfsdk:"name"`
	Port       types.Int64          `tfsdk:"port"`
	Priority   types.Int64          `tfsdk:"priority"`
	RecordType types.String         `tfsdk:"record_type"`
	TTL        timetypes.GoDuration `tfsdk:"ttl"`
	Value      types.String         `tfsdk:"value"`
	Weight     types.Int64          `tfsdk:"weight"`
	Timeouts   timeouts.Value       `tfsdk:"timeouts"`
}

// dnsRecordGenFields is every unifi_dns_record attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func dnsRecordGenFields() []resourcekit.Field[dnsRecordKitModel, ui.DNSRecord] {
	return []resourcekit.Field[dnsRecordKitModel, ui.DNSRecord]{
		resourcekit.BoolField[dnsRecordKitModel, ui.DNSRecord]{
			Wire:  "enabled",
			Model: func(m *dnsRecordKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.DNSRecord) *bool { return &s.Enabled },
		},
		resourcekit.StringField[dnsRecordKitModel, ui.DNSRecord]{
			Wire:  "key",
			Model: func(m *dnsRecordKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.DNSRecord) *string { return &s.Key },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64Field[dnsRecordKitModel, ui.DNSRecord]{
			Wire:  "priority",
			Model: func(m *dnsRecordKitModel) *types.Int64 { return &m.Priority },
			SDK:   func(s *ui.DNSRecord) *int64 { return &s.Priority },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[dnsRecordKitModel, ui.DNSRecord]{
			Wire:  "record_type",
			Model: func(m *dnsRecordKitModel) *types.String { return &m.RecordType },
			SDK:   func(s *ui.DNSRecord) *string { return &s.RecordType },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[dnsRecordKitModel, ui.DNSRecord]{
			Wire:  "value",
			Model: func(m *dnsRecordKitModel) *types.String { return &m.Value },
			SDK:   func(s *ui.DNSRecord) *string { return &s.Value },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64Field[dnsRecordKitModel, ui.DNSRecord]{
			Wire:  "weight",
			Model: func(m *dnsRecordKitModel) *types.Int64 { return &m.Weight },
			SDK:   func(s *ui.DNSRecord) *int64 { return &s.Weight },
			Elide: resourcekit.NullZero,
		},
	}
}
