// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/listresource_dpi_app"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_dpi_app"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type dpiAppKitModel struct {
	ID             types.String   `tfsdk:"id"`
	Site           types.String   `tfsdk:"site"`
	Apps           types.List     `tfsdk:"apps"`
	Blocked        types.Bool     `tfsdk:"blocked"`
	Cats           types.List     `tfsdk:"cats"`
	Enabled        types.Bool     `tfsdk:"enabled"`
	Log            types.Bool     `tfsdk:"log"`
	Name           types.String   `tfsdk:"name"`
	QoSRateMaxDown types.Int64    `tfsdk:"qos_rate_max_down"`
	QoSRateMaxUp   types.Int64    `tfsdk:"qos_rate_max_up"`
	Timeouts       timeouts.Value `tfsdk:"timeouts"`
}

// dpiAppGenFields is every unifi_dpi_app attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func dpiAppGenFields() []resourcekit.Field[dpiAppKitModel, ui.DpiApp] {
	return []resourcekit.Field[dpiAppKitModel, ui.DpiApp]{
		resourcekit.Int64ListField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "apps",
			Model: func(m *dpiAppKitModel) *types.List { return &m.Apps },
			SDK:   func(s *ui.DpiApp) *[]int64 { return &s.Apps },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "blocked",
			Model: func(m *dpiAppKitModel) *types.Bool { return &m.Blocked },
			SDK:   func(s *ui.DpiApp) *bool { return &s.Blocked },
		},
		resourcekit.Int64ListField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "cats",
			Model: func(m *dpiAppKitModel) *types.List { return &m.Cats },
			SDK:   func(s *ui.DpiApp) *[]int64 { return &s.Cats },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "enabled",
			Model: func(m *dpiAppKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.DpiApp) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "log",
			Model: func(m *dpiAppKitModel) *types.Bool { return &m.Log },
			SDK:   func(s *ui.DpiApp) *bool { return &s.Log },
		},
		resourcekit.StringField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "name",
			Model: func(m *dpiAppKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.DpiApp) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[dpiAppKitModel, ui.DpiApp]{
			Wire:     "qos_rate_max_down",
			Model:    func(m *dpiAppKitModel) *types.Int64 { return &m.QoSRateMaxDown },
			SDK:      func(s *ui.DpiApp) **int64 { return &s.QOSRateMaxDown },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[dpiAppKitModel, ui.DpiApp]{
			Wire:     "qos_rate_max_up",
			Model:    func(m *dpiAppKitModel) *types.Int64 { return &m.QoSRateMaxUp },
			SDK:      func(s *ui.DpiApp) **int64 { return &s.QOSRateMaxUp },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
	}
}

func dpiAppKitSpec() resourcekit.Spec[dpiAppKitModel, ui.DpiApp] {
	return resourcekit.Spec[dpiAppKitModel, ui.DpiApp]{
		TypeName: "dpi_app",
		Subject:  "DPI Application",
		IDWire:   "_id",
		New:      func() *ui.DpiApp { return &ui.DpiApp{} },
		ID:       func(m *dpiAppKitModel) *types.String { return &m.ID },
		Site:     func(m *dpiAppKitModel) *types.String { return &m.Site },
		Timeouts: func(m *dpiAppKitModel) *timeouts.Value { return &m.Timeouts },
		Fields:   dpiAppGenFields(),
		// Seeded here as well as in dpiAppKitBackend, because Configure
		// binds the real Backend and a unit test calling ToModel on an
		// unconfigured spec would otherwise dereference nil.
		Backend: resourcekit.Backend[ui.DpiApp]{
			GetID: func(s *ui.DpiApp) string { return s.ID },
			SetID: func(s *ui.DpiApp, id string) { s.ID = id },
		},
	}
}

func dpiAppKitSchema() resourcekit.SchemaSpec {
	return resourcekit.SchemaSpec{
		Resource: resource_dpi_app.DpiAppResourceSchema,
		Timeouts: timeouts.Opts{Create: true, Read: true, Update: true, Delete: true},
	}
}

func dpiAppKitList() resourcekit.ListSpec[ui.DpiApp] {
	return resourcekit.ListSpec[ui.DpiApp]{
		ConfigSchema: listresource_dpi_app.DpiAppListResourceSchema,
		DisplayName: func(s *ui.DpiApp) string {
			if s.Name != "" {
				return s.Name
			}
			return s.ID
		},
		Filters: map[string]func(*ui.DpiApp) string{
			"name": func(s *ui.DpiApp) string { return s.Name },
		},
	}
}

func dpiAppKitBackend(client *ui.ApiClient) resourcekit.Backend[ui.DpiApp] {
	return resourcekit.Backend[ui.DpiApp]{
		Create: func(ctx context.Context, site string, in *ui.DpiApp) (*ui.DpiApp, error) {
			return client.CreateDpiApp(ctx, site, in)
		},
		Read: func(ctx context.Context, site, id string) (*ui.DpiApp, error) {
			return client.GetDpiApp(ctx, site, id)
		},
		UpdateFields: func(
			ctx context.Context, site string, in *ui.DpiApp, fields ...string,
		) (*ui.DpiApp, error) {
			return client.UpdateDpiAppFields(ctx, site, in, fields...)
		},
		Delete: func(ctx context.Context, site, id string) error {
			return client.DeleteDpiApp(ctx, site, id)
		},
		List: func(ctx context.Context, site string) ([]ui.DpiApp, error) {
			return client.ListDpiApp(ctx, site)
		},
		GetID: func(s *ui.DpiApp) string { return s.ID },
		SetID: func(s *ui.DpiApp, id string) { s.ID = id },
	}
}
