// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type dpiGroupKitModel struct {
	ID        types.String   `tfsdk:"id"`
	Site      types.String   `tfsdk:"site"`
	DpiappIDs types.List     `tfsdk:"dpiapp_ids"`
	Enabled   types.Bool     `tfsdk:"enabled"`
	Name      types.String   `tfsdk:"name"`
	Timeouts  timeouts.Value `tfsdk:"timeouts"`
}

// dpiGroupGenFields is every unifi_dpi_group attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func dpiGroupGenFields() []resourcekit.Field[dpiGroupKitModel, ui.DpiGroup] {
	return []resourcekit.Field[dpiGroupKitModel, ui.DpiGroup]{
		resourcekit.StringListField[dpiGroupKitModel, ui.DpiGroup]{
			Wire:  "dpiapp_ids",
			Model: func(m *dpiGroupKitModel) *types.List { return &m.DpiappIDs },
			SDK:   func(s *ui.DpiGroup) *[]string { return &s.DPIappIDs },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[dpiGroupKitModel, ui.DpiGroup]{
			Wire:  "enabled",
			Model: func(m *dpiGroupKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.DpiGroup) *bool { return &s.Enabled },
		},
		resourcekit.StringField[dpiGroupKitModel, ui.DpiGroup]{
			Wire:  "name",
			Model: func(m *dpiGroupKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.DpiGroup) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
	}
}
