// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type dpiAppKitModel struct {
	ID             types.String   `tfsdk:"id"`
	Site           types.String   `tfsdk:"site"`
	Apps           types.List     `tfsdk:"apps"`
	Blocked        types.Bool     `tfsdk:"blocked"`
	Cats           types.List     `tfsdk:"cats"`
	Enabled        types.Bool     `tfsdk:"enabled"`
	Log            types.Bool     `tfsdk:"log"`
	Name           types.String   `tfsdk:"name"`
	QoSRateMaxDown types.Int64    `tfsdk:"qos_rate_max_down"`
	QoSRateMaxUp   types.Int64    `tfsdk:"qos_rate_max_up"`
	Timeouts       timeouts.Value `tfsdk:"timeouts"`
}

// dpiAppGenFields is every unifi_dpi_app attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func dpiAppGenFields() []resourcekit.Field[dpiAppKitModel, ui.DpiApp] {
	return []resourcekit.Field[dpiAppKitModel, ui.DpiApp]{
		resourcekit.Int64ListField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "apps",
			Model: func(m *dpiAppKitModel) *types.List { return &m.Apps },
			SDK:   func(s *ui.DpiApp) *[]int64 { return &s.Apps },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "blocked",
			Model: func(m *dpiAppKitModel) *types.Bool { return &m.Blocked },
			SDK:   func(s *ui.DpiApp) *bool { return &s.Blocked },
		},
		resourcekit.Int64ListField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "cats",
			Model: func(m *dpiAppKitModel) *types.List { return &m.Cats },
			SDK:   func(s *ui.DpiApp) *[]int64 { return &s.Cats },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "enabled",
			Model: func(m *dpiAppKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.DpiApp) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "log",
			Model: func(m *dpiAppKitModel) *types.Bool { return &m.Log },
			SDK:   func(s *ui.DpiApp) *bool { return &s.Log },
		},
		resourcekit.StringField[dpiAppKitModel, ui.DpiApp]{
			Wire:  "name",
			Model: func(m *dpiAppKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.DpiApp) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[dpiAppKitModel, ui.DpiApp]{
			Wire:     "qos_rate_max_down",
			Model:    func(m *dpiAppKitModel) *types.Int64 { return &m.QoSRateMaxDown },
			SDK:      func(s *ui.DpiApp) **int64 { return &s.QOSRateMaxDown },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[dpiAppKitModel, ui.DpiApp]{
			Wire:     "qos_rate_max_up",
			Model:    func(m *dpiAppKitModel) *types.Int64 { return &m.QoSRateMaxUp },
			SDK:      func(s *ui.DpiApp) **int64 { return &s.QOSRateMaxUp },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
	}
}
