// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type dynamicDnsKitModel struct {
	ID        types.String   `tfsdk:"id"`
	Site      types.String   `tfsdk:"site"`
	HostName  types.String   `tfsdk:"host_name"`
	Interface types.String   `tfsdk:"interface"`
	Login     types.String   `tfsdk:"login"`
	Server    types.String   `tfsdk:"server"`
	Service   types.String   `tfsdk:"service"`
	Password  types.String   `tfsdk:"password"`
	Timeouts  timeouts.Value `tfsdk:"timeouts"`
}

// dynamicDnsGenFields is every unifi_dynamic_dns attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func dynamicDnsGenFields() []resourcekit.Field[dynamicDnsKitModel, ui.DynamicDNS] {
	return []resourcekit.Field[dynamicDnsKitModel, ui.DynamicDNS]{
		resourcekit.StringField[dynamicDnsKitModel, ui.DynamicDNS]{
			Wire:  "host_name",
			Model: func(m *dynamicDnsKitModel) *types.String { return &m.HostName },
			SDK:   func(s *ui.DynamicDNS) *string { return &s.HostName },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[dynamicDnsKitModel, ui.DynamicDNS]{
			Wire:  "interface",
			Model: func(m *dynamicDnsKitModel) *types.String { return &m.Interface },
			SDK:   func(s *ui.DynamicDNS) *string { return &s.Interface },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[dynamicDnsKitModel, ui.DynamicDNS]{
			Wire:  "login",
			Model: func(m *dynamicDnsKitModel) *types.String { return &m.Login },
			SDK:   func(s *ui.DynamicDNS) *string { return &s.Login },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[dynamicDnsKitModel, ui.DynamicDNS]{
			Wire:  "server",
			Model: func(m *dynamicDnsKitModel) *types.String { return &m.Server },
			SDK:   func(s *ui.DynamicDNS) *string { return &s.Server },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[dynamicDnsKitModel, ui.DynamicDNS]{
			Wire:  "service",
			Model: func(m *dynamicDnsKitModel) *types.String { return &m.Service },
			SDK:   func(s *ui.DynamicDNS) *string { return &s.Service },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[dynamicDnsKitModel, ui.DynamicDNS]{
			Wire:  "x_password",
			Model: func(m *dynamicDnsKitModel) *types.String { return &m.Password },
			SDK:   func(s *ui.DynamicDNS) *string { return &s.Password },
			Elide: resourcekit.NullZero,
		},
	}
}
