// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type firewallZoneKitModel struct {
	ID          types.String   `tfsdk:"id"`
	Site        types.String   `tfsdk:"site"`
	DefaultZone types.Bool     `tfsdk:"default_zone"`
	Name        types.String   `tfsdk:"name"`
	NetworkIDs  types.List     `tfsdk:"network_ids"`
	ZoneKey     types.String   `tfsdk:"zone_key"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}

// firewallZoneGenFields is every unifi_firewall_zone attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func firewallZoneGenFields() []resourcekit.Field[firewallZoneKitModel, ui.FirewallZone] {
	return []resourcekit.Field[firewallZoneKitModel, ui.FirewallZone]{
		resourcekit.StringField[firewallZoneKitModel, ui.FirewallZone]{
			Wire:  "name",
			Model: func(m *firewallZoneKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.FirewallZone) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringListField[firewallZoneKitModel, ui.FirewallZone]{
			Wire:  "network_ids",
			Model: func(m *firewallZoneKitModel) *types.List { return &m.NetworkIDs },
			SDK:   func(s *ui.FirewallZone) *[]string { return &s.NetworkIDs },
			Elide: resourcekit.KeepZero,
		},
	}
}
