// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type firewallGroupKitModel struct {
	ID       types.String   `tfsdk:"id"`
	Site     types.String   `tfsdk:"site"`
	Members  types.Set      `tfsdk:"members"`
	Type     types.String   `tfsdk:"type"`
	Name     types.String   `tfsdk:"name"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

// firewallGroupGenFields is every unifi_firewall_group attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func firewallGroupGenFields() []resourcekit.Field[firewallGroupKitModel, ui.FirewallGroup] {
	return []resourcekit.Field[firewallGroupKitModel, ui.FirewallGroup]{
		resourcekit.StringSetField[firewallGroupKitModel, ui.FirewallGroup]{
			Wire:  "group_members",
			Model: func(m *firewallGroupKitModel) *types.Set { return &m.Members },
			SDK:   func(s *ui.FirewallGroup) *[]string { return &s.GroupMembers },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallGroupKitModel, ui.FirewallGroup]{
			Wire:  "group_type",
			Model: func(m *firewallGroupKitModel) *types.String { return &m.Type },
			SDK:   func(s *ui.FirewallGroup) *string { return &s.GroupType },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallGroupKitModel, ui.FirewallGroup]{
			Wire:  "name",
			Model: func(m *firewallGroupKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.FirewallGroup) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
	}
}
