// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type firewallPolicyKitModel struct {
	ID                  types.String   `tfsdk:"id"`
	Site                types.String   `tfsdk:"site"`
	Action              types.String   `tfsdk:"action"`
	ConnectionStateType types.String   `tfsdk:"connection_state_type"`
	ConnectionStates    types.List     `tfsdk:"connection_states"`
	CreateAllowRespond  types.Bool     `tfsdk:"create_allow_respond"`
	Description         types.String   `tfsdk:"description"`
	Destination         types.Object   `tfsdk:"destination"`
	Enabled             types.Bool     `tfsdk:"enabled"`
	ICMPTypename        types.String   `tfsdk:"icmp_typename"`
	ICMPV6Typename      types.String   `tfsdk:"icmp_v6_typename"`
	Index               types.Int64    `tfsdk:"index"`
	IPVersion           types.String   `tfsdk:"ip_version"`
	Logging             types.Bool     `tfsdk:"logging"`
	Name                types.String   `tfsdk:"name"`
	Protocol            types.String   `tfsdk:"protocol"`
	Schedule            types.Object   `tfsdk:"schedule"`
	Source              types.Object   `tfsdk:"source"`
	Timeouts            timeouts.Value `tfsdk:"timeouts"`
}

// firewallPolicyGenFields is every unifi_firewall_policy attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func firewallPolicyGenFields() []resourcekit.Field[firewallPolicyKitModel, ui.FirewallPolicy] {
	return []resourcekit.Field[firewallPolicyKitModel, ui.FirewallPolicy]{
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "action",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.Action },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.Action },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "connection_state_type",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.ConnectionStateType },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.ConnectionStateType },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringListField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "connection_states",
			Model: func(m *firewallPolicyKitModel) *types.List { return &m.ConnectionStates },
			SDK:   func(s *ui.FirewallPolicy) *[]string { return &s.ConnectionStates },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "create_allow_respond",
			Model: func(m *firewallPolicyKitModel) *types.Bool { return &m.CreateAllowRespond },
			SDK:   func(s *ui.FirewallPolicy) *bool { return &s.CreateAllowRespond },
		},
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "description",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.Description },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.Description },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "enabled",
			Model: func(m *firewallPolicyKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.FirewallPolicy) *bool { return &s.Enabled },
		},
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "icmp_typename",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.ICMPTypename },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.ICMPTypename },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "icmp_v6_typename",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.ICMPV6Typename },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.ICMPV6Typename },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "ip_version",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.IPVersion },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.Version },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "logging",
			Model: func(m *firewallPolicyKitModel) *types.Bool { return &m.Logging },
			SDK:   func(s *ui.FirewallPolicy) *bool { return &s.Logging },
		},
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "name",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallPolicyKitModel, ui.FirewallPolicy]{
			Wire:  "protocol",
			Model: func(m *firewallPolicyKitModel) *types.String { return &m.Protocol },
			SDK:   func(s *ui.FirewallPolicy) *string { return &s.Protocol },
			Elide: resourcekit.NullZero,
		},
	}
}
