// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-nettypes/hwtypes"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type firewallRuleKitModel struct {
	ID                    types.String       `tfsdk:"id"`
	Site                  types.String       `tfsdk:"site"`
	Action                types.String       `tfsdk:"action"`
	DstAddress            types.String       `tfsdk:"dst_address"`
	DstAddressIPv6        types.String       `tfsdk:"dst_address_ipv6"`
	DstFirewallGroupIDs   types.Set          `tfsdk:"dst_firewall_group_ids"`
	DstNetworkID          types.String       `tfsdk:"dst_network_id"`
	DstNetworkType        types.String       `tfsdk:"dst_network_type"`
	DstPort               types.String       `tfsdk:"dst_port"`
	Enabled               types.Bool         `tfsdk:"enabled"`
	ICMPTypename          types.String       `tfsdk:"icmp_typename"`
	ICMPV6Typename        types.String       `tfsdk:"icmp_v6_typename"`
	IPSec                 types.String       `tfsdk:"ip_sec"`
	Logging               types.Bool         `tfsdk:"logging"`
	Name                  types.String       `tfsdk:"name"`
	Protocol              types.String       `tfsdk:"protocol"`
	ProtocolMatchExcepted types.Bool         `tfsdk:"protocol_match_excepted"`
	ProtocolV6            types.String       `tfsdk:"protocol_v6"`
	RuleIndex             types.Int64        `tfsdk:"rule_index"`
	Ruleset               types.String       `tfsdk:"ruleset"`
	SettingPreference     types.String       `tfsdk:"setting_preference"`
	SrcAddress            types.String       `tfsdk:"src_address"`
	SrcAddressIPv6        types.String       `tfsdk:"src_address_ipv6"`
	SrcFirewallGroupIDs   types.Set          `tfsdk:"src_firewall_group_ids"`
	SrcMAC                hwtypes.MACAddress `tfsdk:"src_mac"`
	SrcNetworkID          types.String       `tfsdk:"src_network_id"`
	SrcNetworkType        types.String       `tfsdk:"src_network_type"`
	SrcPort               types.String       `tfsdk:"src_port"`
	StateEstablished      types.Bool         `tfsdk:"state_established"`
	StateInvalid          types.Bool         `tfsdk:"state_invalid"`
	StateNew              types.Bool         `tfsdk:"state_new"`
	StateRelated          types.Bool         `tfsdk:"state_related"`
	Timeouts              timeouts.Value     `tfsdk:"timeouts"`
}

// firewallRuleGenFields is every unifi_firewall_rule attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func firewallRuleGenFields() []resourcekit.Field[firewallRuleKitModel, ui.FirewallRule] {
	return []resourcekit.Field[firewallRuleKitModel, ui.FirewallRule]{
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "action",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.Action },
			SDK:   func(s *ui.FirewallRule) *string { return &s.Action },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "dst_address",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.DstAddress },
			SDK:   func(s *ui.FirewallRule) *string { return &s.DstAddress },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "dst_address_ipv6",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.DstAddressIPv6 },
			SDK:   func(s *ui.FirewallRule) *string { return &s.DstAddressIPV6 },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringSetField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "dst_firewallgroup_ids",
			Model: func(m *firewallRuleKitModel) *types.Set { return &m.DstFirewallGroupIDs },
			SDK:   func(s *ui.FirewallRule) *[]string { return &s.DstFirewallGroupIDs },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "dst_networkconf_id",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.DstNetworkID },
			SDK:   func(s *ui.FirewallRule) *string { return &s.DstNetworkID },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "dst_port",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.DstPort },
			SDK:   func(s *ui.FirewallRule) *string { return &s.DstPort },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "enabled",
			Model: func(m *firewallRuleKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.FirewallRule) *bool { return &s.Enabled },
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "icmp_typename",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.ICMPTypename },
			SDK:   func(s *ui.FirewallRule) *string { return &s.ICMPTypename },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "icmpv6_typename",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.ICMPV6Typename },
			SDK:   func(s *ui.FirewallRule) *string { return &s.ICMPv6Typename },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "ipsec",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.IPSec },
			SDK:   func(s *ui.FirewallRule) *string { return &s.IPSec },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "logging",
			Model: func(m *firewallRuleKitModel) *types.Bool { return &m.Logging },
			SDK:   func(s *ui.FirewallRule) *bool { return &s.Logging },
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "name",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.FirewallRule) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "protocol",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.Protocol },
			SDK:   func(s *ui.FirewallRule) *string { return &s.Protocol },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "protocol_match_excepted",
			Model: func(m *firewallRuleKitModel) *types.Bool { return &m.ProtocolMatchExcepted },
			SDK:   func(s *ui.FirewallRule) *bool { return &s.ProtocolMatchExcepted },
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "protocol_v6",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.ProtocolV6 },
			SDK:   func(s *ui.FirewallRule) *string { return &s.ProtocolV6 },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "rule_index",
			Model: func(m *firewallRuleKitModel) *types.Int64 { return &m.RuleIndex },
			SDK:   func(s *ui.FirewallRule) **int64 { return &s.RuleIndex },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "ruleset",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.Ruleset },
			SDK:   func(s *ui.FirewallRule) *string { return &s.Ruleset },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "setting_preference",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.SettingPreference },
			SDK:   func(s *ui.FirewallRule) *string { return &s.SettingPreference },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "src_address",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.SrcAddress },
			SDK:   func(s *ui.FirewallRule) *string { return &s.SrcAddress },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "src_address_ipv6",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.SrcAddressIPv6 },
			SDK:   func(s *ui.FirewallRule) *string { return &s.SrcAddressIPV6 },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringSetField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "src_firewallgroup_ids",
			Model: func(m *firewallRuleKitModel) *types.Set { return &m.SrcFirewallGroupIDs },
			SDK:   func(s *ui.FirewallRule) *[]string { return &s.SrcFirewallGroupIDs },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "src_networkconf_id",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.SrcNetworkID },
			SDK:   func(s *ui.FirewallRule) *string { return &s.SrcNetworkID },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "src_port",
			Model: func(m *firewallRuleKitModel) *types.String { return &m.SrcPort },
			SDK:   func(s *ui.FirewallRule) *string { return &s.SrcPort },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "state_established",
			Model: func(m *firewallRuleKitModel) *types.Bool { return &m.StateEstablished },
			SDK:   func(s *ui.FirewallRule) *bool { return &s.StateEstablished },
		},
		resourcekit.BoolField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "state_invalid",
			Model: func(m *firewallRuleKitModel) *types.Bool { return &m.StateInvalid },
			SDK:   func(s *ui.FirewallRule) *bool { return &s.StateInvalid },
		},
		resourcekit.BoolField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "state_new",
			Model: func(m *firewallRuleKitModel) *types.Bool { return &m.StateNew },
			SDK:   func(s *ui.FirewallRule) *bool { return &s.StateNew },
		},
		resourcekit.BoolField[firewallRuleKitModel, ui.FirewallRule]{
			Wire:  "state_related",
			Model: func(m *firewallRuleKitModel) *types.Bool { return &m.StateRelated },
			SDK:   func(s *ui.FirewallRule) *bool { return &s.StateRelated },
		},
	}
}
