// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type hotspotPackageKitModel struct {
	ID                             types.String   `tfsdk:"id"`
	Site                           types.String   `tfsdk:"site"`
	Amount                         types.Float64  `tfsdk:"amount"`
	ChargedAS                      types.String   `tfsdk:"charged_as"`
	Currency                       types.String   `tfsdk:"currency"`
	CustomPaymentFieldsEnabled     types.Bool     `tfsdk:"custom_payment_fields_enabled"`
	Hours                          types.Int64    `tfsdk:"hours"`
	Index                          types.Int64    `tfsdk:"index"`
	LimitDown                      types.Int64    `tfsdk:"limit_down"`
	LimitOverwrite                 types.Bool     `tfsdk:"limit_overwrite"`
	LimitQuota                     types.Int64    `tfsdk:"limit_quota"`
	LimitUp                        types.Int64    `tfsdk:"limit_up"`
	Name                           types.String   `tfsdk:"name"`
	PaymentFieldsAddressEnabled    types.Bool     `tfsdk:"payment_fields_address_enabled"`
	PaymentFieldsAddressRequired   types.Bool     `tfsdk:"payment_fields_address_required"`
	PaymentFieldsCityEnabled       types.Bool     `tfsdk:"payment_fields_city_enabled"`
	PaymentFieldsCityRequired      types.Bool     `tfsdk:"payment_fields_city_required"`
	PaymentFieldsCountryEnabled    types.Bool     `tfsdk:"payment_fields_country_enabled"`
	PaymentFieldsCountryRequired   types.Bool     `tfsdk:"payment_fields_country_required"`
	PaymentFieldsEmailEnabled      types.Bool     `tfsdk:"payment_fields_email_enabled"`
	PaymentFieldsEmailRequired     types.Bool     `tfsdk:"payment_fields_email_required"`
	PaymentFieldsFirstNameEnabled  types.Bool     `tfsdk:"payment_fields_first_name_enabled"`
	PaymentFieldsFirstNameRequired types.Bool     `tfsdk:"payment_fields_first_name_required"`
	PaymentFieldsLastNameEnabled   types.Bool     `tfsdk:"payment_fields_last_name_enabled"`
	PaymentFieldsLastNameRequired  types.Bool     `tfsdk:"payment_fields_last_name_required"`
	PaymentFieldsStateEnabled      types.Bool     `tfsdk:"payment_fields_state_enabled"`
	PaymentFieldsStateRequired     types.Bool     `tfsdk:"payment_fields_state_required"`
	PaymentFieldsZipEnabled        types.Bool     `tfsdk:"payment_fields_zip_enabled"`
	PaymentFieldsZipRequired       types.Bool     `tfsdk:"payment_fields_zip_required"`
	TrialDurationMinutes           types.Int64    `tfsdk:"trial_duration_minutes"`
	TrialReset                     types.Float64  `tfsdk:"trial_reset"`
	Timeouts                       timeouts.Value `tfsdk:"timeouts"`
}

// hotspotPackageGenFields is every unifi_hotspot_package attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func hotspotPackageGenFields() []resourcekit.Field[hotspotPackageKitModel, ui.HotspotPackage] {
	return []resourcekit.Field[hotspotPackageKitModel, ui.HotspotPackage]{
		resourcekit.StringField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "charged_as",
			Model: func(m *hotspotPackageKitModel) *types.String { return &m.ChargedAS },
			SDK:   func(s *ui.HotspotPackage) *string { return &s.ChargedAs },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "currency",
			Model: func(m *hotspotPackageKitModel) *types.String { return &m.Currency },
			SDK:   func(s *ui.HotspotPackage) *string { return &s.Currency },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "custom_payment_fields_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.CustomPaymentFieldsEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.CustomPaymentFieldsEnabled },
		},
		resourcekit.Int64PtrField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "hours",
			Model: func(m *hotspotPackageKitModel) *types.Int64 { return &m.Hours },
			SDK:   func(s *ui.HotspotPackage) **int64 { return &s.Hours },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "index",
			Model: func(m *hotspotPackageKitModel) *types.Int64 { return &m.Index },
			SDK:   func(s *ui.HotspotPackage) **int64 { return &s.Index },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "limit_down",
			Model: func(m *hotspotPackageKitModel) *types.Int64 { return &m.LimitDown },
			SDK:   func(s *ui.HotspotPackage) **int64 { return &s.LimitDown },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "limit_overwrite",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.LimitOverwrite },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.LimitOverwrite },
		},
		resourcekit.Int64PtrField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "limit_quota",
			Model: func(m *hotspotPackageKitModel) *types.Int64 { return &m.LimitQuota },
			SDK:   func(s *ui.HotspotPackage) **int64 { return &s.LimitQuota },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "limit_up",
			Model: func(m *hotspotPackageKitModel) *types.Int64 { return &m.LimitUp },
			SDK:   func(s *ui.HotspotPackage) **int64 { return &s.LimitUp },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "name",
			Model: func(m *hotspotPackageKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.HotspotPackage) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_address_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsAddressEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsAddressEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_address_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsAddressRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsAddressRequired },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_city_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsCityEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsCityEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_city_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsCityRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsCityRequired },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_country_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsCountryEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsCountryEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_country_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsCountryRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsCountryRequired },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_email_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsEmailEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsEmailEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_email_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsEmailRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsEmailRequired },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_first_name_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsFirstNameEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsFirstNameEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_first_name_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsFirstNameRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsFirstNameRequired },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_last_name_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsLastNameEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsLastNameEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_last_name_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsLastNameRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsLastNameRequired },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_state_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsStateEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsStateEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_state_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsStateRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsStateRequired },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_zip_enabled",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsZipEnabled },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsZipEnabled },
		},
		resourcekit.BoolField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "payment_fields_zip_required",
			Model: func(m *hotspotPackageKitModel) *types.Bool { return &m.PaymentFieldsZipRequired },
			SDK:   func(s *ui.HotspotPackage) *bool { return &s.PaymentFieldsZipRequired },
		},
		resourcekit.Int64PtrField[hotspotPackageKitModel, ui.HotspotPackage]{
			Wire:  "trial_duration_minutes",
			Model: func(m *hotspotPackageKitModel) *types.Int64 { return &m.TrialDurationMinutes },
			SDK:   func(s *ui.HotspotPackage) **int64 { return &s.TrialDurationMinutes },
			Elide: resourcekit.KeepZero,
		},
	}
}
