// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type hotspotOpKitModel struct {
	ID       types.String   `tfsdk:"id"`
	Site     types.String   `tfsdk:"site"`
	Name     types.String   `tfsdk:"name"`
	Note     types.String   `tfsdk:"note"`
	Password types.String   `tfsdk:"password"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

// hotspotOpGenFields is every unifi_hotspot_op attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func hotspotOpGenFields() []resourcekit.Field[hotspotOpKitModel, ui.HotspotOp] {
	return []resourcekit.Field[hotspotOpKitModel, ui.HotspotOp]{
		resourcekit.StringField[hotspotOpKitModel, ui.HotspotOp]{
			Wire:  "name",
			Model: func(m *hotspotOpKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.HotspotOp) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[hotspotOpKitModel, ui.HotspotOp]{
			Wire:  "note",
			Model: func(m *hotspotOpKitModel) *types.String { return &m.Note },
			SDK:   func(s *ui.HotspotOp) *string { return &s.Note },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[hotspotOpKitModel, ui.HotspotOp]{
			Wire:  "x_password",
			Model: func(m *hotspotOpKitModel) *types.String { return &m.Password },
			SDK:   func(s *ui.HotspotOp) *string { return &s.Password },
			Elide: resourcekit.KeepZero,
		},
	}
}
