// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type natKitModel struct {
	ID                    types.String   `tfsdk:"id"`
	Site                  types.String   `tfsdk:"site"`
	Description           types.String   `tfsdk:"description"`
	DestinationFilter     types.Object   `tfsdk:"destination_filter"`
	Enabled               types.Bool     `tfsdk:"enabled"`
	Exclude               types.Bool     `tfsdk:"exclude"`
	InInterface           types.String   `tfsdk:"in_interface"`
	IPAddress             types.String   `tfsdk:"ip_address"`
	IPVersion             types.String   `tfsdk:"ip_version"`
	IsPredefined          types.Bool     `tfsdk:"is_predefined"`
	Logging               types.Bool     `tfsdk:"logging"`
	OutInterface          types.String   `tfsdk:"out_interface"`
	Port                  types.Int64    `tfsdk:"port"`
	PppoeUseBaseInterface types.Bool     `tfsdk:"pppoe_use_base_interface"`
	Protocol              types.String   `tfsdk:"protocol"`
	RuleIndex             types.Int64    `tfsdk:"rule_index"`
	SettingPreference     types.String   `tfsdk:"setting_preference"`
	SourceFilter          types.Object   `tfsdk:"source_filter"`
	Type                  types.String   `tfsdk:"type"`
	Timeouts              timeouts.Value `tfsdk:"timeouts"`
}

// natGenFields is every unifi_nat attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func natGenFields() []resourcekit.Field[natKitModel, ui.Nat] {
	return []resourcekit.Field[natKitModel, ui.Nat]{
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:  "description",
			Model: func(m *natKitModel) *types.String { return &m.Description },
			SDK:   func(s *ui.Nat) *string { return &s.Description },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[natKitModel, ui.Nat]{
			Wire:  "enabled",
			Model: func(m *natKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.Nat) *bool { return &s.Enabled },
		},
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:      "in_interface",
			Model:     func(m *natKitModel) *types.String { return &m.InInterface },
			SDK:       func(s *ui.Nat) *string { return &s.InInterface },
			Elide:     resourcekit.KeepZero,
			WriteWhen: func(m *natKitModel) bool { return !m.InInterface.IsNull() && m.InInterface.ValueString() != "" },
		},
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:      "ip_address",
			Model:     func(m *natKitModel) *types.String { return &m.IPAddress },
			SDK:       func(s *ui.Nat) *string { return &s.IPAddress },
			Elide:     resourcekit.KeepZero,
			WriteWhen: func(m *natKitModel) bool { return !m.IPAddress.IsNull() && m.IPAddress.ValueString() != "" },
		},
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:  "ip_version",
			Model: func(m *natKitModel) *types.String { return &m.IPVersion },
			SDK:   func(s *ui.Nat) *string { return &s.Version },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[natKitModel, ui.Nat]{
			Wire:  "logging",
			Model: func(m *natKitModel) *types.Bool { return &m.Logging },
			SDK:   func(s *ui.Nat) *bool { return &s.Logging },
		},
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:  "out_interface",
			Model: func(m *natKitModel) *types.String { return &m.OutInterface },
			SDK:   func(s *ui.Nat) *string { return &s.OutInterface },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[natKitModel, ui.Nat]{
			Wire:     "port",
			Model:    func(m *natKitModel) *types.Int64 { return &m.Port },
			SDK:      func(s *ui.Nat) **int64 { return &s.Port },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:  "protocol",
			Model: func(m *natKitModel) *types.String { return &m.Protocol },
			SDK:   func(s *ui.Nat) *string { return &s.Protocol },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:  "setting_preference",
			Model: func(m *natKitModel) *types.String { return &m.SettingPreference },
			SDK:   func(s *ui.Nat) *string { return &s.SettingPreference },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[natKitModel, ui.Nat]{
			Wire:  "type",
			Model: func(m *natKitModel) *types.String { return &m.Type },
			SDK:   func(s *ui.Nat) *string { return &s.Type },
			Elide: resourcekit.NullZero,
		},
	}
}
