// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type ospfRouterKitModel struct {
	ID                                    types.String   `tfsdk:"id"`
	Site                                  types.String   `tfsdk:"site"`
	AnnounceDefaultRoute                  types.Bool     `tfsdk:"announce_default_route"`
	Areas                                 types.List     `tfsdk:"areas"`
	Enabled                               types.Bool     `tfsdk:"enabled"`
	Interfaces                            types.List     `tfsdk:"interfaces"`
	RedistributeBgpRoutes                 types.Bool     `tfsdk:"redistribute_bgp_routes"`
	RedistributeConnectedRoutes           types.Bool     `tfsdk:"redistribute_connected_routes"`
	RedistributeConnectedRoutesMetricType types.String   `tfsdk:"redistribute_connected_routes_metric_type"`
	RedistributeStaticRoutes              types.Bool     `tfsdk:"redistribute_static_routes"`
	RedistributeStaticRoutesMetricType    types.String   `tfsdk:"redistribute_static_routes_metric_type"`
	RouterID                              types.String   `tfsdk:"router_id"`
	Timeouts                              timeouts.Value `tfsdk:"timeouts"`
}

type ospfRouterAreasModel struct {
	AreaID     types.String `tfsdk:"area_id"`
	AreaType   types.String `tfsdk:"area_type"`
	Name       types.String `tfsdk:"name"`
	NetworkIDs types.List   `tfsdk:"network_ids"`
}

var ospfRouterAreasAttrTypes = map[string]attr.Type{
	"area_id":     types.StringType,
	"area_type":   types.StringType,
	"name":        types.StringType,
	"network_ids": types.ListType{ElemType: types.StringType},
}

type ospfRouterInterfacesModel struct {
	AuthenticationType types.String `tfsdk:"authentication_type"`
	Cost               types.String `tfsdk:"cost"`
	DeadInterval       types.String `tfsdk:"dead_interval"`
	HelloInterval      types.String `tfsdk:"hello_interval"`
	NetworkID          types.String `tfsdk:"network_id"`
	PassiveInterface   types.Bool   `tfsdk:"passive_interface"`
	Priority           types.String `tfsdk:"priority"`
}

var ospfRouterInterfacesAttrTypes = map[string]attr.Type{
	"authentication_type": types.StringType,
	"cost":                types.StringType,
	"dead_interval":       types.StringType,
	"hello_interval":      types.StringType,
	"network_id":          types.StringType,
	"passive_interface":   types.BoolType,
	"priority":            types.StringType,
}

// ospfRouterGenFields is every unifi_ospf_router attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func ospfRouterGenFields() []resourcekit.Field[ospfRouterKitModel, ui.OSPFRouter] {
	return []resourcekit.Field[ospfRouterKitModel, ui.OSPFRouter]{
		resourcekit.BoolField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "announce_default_route",
			Model: func(m *ospfRouterKitModel) *types.Bool { return &m.AnnounceDefaultRoute },
			SDK:   func(s *ui.OSPFRouter) *bool { return &s.AnnounceDefaultRoute },
		},
		resourcekit.BoolField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "enabled",
			Model: func(m *ospfRouterKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.OSPFRouter) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "redistribute_bgp_routes",
			Model: func(m *ospfRouterKitModel) *types.Bool { return &m.RedistributeBgpRoutes },
			SDK:   func(s *ui.OSPFRouter) *bool { return &s.RedistributeBgpRoutes },
		},
		resourcekit.BoolField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "redistribute_connected_routes",
			Model: func(m *ospfRouterKitModel) *types.Bool { return &m.RedistributeConnectedRoutes },
			SDK:   func(s *ui.OSPFRouter) *bool { return &s.RedistributeConnectedRoutes },
		},
		resourcekit.StringField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "redistribute_connected_routes_metric_type",
			Model: func(m *ospfRouterKitModel) *types.String { return &m.RedistributeConnectedRoutesMetricType },
			SDK:   func(s *ui.OSPFRouter) *string { return &s.RedistributeConnectedRoutesMetricType },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "redistribute_static_routes",
			Model: func(m *ospfRouterKitModel) *types.Bool { return &m.RedistributeStaticRoutes },
			SDK:   func(s *ui.OSPFRouter) *bool { return &s.RedistributeStaticRoutes },
		},
		resourcekit.StringField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "redistribute_static_routes_metric_type",
			Model: func(m *ospfRouterKitModel) *types.String { return &m.RedistributeStaticRoutesMetricType },
			SDK:   func(s *ui.OSPFRouter) *string { return &s.RedistributeStaticRoutesMetricType },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[ospfRouterKitModel, ui.OSPFRouter]{
			Wire:  "router_id",
			Model: func(m *ospfRouterKitModel) *types.String { return &m.RouterID },
			SDK:   func(s *ui.OSPFRouter) *string { return &s.RouterID },
			Elide: resourcekit.KeepZero,
		},
	}
}
