// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type portForwardKitModel struct {
	ID             types.String   `tfsdk:"id"`
	Site           types.String   `tfsdk:"site"`
	DestinationIPs types.List     `tfsdk:"destination_ips"`
	Enabled        types.Bool     `tfsdk:"enabled"`
	Logging        types.Bool     `tfsdk:"logging"`
	Name           types.String   `tfsdk:"name"`
	Protocol       types.String   `tfsdk:"protocol"`
	Forward        types.Object   `tfsdk:"forward"`
	SourceLimiting types.Object   `tfsdk:"source_limiting"`
	WAN            types.Object   `tfsdk:"wan"`
	Timeouts       timeouts.Value `tfsdk:"timeouts"`
}

type portForwardDestinationIpsModel struct {
	DestinationIP types.String `tfsdk:"destination_ip"`
	Interface     types.String `tfsdk:"interface"`
}

var portForwardDestinationIpsAttrTypes = map[string]attr.Type{
	"destination_ip": types.StringType,
	"interface":      types.StringType,
}

type portForwardForwardModel struct {
	IP   types.String `tfsdk:"ip"`
	Port types.String `tfsdk:"port"`
}

var portForwardForwardAttrTypes = map[string]attr.Type{
	"ip":   types.StringType,
	"port": types.StringType,
}

type portForwardSourceLimitingModel struct {
	Enabled         types.Bool   `tfsdk:"enabled"`
	FirewallGroupID types.String `tfsdk:"firewall_group_id"`
	IP              types.String `tfsdk:"ip"`
	Type            types.String `tfsdk:"type"`
}

var portForwardSourceLimitingAttrTypes = map[string]attr.Type{
	"enabled":           types.BoolType,
	"firewall_group_id": types.StringType,
	"ip":                types.StringType,
	"type":              types.StringType,
}

type portForwardWanModel struct {
	Interface types.String `tfsdk:"interface"`
	IPAddress types.String `tfsdk:"ip_address"`
	Port      types.String `tfsdk:"port"`
}

var portForwardWanAttrTypes = map[string]attr.Type{
	"interface":  types.StringType,
	"ip_address": types.StringType,
	"port":       types.StringType,
}

// portForwardGenFields is every unifi_port_forward attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func portForwardGenFields() []resourcekit.Field[portForwardKitModel, ui.PortForward] {
	return []resourcekit.Field[portForwardKitModel, ui.PortForward]{
		resourcekit.BoolField[portForwardKitModel, ui.PortForward]{
			Wire:  "enabled",
			Model: func(m *portForwardKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.PortForward) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[portForwardKitModel, ui.PortForward]{
			Wire:  "log",
			Model: func(m *portForwardKitModel) *types.Bool { return &m.Logging },
			SDK:   func(s *ui.PortForward) *bool { return &s.Log },
		},
		resourcekit.StringField[portForwardKitModel, ui.PortForward]{
			Wire:  "name",
			Model: func(m *portForwardKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.PortForward) *string { return &s.Name },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[portForwardKitModel, ui.PortForward]{
			Wire:  "proto",
			Model: func(m *portForwardKitModel) *types.String { return &m.Protocol },
			SDK:   func(s *ui.PortForward) *string { return &s.Proto },
			Elide: resourcekit.NullZero,
		},
	}
}
