// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type portProfileKitModel struct {
	ID                            types.String         `tfsdk:"id"`
	Site                          types.String         `tfsdk:"site"`
	Autoneg                       types.Bool           `tfsdk:"autoneg"`
	Dot1xCtrl                     types.String         `tfsdk:"dot1x_ctrl"`
	Dot1xIdleTimeout              timetypes.GoDuration `tfsdk:"dot1x_idle_timeout"`
	EgressRateLimitKbps           types.Int64          `tfsdk:"egress_rate_limit_kbps"`
	EgressRateLimitKbpsEnabled    types.Bool           `tfsdk:"egress_rate_limit_kbps_enabled"`
	ExcludedNetworkconfIDs        types.Set            `tfsdk:"excluded_networkconf_ids"`
	FecMode                       types.String         `tfsdk:"fec_mode"`
	Forward                       types.String         `tfsdk:"forward"`
	FullDuplex                    types.Bool           `tfsdk:"full_duplex"`
	Isolation                     types.Bool           `tfsdk:"isolation"`
	LldpmedEnabled                types.Bool           `tfsdk:"lldpmed_enabled"`
	LldpmedNotifyEnabled          types.Bool           `tfsdk:"lldpmed_notify_enabled"`
	MulticastRouterNetworkconfIDs types.Set            `tfsdk:"multicast_router_networkconf_ids"`
	Name                          types.String         `tfsdk:"name"`
	NativeNetworkconfID           types.String         `tfsdk:"native_networkconf_id"`
	OpMode                        types.String         `tfsdk:"op_mode"`
	PoeMode                       types.String         `tfsdk:"poe_mode"`
	PortKeepaliveEnabled          types.Bool           `tfsdk:"port_keepalive_enabled"`
	PortSecurityEnabled           types.Bool           `tfsdk:"port_security_enabled"`
	PortSecurityMACAddress        types.Set            `tfsdk:"port_security_mac_address"`
	PriorityQueue1Level           types.Int64          `tfsdk:"priority_queue1_level"`
	PriorityQueue2Level           types.Int64          `tfsdk:"priority_queue2_level"`
	PriorityQueue3Level           types.Int64          `tfsdk:"priority_queue3_level"`
	PriorityQueue4Level           types.Int64          `tfsdk:"priority_queue4_level"`
	SettingPreference             types.String         `tfsdk:"setting_preference"`
	Speed                         types.Int64          `tfsdk:"speed"`
	StormctrlBcastEnabled         types.Bool           `tfsdk:"stormctrl_bcast_enabled"`
	StormctrlBcastLevel           types.Int64          `tfsdk:"stormctrl_bcast_level"`
	StormctrlBcastRate            types.Int64          `tfsdk:"stormctrl_bcast_rate"`
	StormctrlMcastEnabled         types.Bool           `tfsdk:"stormctrl_mcast_enabled"`
	StormctrlMcastLevel           types.Int64          `tfsdk:"stormctrl_mcast_level"`
	StormctrlMcastRate            types.Int64          `tfsdk:"stormctrl_mcast_rate"`
	StormctrlType                 types.String         `tfsdk:"stormctrl_type"`
	StormctrlUcastEnabled         types.Bool           `tfsdk:"stormctrl_ucast_enabled"`
	StormctrlUcastLevel           types.Int64          `tfsdk:"stormctrl_ucast_level"`
	StormctrlUcastRate            types.Int64          `tfsdk:"stormctrl_ucast_rate"`
	STPPortMode                   types.Bool           `tfsdk:"stp_port_mode"`
	TaggedVLANMgmt                types.String         `tfsdk:"tagged_vlan_mgmt"`
	VoiceNetworkconfID            types.String         `tfsdk:"voice_networkconf_id"`
	TaggedNetworkconfIDs          types.Set            `tfsdk:"tagged_networkconf_ids"`
	Timeouts                      timeouts.Value       `tfsdk:"timeouts"`
}

// portProfileGenFields is every unifi_port_profile attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func portProfileGenFields() []resourcekit.Field[portProfileKitModel, ui.PortProfile] {
	return []resourcekit.Field[portProfileKitModel, ui.PortProfile]{
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "autoneg",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.Autoneg },
			SDK:   func(s *ui.PortProfile) *bool { return &s.Autoneg },
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:     "egress_rate_limit_kbps",
			Model:    func(m *portProfileKitModel) *types.Int64 { return &m.EgressRateLimitKbps },
			SDK:      func(s *ui.PortProfile) **int64 { return &s.EgressRateLimitKbps },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "egress_rate_limit_kbps_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.EgressRateLimitKbpsEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.EgressRateLimitKbpsEnabled },
		},
		resourcekit.StringField[portProfileKitModel, ui.PortProfile]{
			Wire:  "fec_mode",
			Model: func(m *portProfileKitModel) *types.String { return &m.FecMode },
			SDK:   func(s *ui.PortProfile) *string { return &s.FecMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "full_duplex",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.FullDuplex },
			SDK:   func(s *ui.PortProfile) *bool { return &s.FullDuplex },
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "isolation",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.Isolation },
			SDK:   func(s *ui.PortProfile) *bool { return &s.Isolation },
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "lldpmed_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.LldpmedEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.LldpmedEnabled },
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "lldpmed_notify_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.LldpmedNotifyEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.LldpmedNotifyEnabled },
		},
		resourcekit.StringSetField[portProfileKitModel, ui.PortProfile]{
			Wire:  "multicast_router_networkconf_ids",
			Model: func(m *portProfileKitModel) *types.Set { return &m.MulticastRouterNetworkconfIDs },
			SDK:   func(s *ui.PortProfile) *[]string { return &s.MulticastRouterNetworkIDs },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[portProfileKitModel, ui.PortProfile]{
			Wire:  "name",
			Model: func(m *portProfileKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.PortProfile) *string { return &s.Name },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[portProfileKitModel, ui.PortProfile]{
			Wire:  "native_networkconf_id",
			Model: func(m *portProfileKitModel) *types.String { return &m.NativeNetworkconfID },
			SDK:   func(s *ui.PortProfile) *string { return &s.NATiveNetworkID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[portProfileKitModel, ui.PortProfile]{
			Wire:      "poe_mode",
			Model:     func(m *portProfileKitModel) *types.String { return &m.PoeMode },
			SDK:       func(s *ui.PortProfile) *string { return &s.PoeMode },
			Elide:     resourcekit.NullZero,
			WriteWhen: func(m *portProfileKitModel) bool { return !m.PoeMode.IsNull() && m.PoeMode.ValueString() != "" },
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "port_keepalive_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.PortKeepaliveEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.PortKeepaliveEnabled },
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "port_security_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.PortSecurityEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.PortSecurityEnabled },
		},
		resourcekit.StringSetField[portProfileKitModel, ui.PortProfile]{
			Wire:  "port_security_mac_address",
			Model: func(m *portProfileKitModel) *types.Set { return &m.PortSecurityMACAddress },
			SDK:   func(s *ui.PortProfile) *[]string { return &s.PortSecurityMACAddress },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "priority_queue1_level",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.PriorityQueue1Level },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.PriorityQueue1Level },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "priority_queue2_level",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.PriorityQueue2Level },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.PriorityQueue2Level },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "priority_queue3_level",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.PriorityQueue3Level },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.PriorityQueue3Level },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "priority_queue4_level",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.PriorityQueue4Level },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.PriorityQueue4Level },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[portProfileKitModel, ui.PortProfile]{
			Wire:  "setting_preference",
			Model: func(m *portProfileKitModel) *types.String { return &m.SettingPreference },
			SDK:   func(s *ui.PortProfile) *string { return &s.SettingPreference },
			Elide: resourcekit.NullZero,
			WriteWhen: func(m *portProfileKitModel) bool {
				return !m.SettingPreference.IsNull() && m.SettingPreference.ValueString() != ""
			},
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:     "speed",
			Model:    func(m *portProfileKitModel) *types.Int64 { return &m.Speed },
			SDK:      func(s *ui.PortProfile) **int64 { return &s.Speed },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_bcast_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.StormctrlBcastEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.StormctrlBroadcastastEnabled },
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_bcast_level",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.StormctrlBcastLevel },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.StormctrlBroadcastastLevel },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_bcast_rate",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.StormctrlBcastRate },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.StormctrlBroadcastastRate },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_mcast_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.StormctrlMcastEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.StormctrlMcastEnabled },
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_mcast_level",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.StormctrlMcastLevel },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.StormctrlMcastLevel },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_mcast_rate",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.StormctrlMcastRate },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.StormctrlMcastRate },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_type",
			Model: func(m *portProfileKitModel) *types.String { return &m.StormctrlType },
			SDK:   func(s *ui.PortProfile) *string { return &s.StormctrlType },
			Elide: resourcekit.NullZero,
			WriteWhen: func(m *portProfileKitModel) bool {
				return !m.StormctrlType.IsNull() && m.StormctrlType.ValueString() != ""
			},
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_ucast_enabled",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.StormctrlUcastEnabled },
			SDK:   func(s *ui.PortProfile) *bool { return &s.StormctrlUcastEnabled },
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_ucast_level",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.StormctrlUcastLevel },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.StormctrlUcastLevel },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stormctrl_ucast_rate",
			Model: func(m *portProfileKitModel) *types.Int64 { return &m.StormctrlUcastRate },
			SDK:   func(s *ui.PortProfile) **int64 { return &s.StormctrlUcastRate },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[portProfileKitModel, ui.PortProfile]{
			Wire:  "stp_port_mode",
			Model: func(m *portProfileKitModel) *types.Bool { return &m.STPPortMode },
			SDK:   func(s *ui.PortProfile) *bool { return &s.StpPortMode },
		},
		resourcekit.StringField[portProfileKitModel, ui.PortProfile]{
			Wire:  "voice_networkconf_id",
			Model: func(m *portProfileKitModel) *types.String { return &m.VoiceNetworkconfID },
			SDK:   func(s *ui.PortProfile) *string { return &s.VoiceNetworkID },
			Elide: resourcekit.NullZero,
		},
	}
}
