// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-nettypes/hwtypes"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type powerSupervisorKitModel struct {
	ID                  types.String         `tfsdk:"id"`
	Site                types.String         `tfsdk:"site"`
	DeviceMAC           hwtypes.MACAddress   `tfsdk:"device_mac"`
	ConsecutiveFailures types.Int64          `tfsdk:"consecutive_failures"`
	Enabled             types.Bool           `tfsdk:"enabled"`
	PowerSources        types.List           `tfsdk:"power_sources"`
	HeartbeatInterval   timetypes.GoDuration `tfsdk:"heartbeat_interval"`
	PowerOffDuration    timetypes.GoDuration `tfsdk:"power_off_duration"`
	SilenceThreshold    timetypes.GoDuration `tfsdk:"silence_threshold"`
	Timeouts            timeouts.Value       `tfsdk:"timeouts"`
}

type powerSupervisorPowerSourcesModel struct {
	ClientPsuIndex   types.Int64  `tfsdk:"client_psu_index"`
	PowerSourceIndex types.Int64  `tfsdk:"power_source_index"`
	PowerSourceMAC   types.String `tfsdk:"power_source_mac"`
	PowerSourceType  types.String `tfsdk:"power_source_type"`
}

var powerSupervisorPowerSourcesAttrTypes = map[string]attr.Type{
	"client_psu_index":   types.Int64Type,
	"power_source_index": types.Int64Type,
	"power_source_mac":   types.StringType,
	"power_source_type":  types.StringType,
}

// powerSupervisorGenFields is every unifi_power_supervisor attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func powerSupervisorGenFields() []resourcekit.Field[powerSupervisorKitModel, ui.PowerSupervisor] {
	return []resourcekit.Field[powerSupervisorKitModel, ui.PowerSupervisor]{
		resourcekit.BoolField[powerSupervisorKitModel, ui.PowerSupervisor]{
			Wire:  "enabled",
			Model: func(m *powerSupervisorKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.PowerSupervisor) *bool { return &s.Enabled },
		},
	}
}
