// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type radiusProfileKitModel struct {
	ID                    types.String         `tfsdk:"id"`
	Site                  types.String         `tfsdk:"site"`
	AccountingEnabled     types.Bool           `tfsdk:"accounting_enabled"`
	InterimUpdateEnabled  types.Bool           `tfsdk:"interim_update_enabled"`
	InterimUpdateInterval timetypes.GoDuration `tfsdk:"interim_update_interval"`
	Name                  types.String         `tfsdk:"name"`
	UseUsgAcctServer      types.Bool           `tfsdk:"use_usg_acct_server"`
	UseUsgAuthServer      types.Bool           `tfsdk:"use_usg_auth_server"`
	VLANEnabled           types.Bool           `tfsdk:"vlan_enabled"`
	VLANWLANMode          types.String         `tfsdk:"vlan_wlan_mode"`
	AcctServer            types.List           `tfsdk:"acct_server"`
	AuthServer            types.List           `tfsdk:"auth_server"`
	Timeouts              timeouts.Value       `tfsdk:"timeouts"`
}

// radiusProfileGenFields is every unifi_radius_profile attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func radiusProfileGenFields() []resourcekit.Field[radiusProfileKitModel, ui.RADIUSProfile] {
	return []resourcekit.Field[radiusProfileKitModel, ui.RADIUSProfile]{
		resourcekit.BoolField[radiusProfileKitModel, ui.RADIUSProfile]{
			Wire:  "accounting_enabled",
			Model: func(m *radiusProfileKitModel) *types.Bool { return &m.AccountingEnabled },
			SDK:   func(s *ui.RADIUSProfile) *bool { return &s.AccountingEnabled },
		},
		resourcekit.BoolField[radiusProfileKitModel, ui.RADIUSProfile]{
			Wire:  "interim_update_enabled",
			Model: func(m *radiusProfileKitModel) *types.Bool { return &m.InterimUpdateEnabled },
			SDK:   func(s *ui.RADIUSProfile) *bool { return &s.InterimUpdateEnabled },
		},
		resourcekit.StringField[radiusProfileKitModel, ui.RADIUSProfile]{
			Wire:  "name",
			Model: func(m *radiusProfileKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.RADIUSProfile) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[radiusProfileKitModel, ui.RADIUSProfile]{
			Wire:  "use_usg_acct_server",
			Model: func(m *radiusProfileKitModel) *types.Bool { return &m.UseUsgAcctServer },
			SDK:   func(s *ui.RADIUSProfile) *bool { return &s.UseUsgAcctServer },
		},
		resourcekit.BoolField[radiusProfileKitModel, ui.RADIUSProfile]{
			Wire:  "use_usg_auth_server",
			Model: func(m *radiusProfileKitModel) *types.Bool { return &m.UseUsgAuthServer },
			SDK:   func(s *ui.RADIUSProfile) *bool { return &s.UseUsgAuthServer },
		},
		resourcekit.BoolField[radiusProfileKitModel, ui.RADIUSProfile]{
			Wire:  "vlan_enabled",
			Model: func(m *radiusProfileKitModel) *types.Bool { return &m.VLANEnabled },
			SDK:   func(s *ui.RADIUSProfile) *bool { return &s.VLANEnabled },
		},
		resourcekit.StringField[radiusProfileKitModel, ui.RADIUSProfile]{
			Wire:  "vlan_wlan_mode",
			Model: func(m *radiusProfileKitModel) *types.String { return &m.VLANWLANMode },
			SDK:   func(s *ui.RADIUSProfile) *string { return &s.VLANWLANMode },
			Elide: resourcekit.NullZero,
		},
	}
}
