// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type radiusUserKitModel struct {
	ID               types.String   `tfsdk:"id"`
	Site             types.String   `tfsdk:"site"`
	Name             types.String   `tfsdk:"name"`
	NetworkID        types.String   `tfsdk:"network_id"`
	TunnelConfigType types.String   `tfsdk:"tunnel_config_type"`
	TunnelMediumType types.Int64    `tfsdk:"tunnel_medium_type"`
	TunnelType       types.Int64    `tfsdk:"tunnel_type"`
	VLAN             types.Int64    `tfsdk:"vlan"`
	Password         types.String   `tfsdk:"password"`
	Timeouts         timeouts.Value `tfsdk:"timeouts"`
}

// radiusUserGenFields is every unifi_radius_user attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func radiusUserGenFields() []resourcekit.Field[radiusUserKitModel, ui.Account] {
	return []resourcekit.Field[radiusUserKitModel, ui.Account]{
		resourcekit.StringField[radiusUserKitModel, ui.Account]{
			Wire:  "name",
			Model: func(m *radiusUserKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.Account) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[radiusUserKitModel, ui.Account]{
			Wire:  "networkconf_id",
			Model: func(m *radiusUserKitModel) *types.String { return &m.NetworkID },
			SDK:   func(s *ui.Account) *string { return &s.NetworkID },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[radiusUserKitModel, ui.Account]{
			Wire:  "tunnel_config_type",
			Model: func(m *radiusUserKitModel) *types.String { return &m.TunnelConfigType },
			SDK:   func(s *ui.Account) *string { return &s.TunnelConfigType },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[radiusUserKitModel, ui.Account]{
			Wire:     "tunnel_medium_type",
			Model:    func(m *radiusUserKitModel) *types.Int64 { return &m.TunnelMediumType },
			SDK:      func(s *ui.Account) **int64 { return &s.TunnelMediumType },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[radiusUserKitModel, ui.Account]{
			Wire:     "tunnel_type",
			Model:    func(m *radiusUserKitModel) *types.Int64 { return &m.TunnelType },
			SDK:      func(s *ui.Account) **int64 { return &s.TunnelType },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.StringField[radiusUserKitModel, ui.Account]{
			Wire:  "x_password",
			Model: func(m *radiusUserKitModel) *types.String { return &m.Password },
			SDK:   func(s *ui.Account) *string { return &s.Password },
			Elide: resourcekit.KeepZero,
		},
	}
}
