// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type scheduleTaskKitModel struct {
	ID              types.String   `tfsdk:"id"`
	Site            types.String   `tfsdk:"site"`
	Action          types.String   `tfsdk:"action"`
	CronExpr        types.String   `tfsdk:"cron_expr"`
	ExecuteOnlyOnce types.Bool     `tfsdk:"execute_only_once"`
	Name            types.String   `tfsdk:"name"`
	UpgradeTargets  types.List     `tfsdk:"upgrade_targets"`
	Timeouts        timeouts.Value `tfsdk:"timeouts"`
}

type scheduleTaskUpgradeTargetsModel struct {
	MAC types.String `tfsdk:"mac"`
}

var scheduleTaskUpgradeTargetsAttrTypes = map[string]attr.Type{
	"mac": types.StringType,
}

// scheduleTaskGenFields is every unifi_schedule_task attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func scheduleTaskGenFields() []resourcekit.Field[scheduleTaskKitModel, ui.ScheduleTask] {
	return []resourcekit.Field[scheduleTaskKitModel, ui.ScheduleTask]{
		resourcekit.StringField[scheduleTaskKitModel, ui.ScheduleTask]{
			Wire:  "action",
			Model: func(m *scheduleTaskKitModel) *types.String { return &m.Action },
			SDK:   func(s *ui.ScheduleTask) *string { return &s.Action },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[scheduleTaskKitModel, ui.ScheduleTask]{
			Wire:  "cron_expr",
			Model: func(m *scheduleTaskKitModel) *types.String { return &m.CronExpr },
			SDK:   func(s *ui.ScheduleTask) *string { return &s.CronExpr },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[scheduleTaskKitModel, ui.ScheduleTask]{
			Wire:  "execute_only_once",
			Model: func(m *scheduleTaskKitModel) *types.Bool { return &m.ExecuteOnlyOnce },
			SDK:   func(s *ui.ScheduleTask) *bool { return &s.ExecuteOnlyOnce },
		},
		resourcekit.StringField[scheduleTaskKitModel, ui.ScheduleTask]{
			Wire:  "name",
			Model: func(m *scheduleTaskKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.ScheduleTask) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
	}
}
