// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingIpsecModel struct {
	Ikev2ReauthenticationMethod types.String `tfsdk:"ikev2_reauthentication_method"`
}

var ipsecAttrTypes = map[string]attr.Type{
	"ikev2_reauthentication_method": types.StringType,
}

// ipsecNestedSchema is the ipsec SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func ipsecNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["ipsec"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingIpsecGenFields is every unifi_setting ipsec attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingIpsecGenFields() []resourcekit.Field[settingIpsecModel, settings.Ipsec] {
	return []resourcekit.Field[settingIpsecModel, settings.Ipsec]{
		resourcekit.StringField[settingIpsecModel, settings.Ipsec]{
			Wire:  "ikev2_reauthentication_method",
			Model: func(m *settingIpsecModel) *types.String { return &m.Ikev2ReauthenticationMethod },
			SDK:   func(s *settings.Ipsec) *string { return &s.Ikev2ReauthenticationMethod },
			Elide: resourcekit.KeepZero,
		},
	}
}

// ipsecKitSpec is the ipsec section's Spec: the generated field
// list over settings.Ipsec, with no hook and no conditional write.
func ipsecKitSpec() resourcekit.Spec[settingIpsecModel, settings.Ipsec] {
	return resourcekit.Spec[settingIpsecModel, settings.Ipsec]{
		TypeName: "setting_ipsec",
		Subject:  "IPsec Setting",
		New:      func() *settings.Ipsec { return &settings.Ipsec{} },
		Fields:   settingIpsecGenFields(),
	}
}

// ipsecKitBackend binds ipsecKitSpec to a client: Read is
// GetSetting[*settings.Ipsec], UpdateFields is the masked UpdateSettingFields --
// naming only the fields the plan set.
func ipsecKitBackend(client *ui.ApiClient) resourcekit.Backend[settings.Ipsec] {
	return resourcekit.Backend[settings.Ipsec]{
		Read: func(ctx context.Context, site, _ string) (*settings.Ipsec, error) {
			_, doc, err := ui.GetSetting[*settings.Ipsec](client, ctx, site)
			if err != nil {
				return nil, err
			}
			return doc, nil
		},
		UpdateFields: func(
			ctx context.Context, site string, in *settings.Ipsec, fields ...string,
		) (*settings.Ipsec, error) {
			if err := client.UpdateSettingFields(ctx, site, in, fields...); err != nil {
				return nil, err
			}
			return in, nil
		},
	}
}

// ipsecKitSection builds the ipsec entry for settingResource's
// Sections, bound to client via settingKitSections.
func ipsecKitSection(client *ui.ApiClient) resourcekit.Section[settingResourceModel] {
	spec := ipsecKitSpec()
	spec.Backend = ipsecKitBackend(client)
	return resourcekit.SpecSection[settingResourceModel, settingIpsecModel, settings.Ipsec]{
		SectionName: "ipsec",
		Get:         func(m *settingResourceModel) *types.Object { return &m.Ipsec },
		Set:         func(m *settingResourceModel, o types.Object) { m.Ipsec = o },
		AttrTypes:   ipsecAttrTypes,
		Spec:        spec,
	}
}
