// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingGlobalNetworkModel struct {
	DefaultSecurityPosture types.String `tfsdk:"default_security_posture"`
}

var globalNetworkAttrTypes = map[string]attr.Type{
	"default_security_posture": types.StringType,
}

// globalNetworkNestedSchema is the global_network SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func globalNetworkNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["global_network"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingGlobalNetworkGenFields is every unifi_setting global_network attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingGlobalNetworkGenFields() []resourcekit.Field[settingGlobalNetworkModel, settings.GlobalNetwork] {
	return []resourcekit.Field[settingGlobalNetworkModel, settings.GlobalNetwork]{
		resourcekit.StringField[settingGlobalNetworkModel, settings.GlobalNetwork]{
			Wire:  "default_security_posture",
			Model: func(m *settingGlobalNetworkModel) *types.String { return &m.DefaultSecurityPosture },
			SDK:   func(s *settings.GlobalNetwork) *string { return &s.DefaultSecurityPosture },
			Elide: resourcekit.KeepZero,
		},
	}
}

// globalNetworkKitSpec is the global_network section's Spec: the generated field
// list over settings.GlobalNetwork, with no hook and no conditional write.
func globalNetworkKitSpec() resourcekit.Spec[settingGlobalNetworkModel, settings.GlobalNetwork] {
	return resourcekit.Spec[settingGlobalNetworkModel, settings.GlobalNetwork]{
		TypeName: "setting_global_network",
		Subject:  "Global Network Setting",
		New:      func() *settings.GlobalNetwork { return &settings.GlobalNetwork{} },
		Fields:   settingGlobalNetworkGenFields(),
	}
}

// globalNetworkKitBackend binds globalNetworkKitSpec to a client: Read is
// GetSetting[*settings.GlobalNetwork], UpdateFields is the masked UpdateSettingFields --
// naming only the fields the plan set.
func globalNetworkKitBackend(client *ui.ApiClient) resourcekit.Backend[settings.GlobalNetwork] {
	return resourcekit.Backend[settings.GlobalNetwork]{
		Read: func(ctx context.Context, site, _ string) (*settings.GlobalNetwork, error) {
			_, doc, err := ui.GetSetting[*settings.GlobalNetwork](client, ctx, site)
			if err != nil {
				return nil, err
			}
			return doc, nil
		},
		UpdateFields: func(
			ctx context.Context, site string, in *settings.GlobalNetwork, fields ...string,
		) (*settings.GlobalNetwork, error) {
			if err := client.UpdateSettingFields(ctx, site, in, fields...); err != nil {
				return nil, err
			}
			return in, nil
		},
	}
}

// globalNetworkKitSection builds the global_network entry for settingResource's
// Sections, bound to client via settingKitSections.
func globalNetworkKitSection(client *ui.ApiClient) resourcekit.Section[settingResourceModel] {
	spec := globalNetworkKitSpec()
	spec.Backend = globalNetworkKitBackend(client)
	return resourcekit.SpecSection[settingResourceModel, settingGlobalNetworkModel, settings.GlobalNetwork]{
		SectionName: "global_network",
		Get:         func(m *settingResourceModel) *types.Object { return &m.GlobalNetwork },
		Set:         func(m *settingResourceModel, o types.Object) { m.GlobalNetwork = o },
		AttrTypes:   globalNetworkAttrTypes,
		Spec:        spec,
	}
}
