// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingGuestAccessModel struct {
	Auth                                   types.String `tfsdk:"auth"`
	PortalEnabled                          types.Bool   `tfsdk:"portal_enabled"`
	PortalUseHostname                      types.Bool   `tfsdk:"portal_use_hostname"`
	PortalHostname                         types.String `tfsdk:"portal_hostname"`
	RedirectEnabled                        types.Bool   `tfsdk:"redirect_enabled"`
	RedirectURL                            types.String `tfsdk:"redirect_url"`
	RedirectHTTPS                          types.Bool   `tfsdk:"redirect_https"`
	RedirectToHTTPS                        types.Bool   `tfsdk:"redirect_to_https"`
	Expire                                 types.String `tfsdk:"expire"`
	ExpireNumber                           types.Int64  `tfsdk:"expire_number"`
	ExpireUnit                             types.Int64  `tfsdk:"expire_unit"`
	RADIUSEnabled                          types.Bool   `tfsdk:"radius_enabled"`
	RADIUSAuthType                         types.String `tfsdk:"radius_auth_type"`
	RADIUSDisconnectEnabled                types.Bool   `tfsdk:"radius_disconnect_enabled"`
	RADIUSDisconnectPort                   types.Int64  `tfsdk:"radius_disconnect_port"`
	RadiusprofileID                        types.String `tfsdk:"radiusprofile_id"`
	PasswordEnabled                        types.Bool   `tfsdk:"password_enabled"`
	VoucherEnabled                         types.Bool   `tfsdk:"voucher_enabled"`
	PaymentEnabled                         types.Bool   `tfsdk:"payment_enabled"`
	Gateway                                types.String `tfsdk:"gateway"`
	EcEnabled                              types.Bool   `tfsdk:"ec_enabled"`
	Password                               types.String `tfsdk:"password"`
	FacebookAppSecret                      types.String `tfsdk:"facebook_app_secret"`
	GoogleClientSecret                     types.String `tfsdk:"google_client_secret"`
	WechatAppSecret                        types.String `tfsdk:"wechat_app_secret"`
	WechatSecretKey                        types.String `tfsdk:"wechat_secret_key"`
	AuthorizeLoginid                       types.String `tfsdk:"authorize_loginid"`
	AuthorizeTransactionkey                types.String `tfsdk:"authorize_transactionkey"`
	PaypalUsername                         types.String `tfsdk:"paypal_username"`
	PaypalPassword                         types.String `tfsdk:"paypal_password"`
	PaypalSignature                        types.String `tfsdk:"paypal_signature"`
	QuickpayAgreementid                    types.String `tfsdk:"quickpay_agreementid"`
	QuickpayMerchantid                     types.String `tfsdk:"quickpay_merchantid"`
	QuickpayApikey                         types.String `tfsdk:"quickpay_apikey"`
	MerchantwarriorMerchantuuid            types.String `tfsdk:"merchantwarrior_merchantuuid"`
	MerchantwarriorApikey                  types.String `tfsdk:"merchantwarrior_apikey"`
	MerchantwarriorApipassphrase           types.String `tfsdk:"merchantwarrior_apipassphrase"`
	IppayTerminalid                        types.String `tfsdk:"ippay_terminalid"`
	StripeApiKey                           types.String `tfsdk:"stripe_api_key"`
	RestrictedDNSEnabled                   types.Bool   `tfsdk:"restricted_dns_enabled"`
	RestrictedDNSServers                   types.List   `tfsdk:"restricted_dns_servers"`
	FacebookEnabled                        types.Bool   `tfsdk:"facebook_enabled"`
	FacebookAppID                          types.String `tfsdk:"facebook_app_id"`
	FacebookScopeEmail                     types.Bool   `tfsdk:"facebook_scope_email"`
	GoogleEnabled                          types.Bool   `tfsdk:"google_enabled"`
	GoogleClientID                         types.String `tfsdk:"google_client_id"`
	GoogleDomain                           types.String `tfsdk:"google_domain"`
	GoogleScopeEmail                       types.Bool   `tfsdk:"google_scope_email"`
	WechatEnabled                          types.Bool   `tfsdk:"wechat_enabled"`
	WechatAppID                            types.String `tfsdk:"wechat_app_id"`
	WechatShopID                           types.String `tfsdk:"wechat_shop_id"`
	AuthorizeUseSandbox                    types.Bool   `tfsdk:"authorize_use_sandbox"`
	IppayUseSandbox                        types.Bool   `tfsdk:"ippay_use_sandbox"`
	MerchantwarriorUseSandbox              types.Bool   `tfsdk:"merchantwarrior_use_sandbox"`
	PaypalUseSandbox                       types.Bool   `tfsdk:"paypal_use_sandbox"`
	QuickpayTestmode                       types.Bool   `tfsdk:"quickpay_testmode"`
	AuthURL                                types.String `tfsdk:"auth_url"`
	CustomIP                               types.String `tfsdk:"custom_ip"`
	VoucherCustomized                      types.Bool   `tfsdk:"voucher_customized"`
	PortalCustomized                       types.Bool   `tfsdk:"portal_customized"`
	PortalCustomizedAuthenticationText     types.String `tfsdk:"portal_customized_authentication_text"`
	PortalCustomizedBgColor                types.String `tfsdk:"portal_customized_bg_color"`
	PortalCustomizedBgImageEnabled         types.Bool   `tfsdk:"portal_customized_bg_image_enabled"`
	PortalCustomizedBgImageFilename        types.String `tfsdk:"portal_customized_bg_image_filename"`
	PortalCustomizedBgImageTile            types.Bool   `tfsdk:"portal_customized_bg_image_tile"`
	PortalCustomizedBgType                 types.String `tfsdk:"portal_customized_bg_type"`
	PortalCustomizedBoxColor               types.String `tfsdk:"portal_customized_box_color"`
	PortalCustomizedBoxLinkColor           types.String `tfsdk:"portal_customized_box_link_color"`
	PortalCustomizedBoxOpacity             types.Int64  `tfsdk:"portal_customized_box_opacity"`
	PortalCustomizedBoxRADIUS              types.Int64  `tfsdk:"portal_customized_box_radius"`
	PortalCustomizedBoxTextColor           types.String `tfsdk:"portal_customized_box_text_color"`
	PortalCustomizedButtonColor            types.String `tfsdk:"portal_customized_button_color"`
	PortalCustomizedButtonText             types.String `tfsdk:"portal_customized_button_text"`
	PortalCustomizedButtonTextColor        types.String `tfsdk:"portal_customized_button_text_color"`
	PortalCustomizedLanguages              types.List   `tfsdk:"portal_customized_languages"`
	PortalCustomizedLinkColor              types.String `tfsdk:"portal_customized_link_color"`
	PortalCustomizedLogoEnabled            types.Bool   `tfsdk:"portal_customized_logo_enabled"`
	PortalCustomizedLogoFilename           types.String `tfsdk:"portal_customized_logo_filename"`
	PortalCustomizedLogoPosition           types.String `tfsdk:"portal_customized_logo_position"`
	PortalCustomizedLogoSize               types.Int64  `tfsdk:"portal_customized_logo_size"`
	PortalCustomizedSuccessText            types.String `tfsdk:"portal_customized_success_text"`
	PortalCustomizedTextColor              types.String `tfsdk:"portal_customized_text_color"`
	PortalCustomizedTitle                  types.String `tfsdk:"portal_customized_title"`
	PortalCustomizedTos                    types.String `tfsdk:"portal_customized_tos"`
	PortalCustomizedTosEnabled             types.Bool   `tfsdk:"portal_customized_tos_enabled"`
	PortalCustomizedUnsplashAuthorName     types.String `tfsdk:"portal_customized_unsplash_author_name"`
	PortalCustomizedUnsplashAuthorUsername types.String `tfsdk:"portal_customized_unsplash_author_username"`
	PortalCustomizedWelcomeText            types.String `tfsdk:"portal_customized_welcome_text"`
	PortalCustomizedWelcomeTextEnabled     types.Bool   `tfsdk:"portal_customized_welcome_text_enabled"`
	PortalCustomizedWelcomeTextPosition    types.String `tfsdk:"portal_customized_welcome_text_position"`
}

var guestAccessAttrTypes = map[string]attr.Type{
	"auth":                                       types.StringType,
	"auth_url":                                   types.StringType,
	"authorize_loginid":                          types.StringType,
	"authorize_transactionkey":                   types.StringType,
	"authorize_use_sandbox":                      types.BoolType,
	"custom_ip":                                  types.StringType,
	"ec_enabled":                                 types.BoolType,
	"expire":                                     types.StringType,
	"expire_number":                              types.Int64Type,
	"expire_unit":                                types.Int64Type,
	"facebook_app_id":                            types.StringType,
	"facebook_app_secret":                        types.StringType,
	"facebook_enabled":                           types.BoolType,
	"facebook_scope_email":                       types.BoolType,
	"gateway":                                    types.StringType,
	"google_client_id":                           types.StringType,
	"google_client_secret":                       types.StringType,
	"google_domain":                              types.StringType,
	"google_enabled":                             types.BoolType,
	"google_scope_email":                         types.BoolType,
	"ippay_terminalid":                           types.StringType,
	"ippay_use_sandbox":                          types.BoolType,
	"merchantwarrior_apikey":                     types.StringType,
	"merchantwarrior_apipassphrase":              types.StringType,
	"merchantwarrior_merchantuuid":               types.StringType,
	"merchantwarrior_use_sandbox":                types.BoolType,
	"password":                                   types.StringType,
	"password_enabled":                           types.BoolType,
	"payment_enabled":                            types.BoolType,
	"paypal_password":                            types.StringType,
	"paypal_signature":                           types.StringType,
	"paypal_use_sandbox":                         types.BoolType,
	"paypal_username":                            types.StringType,
	"portal_customized":                          types.BoolType,
	"portal_customized_authentication_text":      types.StringType,
	"portal_customized_bg_color":                 types.StringType,
	"portal_customized_bg_image_enabled":         types.BoolType,
	"portal_customized_bg_image_filename":        types.StringType,
	"portal_customized_bg_image_tile":            types.BoolType,
	"portal_customized_bg_type":                  types.StringType,
	"portal_customized_box_color":                types.StringType,
	"portal_customized_box_link_color":           types.StringType,
	"portal_customized_box_opacity":              types.Int64Type,
	"portal_customized_box_radius":               types.Int64Type,
	"portal_customized_box_text_color":           types.StringType,
	"portal_customized_button_color":             types.StringType,
	"portal_customized_button_text":              types.StringType,
	"portal_customized_button_text_color":        types.StringType,
	"portal_customized_languages":                types.ListType{ElemType: types.StringType},
	"portal_customized_link_color":               types.StringType,
	"portal_customized_logo_enabled":             types.BoolType,
	"portal_customized_logo_filename":            types.StringType,
	"portal_customized_logo_position":            types.StringType,
	"portal_customized_logo_size":                types.Int64Type,
	"portal_customized_success_text":             types.StringType,
	"portal_customized_text_color":               types.StringType,
	"portal_customized_title":                    types.StringType,
	"portal_customized_tos":                      types.StringType,
	"portal_customized_tos_enabled":              types.BoolType,
	"portal_customized_unsplash_author_name":     types.StringType,
	"portal_customized_unsplash_author_username": types.StringType,
	"portal_customized_welcome_text":             types.StringType,
	"portal_customized_welcome_text_enabled":     types.BoolType,
	"portal_customized_welcome_text_position":    types.StringType,
	"portal_enabled":                             types.BoolType,
	"portal_hostname":                            types.StringType,
	"portal_use_hostname":                        types.BoolType,
	"quickpay_agreementid":                       types.StringType,
	"quickpay_apikey":                            types.StringType,
	"quickpay_merchantid":                        types.StringType,
	"quickpay_testmode":                          types.BoolType,
	"radius_auth_type":                           types.StringType,
	"radius_disconnect_enabled":                  types.BoolType,
	"radius_disconnect_port":                     types.Int64Type,
	"radius_enabled":                             types.BoolType,
	"radiusprofile_id":                           types.StringType,
	"redirect_enabled":                           types.BoolType,
	"redirect_https":                             types.BoolType,
	"redirect_to_https":                          types.BoolType,
	"redirect_url":                               types.StringType,
	"restricted_dns_enabled":                     types.BoolType,
	"restricted_dns_servers":                     types.ListType{ElemType: types.StringType},
	"stripe_api_key":                             types.StringType,
	"voucher_customized":                         types.BoolType,
	"voucher_enabled":                            types.BoolType,
	"wechat_app_id":                              types.StringType,
	"wechat_app_secret":                          types.StringType,
	"wechat_enabled":                             types.BoolType,
	"wechat_secret_key":                          types.StringType,
	"wechat_shop_id":                             types.StringType,
}

// guestAccessNestedSchema is the guest_access SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func guestAccessNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["guest_access"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingGuestAccessGenFields is every unifi_setting guest_access attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingGuestAccessGenFields() []resourcekit.Field[settingGuestAccessModel, settings.GuestAccess] {
	return []resourcekit.Field[settingGuestAccessModel, settings.GuestAccess]{
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "auth",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.Auth },
			SDK:   func(s *settings.GuestAccess) *string { return &s.Auth },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalEnabled },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_use_hostname",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalUseHostname },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalUseHostname },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_hostname",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalHostname },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalHostname },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "redirect_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.RedirectEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.RedirectEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "redirect_url",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.RedirectURL },
			SDK:   func(s *settings.GuestAccess) *string { return &s.RedirectUrl },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "redirect_https",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.RedirectHTTPS },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.RedirectHttps },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "redirect_to_https",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.RedirectToHTTPS },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.RedirectToHttps },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "expire",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.Expire },
			SDK:   func(s *settings.GuestAccess) *string { return &s.Expire },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:     "expire_number",
			Model:    func(m *settingGuestAccessModel) *types.Int64 { return &m.ExpireNumber },
			SDK:      func(s *settings.GuestAccess) **int64 { return &s.ExpireNumber },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:     "expire_unit",
			Model:    func(m *settingGuestAccessModel) *types.Int64 { return &m.ExpireUnit },
			SDK:      func(s *settings.GuestAccess) **int64 { return &s.ExpireUnit },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "radius_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.RADIUSEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.RADIUSEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "radius_auth_type",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.RADIUSAuthType },
			SDK:   func(s *settings.GuestAccess) *string { return &s.RADIUSAuthType },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "radius_disconnect_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.RADIUSDisconnectEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.RADIUSDisconnectEnabled },
		},
		resourcekit.Int64PtrField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:     "radius_disconnect_port",
			Model:    func(m *settingGuestAccessModel) *types.Int64 { return &m.RADIUSDisconnectPort },
			SDK:      func(s *settings.GuestAccess) **int64 { return &s.RADIUSDisconnectPort },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "radiusprofile_id",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.RadiusprofileID },
			SDK:   func(s *settings.GuestAccess) *string { return &s.RADIUSProfileID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "password_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PasswordEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PasswordEnabled },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "voucher_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.VoucherEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.VoucherEnabled },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "payment_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PaymentEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PaymentEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "gateway",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.Gateway },
			SDK:   func(s *settings.GuestAccess) *string { return &s.Gateway },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "ec_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.EcEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.EcEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_password",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.Password },
			SDK:   func(s *settings.GuestAccess) *string { return &s.Password },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_facebook_app_secret",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.FacebookAppSecret },
			SDK:   func(s *settings.GuestAccess) *string { return &s.FacebookAppSecret },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_google_client_secret",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.GoogleClientSecret },
			SDK:   func(s *settings.GuestAccess) *string { return &s.GoogleClientSecret },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_wechat_app_secret",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.WechatAppSecret },
			SDK:   func(s *settings.GuestAccess) *string { return &s.WechatAppSecret },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_wechat_secret_key",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.WechatSecretKey },
			SDK:   func(s *settings.GuestAccess) *string { return &s.WechatSecretKey },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_authorize_loginid",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.AuthorizeLoginid },
			SDK:   func(s *settings.GuestAccess) *string { return &s.AuthorizeLoginid },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_authorize_transactionkey",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.AuthorizeTransactionkey },
			SDK:   func(s *settings.GuestAccess) *string { return &s.AuthorizeTransactionkey },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_paypal_username",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PaypalUsername },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PaypalUsername },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_paypal_password",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PaypalPassword },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PaypalPassword },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_paypal_signature",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PaypalSignature },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PaypalSignature },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_quickpay_agreementid",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.QuickpayAgreementid },
			SDK:   func(s *settings.GuestAccess) *string { return &s.QuickpayAgreementid },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_quickpay_merchantid",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.QuickpayMerchantid },
			SDK:   func(s *settings.GuestAccess) *string { return &s.QuickpayMerchantid },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_quickpay_apikey",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.QuickpayApikey },
			SDK:   func(s *settings.GuestAccess) *string { return &s.QuickpayApikey },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_merchantwarrior_merchantuuid",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.MerchantwarriorMerchantuuid },
			SDK:   func(s *settings.GuestAccess) *string { return &s.MerchantwarriorMerchantuuid },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_merchantwarrior_apikey",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.MerchantwarriorApikey },
			SDK:   func(s *settings.GuestAccess) *string { return &s.MerchantwarriorApikey },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_merchantwarrior_apipassphrase",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.MerchantwarriorApipassphrase },
			SDK:   func(s *settings.GuestAccess) *string { return &s.MerchantwarriorApipassphrase },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_ippay_terminalid",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.IppayTerminalid },
			SDK:   func(s *settings.GuestAccess) *string { return &s.IPpayTerminalid },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "x_stripe_api_key",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.StripeApiKey },
			SDK:   func(s *settings.GuestAccess) *string { return &s.StripeApiKey },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "restricted_dns_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.RestrictedDNSEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.RestrictedDNSEnabled },
		},
		resourcekit.StringListField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "restricted_dns_servers",
			Model: func(m *settingGuestAccessModel) *types.List { return &m.RestrictedDNSServers },
			SDK:   func(s *settings.GuestAccess) *[]string { return &s.RestrictedDNSServers },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "facebook_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.FacebookEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.FacebookEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "facebook_app_id",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.FacebookAppID },
			SDK:   func(s *settings.GuestAccess) *string { return &s.FacebookAppID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "facebook_scope_email",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.FacebookScopeEmail },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.FacebookScopeEmail },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "google_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.GoogleEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.GoogleEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "google_client_id",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.GoogleClientID },
			SDK:   func(s *settings.GuestAccess) *string { return &s.GoogleClientID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "google_domain",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.GoogleDomain },
			SDK:   func(s *settings.GuestAccess) *string { return &s.GoogleDomain },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "google_scope_email",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.GoogleScopeEmail },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.GoogleScopeEmail },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "wechat_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.WechatEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.WechatEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "wechat_app_id",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.WechatAppID },
			SDK:   func(s *settings.GuestAccess) *string { return &s.WechatAppID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "wechat_shop_id",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.WechatShopID },
			SDK:   func(s *settings.GuestAccess) *string { return &s.WechatShopID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "authorize_use_sandbox",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.AuthorizeUseSandbox },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.AuthorizeUseSandbox },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "ippay_use_sandbox",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.IppayUseSandbox },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.IPpayUseSandbox },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "merchantwarrior_use_sandbox",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.MerchantwarriorUseSandbox },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.MerchantwarriorUseSandbox },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "paypal_use_sandbox",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PaypalUseSandbox },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PaypalUseSandbox },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "quickpay_testmode",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.QuickpayTestmode },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.QuickpayTestmode },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "auth_url",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.AuthURL },
			SDK:   func(s *settings.GuestAccess) *string { return &s.AuthUrl },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "custom_ip",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.CustomIP },
			SDK:   func(s *settings.GuestAccess) *string { return &s.CustomIP },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "voucher_customized",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.VoucherCustomized },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.VoucherCustomized },
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalCustomized },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalCustomized },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_authentication_text",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedAuthenticationText },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedAuthenticationText },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_bg_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedBgColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedBgColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_bg_image_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalCustomizedBgImageEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalCustomizedBgImageEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_bg_image_filename",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedBgImageFilename },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedBgImageFilename },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_bg_image_tile",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalCustomizedBgImageTile },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalCustomizedBgImageTile },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_bg_type",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedBgType },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedBgType },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_box_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedBoxColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedBoxColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_box_link_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedBoxLinkColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedBoxLinkColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:     "portal_customized_box_opacity",
			Model:    func(m *settingGuestAccessModel) *types.Int64 { return &m.PortalCustomizedBoxOpacity },
			SDK:      func(s *settings.GuestAccess) **int64 { return &s.PortalCustomizedBoxOpacity },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_box_radius",
			Model: func(m *settingGuestAccessModel) *types.Int64 { return &m.PortalCustomizedBoxRADIUS },
			SDK:   func(s *settings.GuestAccess) **int64 { return &s.PortalCustomizedBoxRADIUS },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_box_text_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedBoxTextColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedBoxTextColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_button_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedButtonColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedButtonColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_button_text",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedButtonText },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedButtonText },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_button_text_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedButtonTextColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedButtonTextColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringListField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_languages",
			Model: func(m *settingGuestAccessModel) *types.List { return &m.PortalCustomizedLanguages },
			SDK:   func(s *settings.GuestAccess) *[]string { return &s.PortalCustomizedLanguages },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_link_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedLinkColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedLinkColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_logo_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalCustomizedLogoEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalCustomizedLogoEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_logo_filename",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedLogoFilename },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedLogoFilename },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_logo_position",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedLogoPosition },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedLogoPosition },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:     "portal_customized_logo_size",
			Model:    func(m *settingGuestAccessModel) *types.Int64 { return &m.PortalCustomizedLogoSize },
			SDK:      func(s *settings.GuestAccess) **int64 { return &s.PortalCustomizedLogoSize },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_success_text",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedSuccessText },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedSuccessText },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_text_color",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedTextColor },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedTextColor },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_title",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedTitle },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedTitle },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_tos",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedTos },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedTos },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_tos_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalCustomizedTosEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalCustomizedTosEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_unsplash_author_name",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedUnsplashAuthorName },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedUnsplashAuthorName },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_unsplash_author_username",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedUnsplashAuthorUsername },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedUnsplashAuthorUsername },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_welcome_text",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedWelcomeText },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedWelcomeText },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_welcome_text_enabled",
			Model: func(m *settingGuestAccessModel) *types.Bool { return &m.PortalCustomizedWelcomeTextEnabled },
			SDK:   func(s *settings.GuestAccess) *bool { return &s.PortalCustomizedWelcomeTextEnabled },
		},
		resourcekit.StringField[settingGuestAccessModel, settings.GuestAccess]{
			Wire:  "portal_customized_welcome_text_position",
			Model: func(m *settingGuestAccessModel) *types.String { return &m.PortalCustomizedWelcomeTextPosition },
			SDK:   func(s *settings.GuestAccess) *string { return &s.PortalCustomizedWelcomeTextPosition },
			Elide: resourcekit.NullZero,
		},
	}
}
