// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingDohModel struct {
	CustomServers types.List   `tfsdk:"custom_servers"`
	ServerNames   types.List   `tfsdk:"server_names"`
	State         types.String `tfsdk:"state"`
}

type dohCustomServersModel struct {
	Enabled    types.Bool   `tfsdk:"enabled"`
	SdnsStamp  types.String `tfsdk:"sdns_stamp"`
	ServerName types.String `tfsdk:"server_name"`
}

var dohCustomServersAttrTypes = map[string]attr.Type{
	"enabled":     types.BoolType,
	"sdns_stamp":  types.StringType,
	"server_name": types.StringType,
}

var dohAttrTypes = map[string]attr.Type{
	"custom_servers": types.ListType{ElemType: types.ObjectType{AttrTypes: dohCustomServersAttrTypes}},
	"server_names":   types.ListType{ElemType: types.StringType},
	"state":          types.StringType,
}

// dohNestedSchema is the doh SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func dohNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["doh"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingDohGenFields is every unifi_setting doh attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingDohGenFields() []resourcekit.Field[settingDohModel, settings.Doh] {
	return []resourcekit.Field[settingDohModel, settings.Doh]{
		resourcekit.StringListField[settingDohModel, settings.Doh]{
			Wire:  "server_names",
			Model: func(m *settingDohModel) *types.List { return &m.ServerNames },
			SDK:   func(s *settings.Doh) *[]string { return &s.ServerNames },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingDohModel, settings.Doh]{
			Wire:  "state",
			Model: func(m *settingDohModel) *types.String { return &m.State },
			SDK:   func(s *settings.Doh) *string { return &s.State },
			Elide: resourcekit.NullZero,
		},
	}
}
