// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingSslInspectionModel struct {
	State types.String `tfsdk:"state"`
}

var sslInspectionAttrTypes = map[string]attr.Type{
	"state": types.StringType,
}

// sslInspectionNestedSchema is the ssl_inspection SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func sslInspectionNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["ssl_inspection"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingSslInspectionGenFields is every unifi_setting ssl_inspection attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingSslInspectionGenFields() []resourcekit.Field[settingSslInspectionModel, settings.SslInspection] {
	return []resourcekit.Field[settingSslInspectionModel, settings.SslInspection]{
		resourcekit.StringField[settingSslInspectionModel, settings.SslInspection]{
			Wire:  "state",
			Model: func(m *settingSslInspectionModel) *types.String { return &m.State },
			SDK:   func(s *settings.SslInspection) *string { return &s.State },
			Elide: resourcekit.NullZero,
		},
	}
}
