// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingNetflowModel struct {
	AutoEngineIDEnabled types.Bool   `tfsdk:"auto_engine_id_enabled"`
	Enabled             types.Bool   `tfsdk:"enabled"`
	EngineID            types.Int64  `tfsdk:"engine_id"`
	ExportFrequency     types.Int64  `tfsdk:"export_frequency"`
	NetworkIDs          types.List   `tfsdk:"network_ids"`
	Port                types.Int64  `tfsdk:"port"`
	RefreshRate         types.Int64  `tfsdk:"refresh_rate"`
	SamplingMode        types.String `tfsdk:"sampling_mode"`
	SamplingRate        types.Int64  `tfsdk:"sampling_rate"`
	Server              types.String `tfsdk:"server"`
	Version             types.Int64  `tfsdk:"version"`
}

var netflowAttrTypes = map[string]attr.Type{
	"auto_engine_id_enabled": types.BoolType,
	"enabled":                types.BoolType,
	"engine_id":              types.Int64Type,
	"export_frequency":       types.Int64Type,
	"network_ids":            types.ListType{ElemType: types.StringType},
	"port":                   types.Int64Type,
	"refresh_rate":           types.Int64Type,
	"sampling_mode":          types.StringType,
	"sampling_rate":          types.Int64Type,
	"server":                 types.StringType,
	"version":                types.Int64Type,
}

// netflowNestedSchema is the netflow SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func netflowNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["netflow"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingNetflowGenFields is every unifi_setting netflow attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingNetflowGenFields() []resourcekit.Field[settingNetflowModel, settings.Netflow] {
	return []resourcekit.Field[settingNetflowModel, settings.Netflow]{
		resourcekit.BoolField[settingNetflowModel, settings.Netflow]{
			Wire:  "auto_engine_id_enabled",
			Model: func(m *settingNetflowModel) *types.Bool { return &m.AutoEngineIDEnabled },
			SDK:   func(s *settings.Netflow) *bool { return &s.AutoEngineIDEnabled },
		},
		resourcekit.BoolField[settingNetflowModel, settings.Netflow]{
			Wire:  "enabled",
			Model: func(m *settingNetflowModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Netflow) *bool { return &s.Enabled },
		},
		resourcekit.Int64PtrField[settingNetflowModel, settings.Netflow]{
			Wire:     "engine_id",
			Model:    func(m *settingNetflowModel) *types.Int64 { return &m.EngineID },
			SDK:      func(s *settings.Netflow) **int64 { return &s.EngineID },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingNetflowModel, settings.Netflow]{
			Wire:  "export_frequency",
			Model: func(m *settingNetflowModel) *types.Int64 { return &m.ExportFrequency },
			SDK:   func(s *settings.Netflow) **int64 { return &s.ExportFrequency },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringListField[settingNetflowModel, settings.Netflow]{
			Wire:  "network_ids",
			Model: func(m *settingNetflowModel) *types.List { return &m.NetworkIDs },
			SDK:   func(s *settings.Netflow) *[]string { return &s.NetworkIDs },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[settingNetflowModel, settings.Netflow]{
			Wire:     "port",
			Model:    func(m *settingNetflowModel) *types.Int64 { return &m.Port },
			SDK:      func(s *settings.Netflow) **int64 { return &s.Port },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingNetflowModel, settings.Netflow]{
			Wire:  "refresh_rate",
			Model: func(m *settingNetflowModel) *types.Int64 { return &m.RefreshRate },
			SDK:   func(s *settings.Netflow) **int64 { return &s.RefreshRate },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingNetflowModel, settings.Netflow]{
			Wire:  "sampling_mode",
			Model: func(m *settingNetflowModel) *types.String { return &m.SamplingMode },
			SDK:   func(s *settings.Netflow) *string { return &s.SamplingMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[settingNetflowModel, settings.Netflow]{
			Wire:     "sampling_rate",
			Model:    func(m *settingNetflowModel) *types.Int64 { return &m.SamplingRate },
			SDK:      func(s *settings.Netflow) **int64 { return &s.SamplingRate },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.StringField[settingNetflowModel, settings.Netflow]{
			Wire:  "server",
			Model: func(m *settingNetflowModel) *types.String { return &m.Server },
			SDK:   func(s *settings.Netflow) *string { return &s.Server },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[settingNetflowModel, settings.Netflow]{
			Wire:     "version",
			Model:    func(m *settingNetflowModel) *types.Int64 { return &m.Version },
			SDK:      func(s *settings.Netflow) **int64 { return &s.Version },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
	}
}
