// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingCountryModel struct {
	Code types.Int64 `tfsdk:"code"`
}

var countryAttrTypes = map[string]attr.Type{
	"code": types.Int64Type,
}

// countryNestedSchema is the country SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func countryNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["country"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingCountryGenFields is every unifi_setting country attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingCountryGenFields() []resourcekit.Field[settingCountryModel, settings.Country] {
	return []resourcekit.Field[settingCountryModel, settings.Country]{
		resourcekit.Int64PtrField[settingCountryModel, settings.Country]{
			Wire:  "code",
			Model: func(m *settingCountryModel) *types.Int64 { return &m.Code },
			SDK:   func(s *settings.Country) **int64 { return &s.Code },
			Elide: resourcekit.KeepZero,
		},
	}
}
