// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingDpiModel struct {
	Enabled               types.Bool `tfsdk:"enabled"`
	FingerprintingEnabled types.Bool `tfsdk:"fingerprinting_enabled"`
}

var dpiAttrTypes = map[string]attr.Type{
	"enabled":                types.BoolType,
	"fingerprinting_enabled": types.BoolType,
}

// dpiNestedSchema is the dpi SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func dpiNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["dpi"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingDpiGenFields is every unifi_setting dpi attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingDpiGenFields() []resourcekit.Field[settingDpiModel, settings.Dpi] {
	return []resourcekit.Field[settingDpiModel, settings.Dpi]{
		resourcekit.BoolField[settingDpiModel, settings.Dpi]{
			Wire:  "enabled",
			Model: func(m *settingDpiModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Dpi) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[settingDpiModel, settings.Dpi]{
			Wire:  "fingerprintingEnabled",
			Model: func(m *settingDpiModel) *types.Bool { return &m.FingerprintingEnabled },
			SDK:   func(s *settings.Dpi) *bool { return &s.FingerprintingEnabled },
		},
	}
}
