// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingUsgModel struct {
	BroadcastPing                  types.Bool           `tfsdk:"broadcast_ping"`
	DNSVerification                types.Object         `tfsdk:"dns_verification"`
	FtpModule                      types.Bool           `tfsdk:"ftp_module"`
	GeoIPFilteringBlock            types.String         `tfsdk:"geo_ip_filtering_block"`
	GeoIPFilteringCountries        types.String         `tfsdk:"geo_ip_filtering_countries"`
	GeoIPFilteringEnabled          types.Bool           `tfsdk:"geo_ip_filtering_enabled"`
	GeoIPFilteringTrafficDirection types.String         `tfsdk:"geo_ip_filtering_traffic_direction"`
	GreModule                      types.Bool           `tfsdk:"gre_module"`
	H323Module                     types.Bool           `tfsdk:"h323_module"`
	ICMPTimeout                    timetypes.GoDuration `tfsdk:"icmp_timeout"`
	MssClamp                       types.String         `tfsdk:"mss_clamp"`
	OffloadAccounting              types.Bool           `tfsdk:"offload_accounting"`
	OffloadL2Blocking              types.Bool           `tfsdk:"offload_l2_blocking"`
	OffloadSch                     types.Bool           `tfsdk:"offload_sch"`
	OtherTimeout                   timetypes.GoDuration `tfsdk:"other_timeout"`
	PptpModule                     types.Bool           `tfsdk:"pptp_module"`
	ReceiveRedirects               types.Bool           `tfsdk:"receive_redirects"`
	SendRedirects                  types.Bool           `tfsdk:"send_redirects"`
	SipModule                      types.Bool           `tfsdk:"sip_module"`
	SynCookies                     types.Bool           `tfsdk:"syn_cookies"`
	TCPCloseTimeout                timetypes.GoDuration `tfsdk:"tcp_close_timeout"`
	TCPCloseWaitTimeout            timetypes.GoDuration `tfsdk:"tcp_close_wait_timeout"`
	TCPEstablishedTimeout          timetypes.GoDuration `tfsdk:"tcp_established_timeout"`
	TCPFinWaitTimeout              timetypes.GoDuration `tfsdk:"tcp_fin_wait_timeout"`
	TCPLastAckTimeout              timetypes.GoDuration `tfsdk:"tcp_last_ack_timeout"`
	TCPSynRecvTimeout              timetypes.GoDuration `tfsdk:"tcp_syn_recv_timeout"`
	TCPSynSentTimeout              timetypes.GoDuration `tfsdk:"tcp_syn_sent_timeout"`
	TCPTimeWaitTimeout             timetypes.GoDuration `tfsdk:"tcp_time_wait_timeout"`
	TFTPModule                     types.Bool           `tfsdk:"tftp_module"`
	TimeoutSettingPreference       types.String         `tfsdk:"timeout_setting_preference"`
	UDPOtherTimeout                timetypes.GoDuration `tfsdk:"udp_other_timeout"`
	UDPStreamTimeout               timetypes.GoDuration `tfsdk:"udp_stream_timeout"`
	UnbindWANMonitors              types.Bool           `tfsdk:"unbind_wan_monitors"`
	UPnPEnabled                    types.Bool           `tfsdk:"upnp_enabled"`
	UPnPNATPmpEnabled              types.Bool           `tfsdk:"upnp_nat_pmp_enabled"`
	UPnPSecureMode                 types.Bool           `tfsdk:"upnp_secure_mode"`
	UPnPWANInterface               types.String         `tfsdk:"upnp_wan_interface"`
}

type usgDnsVerificationModel struct {
	Domain             types.String `tfsdk:"domain"`
	PrimaryDNSServer   types.String `tfsdk:"primary_dns_server"`
	SecondaryDNSServer types.String `tfsdk:"secondary_dns_server"`
	SettingPreference  types.String `tfsdk:"setting_preference"`
}

var usgDnsVerificationAttrTypes = map[string]attr.Type{
	"domain":               types.StringType,
	"primary_dns_server":   types.StringType,
	"secondary_dns_server": types.StringType,
	"setting_preference":   types.StringType,
}

var usgAttrTypes = map[string]attr.Type{
	"broadcast_ping":                     types.BoolType,
	"dns_verification":                   types.ObjectType{AttrTypes: usgDnsVerificationAttrTypes},
	"ftp_module":                         types.BoolType,
	"geo_ip_filtering_block":             types.StringType,
	"geo_ip_filtering_countries":         types.StringType,
	"geo_ip_filtering_enabled":           types.BoolType,
	"geo_ip_filtering_traffic_direction": types.StringType,
	"gre_module":                         types.BoolType,
	"h323_module":                        types.BoolType,
	"icmp_timeout":                       timetypes.GoDurationType{},
	"mss_clamp":                          types.StringType,
	"offload_accounting":                 types.BoolType,
	"offload_l2_blocking":                types.BoolType,
	"offload_sch":                        types.BoolType,
	"other_timeout":                      timetypes.GoDurationType{},
	"pptp_module":                        types.BoolType,
	"receive_redirects":                  types.BoolType,
	"send_redirects":                     types.BoolType,
	"sip_module":                         types.BoolType,
	"syn_cookies":                        types.BoolType,
	"tcp_close_timeout":                  timetypes.GoDurationType{},
	"tcp_close_wait_timeout":             timetypes.GoDurationType{},
	"tcp_established_timeout":            timetypes.GoDurationType{},
	"tcp_fin_wait_timeout":               timetypes.GoDurationType{},
	"tcp_last_ack_timeout":               timetypes.GoDurationType{},
	"tcp_syn_recv_timeout":               timetypes.GoDurationType{},
	"tcp_syn_sent_timeout":               timetypes.GoDurationType{},
	"tcp_time_wait_timeout":              timetypes.GoDurationType{},
	"tftp_module":                        types.BoolType,
	"timeout_setting_preference":         types.StringType,
	"udp_other_timeout":                  timetypes.GoDurationType{},
	"udp_stream_timeout":                 timetypes.GoDurationType{},
	"unbind_wan_monitors":                types.BoolType,
	"upnp_enabled":                       types.BoolType,
	"upnp_nat_pmp_enabled":               types.BoolType,
	"upnp_secure_mode":                   types.BoolType,
	"upnp_wan_interface":                 types.StringType,
}

// usgNestedSchema is the usg SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func usgNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["usg"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingUsgGenFields is every unifi_setting usg attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingUsgGenFields() []resourcekit.Field[settingUsgModel, settings.Usg] {
	return []resourcekit.Field[settingUsgModel, settings.Usg]{
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "broadcast_ping",
			Model: func(m *settingUsgModel) *types.Bool { return &m.BroadcastPing },
			SDK:   func(s *settings.Usg) *bool { return &s.BroadcastPing },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "ftp_module",
			Model: func(m *settingUsgModel) *types.Bool { return &m.FtpModule },
			SDK:   func(s *settings.Usg) *bool { return &s.FtpModule },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "gre_module",
			Model: func(m *settingUsgModel) *types.Bool { return &m.GreModule },
			SDK:   func(s *settings.Usg) *bool { return &s.GreModule },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "h323_module",
			Model: func(m *settingUsgModel) *types.Bool { return &m.H323Module },
			SDK:   func(s *settings.Usg) *bool { return &s.H323Module },
		},
		resourcekit.StringField[settingUsgModel, settings.Usg]{
			Wire:  "mss_clamp",
			Model: func(m *settingUsgModel) *types.String { return &m.MssClamp },
			SDK:   func(s *settings.Usg) *string { return &s.MssClamp },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "offload_accounting",
			Model: func(m *settingUsgModel) *types.Bool { return &m.OffloadAccounting },
			SDK:   func(s *settings.Usg) *bool { return &s.OffloadAccounting },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "offload_l2_blocking",
			Model: func(m *settingUsgModel) *types.Bool { return &m.OffloadL2Blocking },
			SDK:   func(s *settings.Usg) *bool { return &s.OffloadL2Blocking },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "offload_sch",
			Model: func(m *settingUsgModel) *types.Bool { return &m.OffloadSch },
			SDK:   func(s *settings.Usg) *bool { return &s.OffloadSch },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "pptp_module",
			Model: func(m *settingUsgModel) *types.Bool { return &m.PptpModule },
			SDK:   func(s *settings.Usg) *bool { return &s.PptpModule },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "receive_redirects",
			Model: func(m *settingUsgModel) *types.Bool { return &m.ReceiveRedirects },
			SDK:   func(s *settings.Usg) *bool { return &s.ReceiveRedirects },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "send_redirects",
			Model: func(m *settingUsgModel) *types.Bool { return &m.SendRedirects },
			SDK:   func(s *settings.Usg) *bool { return &s.SendRedirects },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "sip_module",
			Model: func(m *settingUsgModel) *types.Bool { return &m.SipModule },
			SDK:   func(s *settings.Usg) *bool { return &s.SipModule },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "syn_cookies",
			Model: func(m *settingUsgModel) *types.Bool { return &m.SynCookies },
			SDK:   func(s *settings.Usg) *bool { return &s.SynCookies },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "tftp_module",
			Model: func(m *settingUsgModel) *types.Bool { return &m.TFTPModule },
			SDK:   func(s *settings.Usg) *bool { return &s.TFTPModule },
		},
		resourcekit.StringField[settingUsgModel, settings.Usg]{
			Wire:  "timeout_setting_preference",
			Model: func(m *settingUsgModel) *types.String { return &m.TimeoutSettingPreference },
			SDK:   func(s *settings.Usg) *string { return &s.TimeoutSettingPreference },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "unbind_wan_monitors",
			Model: func(m *settingUsgModel) *types.Bool { return &m.UnbindWANMonitors },
			SDK:   func(s *settings.Usg) *bool { return &s.UnbindWANMonitors },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "upnp_enabled",
			Model: func(m *settingUsgModel) *types.Bool { return &m.UPnPEnabled },
			SDK:   func(s *settings.Usg) *bool { return &s.UPnPEnabled },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "upnp_nat_pmp_enabled",
			Model: func(m *settingUsgModel) *types.Bool { return &m.UPnPNATPmpEnabled },
			SDK:   func(s *settings.Usg) *bool { return &s.UPnPNATPmpEnabled },
		},
		resourcekit.BoolField[settingUsgModel, settings.Usg]{
			Wire:  "upnp_secure_mode",
			Model: func(m *settingUsgModel) *types.Bool { return &m.UPnPSecureMode },
			SDK:   func(s *settings.Usg) *bool { return &s.UPnPSecureMode },
		},
		resourcekit.StringField[settingUsgModel, settings.Usg]{
			Wire:  "upnp_wan_interface",
			Model: func(m *settingUsgModel) *types.String { return &m.UPnPWANInterface },
			SDK:   func(s *settings.Usg) *string { return &s.UPnPWANInterface },
			Elide: resourcekit.NullZero,
		},
	}
}
