// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingGlobalNatModel struct {
	ExcludedNetworkIDs types.List   `tfsdk:"excluded_network_ids"`
	Mode               types.String `tfsdk:"mode"`
}

var globalNatAttrTypes = map[string]attr.Type{
	"excluded_network_ids": types.ListType{ElemType: types.StringType},
	"mode":                 types.StringType,
}

// globalNatNestedSchema is the global_nat SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func globalNatNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["global_nat"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingGlobalNatGenFields is every unifi_setting global_nat attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingGlobalNatGenFields() []resourcekit.Field[settingGlobalNatModel, settings.GlobalNat] {
	return []resourcekit.Field[settingGlobalNatModel, settings.GlobalNat]{
		resourcekit.StringListField[settingGlobalNatModel, settings.GlobalNat]{
			Wire:  "excluded_network_ids",
			Model: func(m *settingGlobalNatModel) *types.List { return &m.ExcludedNetworkIDs },
			SDK:   func(s *settings.GlobalNat) *[]string { return &s.ExcludedNetworkIDs },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGlobalNatModel, settings.GlobalNat]{
			Wire:  "mode",
			Model: func(m *settingGlobalNatModel) *types.String { return &m.Mode },
			SDK:   func(s *settings.GlobalNat) *string { return &s.Mode },
			Elide: resourcekit.NullZero,
		},
	}
}
