// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingNetworkOptimizationModel struct {
	Enabled types.Bool `tfsdk:"enabled"`
}

var networkOptimizationAttrTypes = map[string]attr.Type{
	"enabled": types.BoolType,
}

// networkOptimizationNestedSchema is the network_optimization SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func networkOptimizationNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["network_optimization"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingNetworkOptimizationGenFields is every unifi_setting network_optimization attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingNetworkOptimizationGenFields() []resourcekit.Field[settingNetworkOptimizationModel, settings.NetworkOptimization] {
	return []resourcekit.Field[settingNetworkOptimizationModel, settings.NetworkOptimization]{
		resourcekit.BoolField[settingNetworkOptimizationModel, settings.NetworkOptimization]{
			Wire:  "enabled",
			Model: func(m *settingNetworkOptimizationModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.NetworkOptimization) *bool { return &s.Enabled },
		},
	}
}
