// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingMgmtModel struct {
	AdvancedFeatureEnabled types.Bool   `tfsdk:"advanced_feature_enabled"`
	AutoUpgrade            types.Bool   `tfsdk:"auto_upgrade"`
	AutoUpgradeHour        types.Int64  `tfsdk:"auto_upgrade_hour"`
	DebugToolsEnabled      types.Bool   `tfsdk:"debug_tools_enabled"`
	DirectConnectEnabled   types.Bool   `tfsdk:"direct_connect_enabled"`
	SSHAuthPasswordEnabled types.Bool   `tfsdk:"ssh_auth_password_enabled"`
	SSHEnabled             types.Bool   `tfsdk:"ssh_enabled"`
	SSHKeys                types.List   `tfsdk:"ssh_keys"`
	SSHPassword            types.String `tfsdk:"ssh_password"`
	SSHUsername            types.String `tfsdk:"ssh_username"`
	UnifiIdpEnabled        types.Bool   `tfsdk:"unifi_idp_enabled"`
	WifimanEnabled         types.Bool   `tfsdk:"wifiman_enabled"`
}

type mgmtSshKeysModel struct {
	Comment types.String `tfsdk:"comment"`
	Key     types.String `tfsdk:"key"`
	Name    types.String `tfsdk:"name"`
	Type    types.String `tfsdk:"type"`
}

var mgmtSshKeysAttrTypes = map[string]attr.Type{
	"comment": types.StringType,
	"key":     types.StringType,
	"name":    types.StringType,
	"type":    types.StringType,
}

var mgmtAttrTypes = map[string]attr.Type{
	"advanced_feature_enabled":  types.BoolType,
	"auto_upgrade":              types.BoolType,
	"auto_upgrade_hour":         types.Int64Type,
	"debug_tools_enabled":       types.BoolType,
	"direct_connect_enabled":    types.BoolType,
	"ssh_auth_password_enabled": types.BoolType,
	"ssh_enabled":               types.BoolType,
	"ssh_keys":                  types.ListType{ElemType: types.ObjectType{AttrTypes: mgmtSshKeysAttrTypes}},
	"ssh_password":              types.StringType,
	"ssh_username":              types.StringType,
	"unifi_idp_enabled":         types.BoolType,
	"wifiman_enabled":           types.BoolType,
}

// mgmtNestedSchema is the mgmt SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func mgmtNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["mgmt"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingMgmtGenFields is every unifi_setting mgmt attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingMgmtGenFields() []resourcekit.Field[settingMgmtModel, settings.Mgmt] {
	return []resourcekit.Field[settingMgmtModel, settings.Mgmt]{
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "advanced_feature_enabled",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.AdvancedFeatureEnabled },
			SDK:   func(s *settings.Mgmt) *bool { return &s.AdvancedFeatureEnabled },
		},
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "auto_upgrade",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.AutoUpgrade },
			SDK:   func(s *settings.Mgmt) *bool { return &s.AutoUpgrade },
		},
		resourcekit.Int64PtrField[settingMgmtModel, settings.Mgmt]{
			Wire:  "auto_upgrade_hour",
			Model: func(m *settingMgmtModel) *types.Int64 { return &m.AutoUpgradeHour },
			SDK:   func(s *settings.Mgmt) **int64 { return &s.AutoUpgradeHour },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "debug_tools_enabled",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.DebugToolsEnabled },
			SDK:   func(s *settings.Mgmt) *bool { return &s.DebugToolsEnabled },
		},
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "direct_connect_enabled",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.DirectConnectEnabled },
			SDK:   func(s *settings.Mgmt) *bool { return &s.DirectConnectEnabled },
		},
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "x_ssh_auth_password_enabled",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.SSHAuthPasswordEnabled },
			SDK:   func(s *settings.Mgmt) *bool { return &s.SSHAuthPasswordEnabled },
		},
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "x_ssh_enabled",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.SSHEnabled },
			SDK:   func(s *settings.Mgmt) *bool { return &s.SSHEnabled },
		},
		resourcekit.StringField[settingMgmtModel, settings.Mgmt]{
			Wire:  "x_ssh_password",
			Model: func(m *settingMgmtModel) *types.String { return &m.SSHPassword },
			SDK:   func(s *settings.Mgmt) *string { return &s.SSHPassword },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[settingMgmtModel, settings.Mgmt]{
			Wire:  "x_ssh_username",
			Model: func(m *settingMgmtModel) *types.String { return &m.SSHUsername },
			SDK:   func(s *settings.Mgmt) *string { return &s.SSHUsername },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "unifi_idp_enabled",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.UnifiIdpEnabled },
			SDK:   func(s *settings.Mgmt) *bool { return &s.UniFiIdentityProviderEnabled },
		},
		resourcekit.BoolField[settingMgmtModel, settings.Mgmt]{
			Wire:  "wifiman_enabled",
			Model: func(m *settingMgmtModel) *types.Bool { return &m.WifimanEnabled },
			SDK:   func(s *settings.Mgmt) *bool { return &s.WifimanEnabled },
		},
	}
}
