// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingLcmModel struct {
	Brightness  types.Int64 `tfsdk:"brightness"`
	Enabled     types.Bool  `tfsdk:"enabled"`
	IdleTimeout types.Int64 `tfsdk:"idle_timeout"`
	Sync        types.Bool  `tfsdk:"sync"`
	TouchEvent  types.Bool  `tfsdk:"touch_event"`
}

var lcmAttrTypes = map[string]attr.Type{
	"brightness":   types.Int64Type,
	"enabled":      types.BoolType,
	"idle_timeout": types.Int64Type,
	"sync":         types.BoolType,
	"touch_event":  types.BoolType,
}

// lcmNestedSchema is the lcm SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func lcmNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["lcm"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingLcmGenFields is every unifi_setting lcm attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingLcmGenFields() []resourcekit.Field[settingLcmModel, settings.Lcm] {
	return []resourcekit.Field[settingLcmModel, settings.Lcm]{
		resourcekit.Int64PtrField[settingLcmModel, settings.Lcm]{
			Wire:     "brightness",
			Model:    func(m *settingLcmModel) *types.Int64 { return &m.Brightness },
			SDK:      func(s *settings.Lcm) **int64 { return &s.Brightness },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.BoolField[settingLcmModel, settings.Lcm]{
			Wire:  "enabled",
			Model: func(m *settingLcmModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Lcm) *bool { return &s.Enabled },
		},
		resourcekit.Int64PtrField[settingLcmModel, settings.Lcm]{
			Wire:     "idle_timeout",
			Model:    func(m *settingLcmModel) *types.Int64 { return &m.IdleTimeout },
			SDK:      func(s *settings.Lcm) **int64 { return &s.IDleTimeout },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.BoolField[settingLcmModel, settings.Lcm]{
			Wire:  "sync",
			Model: func(m *settingLcmModel) *types.Bool { return &m.Sync },
			SDK:   func(s *settings.Lcm) *bool { return &s.Sync },
		},
		resourcekit.BoolField[settingLcmModel, settings.Lcm]{
			Wire:  "touch_event",
			Model: func(m *settingLcmModel) *types.Bool { return &m.TouchEvent },
			SDK:   func(s *settings.Lcm) *bool { return &s.TouchEvent },
		},
	}
}

// lcmKitSpec is the lcm section's Spec: the generated field
// list over settings.Lcm, with no hook and no conditional write.
func lcmKitSpec() resourcekit.Spec[settingLcmModel, settings.Lcm] {
	return resourcekit.Spec[settingLcmModel, settings.Lcm]{
		TypeName: "setting_lcm",
		Subject:  "LCM Setting",
		New:      func() *settings.Lcm { return &settings.Lcm{} },
		Fields:   settingLcmGenFields(),
	}
}

// lcmKitBackend binds lcmKitSpec to a client: Read is
// GetSetting[*settings.Lcm], UpdateFields is the masked UpdateSettingFields --
// naming only the fields the plan set.
func lcmKitBackend(client *ui.ApiClient) resourcekit.Backend[settings.Lcm] {
	return resourcekit.Backend[settings.Lcm]{
		Read: func(ctx context.Context, site, _ string) (*settings.Lcm, error) {
			_, doc, err := ui.GetSetting[*settings.Lcm](client, ctx, site)
			if err != nil {
				return nil, err
			}
			return doc, nil
		},
		UpdateFields: func(
			ctx context.Context, site string, in *settings.Lcm, fields ...string,
		) (*settings.Lcm, error) {
			if err := client.UpdateSettingFields(ctx, site, in, fields...); err != nil {
				return nil, err
			}
			return in, nil
		},
	}
}

// lcmKitSection builds the lcm entry for settingResource's
// Sections, bound to client via settingKitSections.
func lcmKitSection(client *ui.ApiClient) resourcekit.Section[settingResourceModel] {
	spec := lcmKitSpec()
	spec.Backend = lcmKitBackend(client)
	return resourcekit.SpecSection[settingResourceModel, settingLcmModel, settings.Lcm]{
		SectionName: "lcm",
		Get:         func(m *settingResourceModel) *types.Object { return &m.Lcm },
		Set:         func(m *settingResourceModel, o types.Object) { m.Lcm = o },
		AttrTypes:   lcmAttrTypes,
		Spec:        spec,
	}
}
