// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingDeviceSupervisionModel struct {
	GlobalSupervisionEnabled types.Bool  `tfsdk:"global_supervision_enabled"`
	HeartbeatIntervalSeconds types.Int64 `tfsdk:"heartbeat_interval_seconds"`
	PowerOffDurationSeconds  types.Int64 `tfsdk:"power_off_duration_seconds"`
	SilenceThresholdSeconds  types.Int64 `tfsdk:"silence_threshold_seconds"`
}

var deviceSupervisionAttrTypes = map[string]attr.Type{
	"global_supervision_enabled": types.BoolType,
	"heartbeat_interval_seconds": types.Int64Type,
	"power_off_duration_seconds": types.Int64Type,
	"silence_threshold_seconds":  types.Int64Type,
}

// deviceSupervisionNestedSchema is the device_supervision SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func deviceSupervisionNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["device_supervision"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingDeviceSupervisionGenFields is every unifi_setting device_supervision attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingDeviceSupervisionGenFields() []resourcekit.Field[settingDeviceSupervisionModel, settings.DeviceSupervision] {
	return []resourcekit.Field[settingDeviceSupervisionModel, settings.DeviceSupervision]{
		resourcekit.BoolField[settingDeviceSupervisionModel, settings.DeviceSupervision]{
			Wire:  "global_supervision_enabled",
			Model: func(m *settingDeviceSupervisionModel) *types.Bool { return &m.GlobalSupervisionEnabled },
			SDK:   func(s *settings.DeviceSupervision) *bool { return &s.GlobalSupervisionEnabled },
		},
		resourcekit.Int64PtrField[settingDeviceSupervisionModel, settings.DeviceSupervision]{
			Wire:     "heartbeat_interval_seconds",
			Model:    func(m *settingDeviceSupervisionModel) *types.Int64 { return &m.HeartbeatIntervalSeconds },
			SDK:      func(s *settings.DeviceSupervision) **int64 { return &s.HeartbeatIntervalSeconds },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingDeviceSupervisionModel, settings.DeviceSupervision]{
			Wire:     "power_off_duration_seconds",
			Model:    func(m *settingDeviceSupervisionModel) *types.Int64 { return &m.PowerOffDurationSeconds },
			SDK:      func(s *settings.DeviceSupervision) **int64 { return &s.PowerOffDurationSeconds },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingDeviceSupervisionModel, settings.DeviceSupervision]{
			Wire:     "silence_threshold_seconds",
			Model:    func(m *settingDeviceSupervisionModel) *types.Int64 { return &m.SilenceThresholdSeconds },
			SDK:      func(s *settings.DeviceSupervision) **int64 { return &s.SilenceThresholdSeconds },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
	}
}
