// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingEtherLightingModel struct {
	NetworkOverrides types.List `tfsdk:"network_overrides"`
	SpeedOverrides   types.List `tfsdk:"speed_overrides"`
}

type etherLightingNetworkOverridesModel struct {
	Key         types.String `tfsdk:"key"`
	RawColorHex types.String `tfsdk:"raw_color_hex"`
}

var etherLightingNetworkOverridesAttrTypes = map[string]attr.Type{
	"key":           types.StringType,
	"raw_color_hex": types.StringType,
}

type etherLightingSpeedOverridesModel struct {
	Key         types.String `tfsdk:"key"`
	RawColorHex types.String `tfsdk:"raw_color_hex"`
}

var etherLightingSpeedOverridesAttrTypes = map[string]attr.Type{
	"key":           types.StringType,
	"raw_color_hex": types.StringType,
}

var etherLightingAttrTypes = map[string]attr.Type{
	"network_overrides": types.ListType{ElemType: types.ObjectType{AttrTypes: etherLightingNetworkOverridesAttrTypes}},
	"speed_overrides":   types.ListType{ElemType: types.ObjectType{AttrTypes: etherLightingSpeedOverridesAttrTypes}},
}

// etherLightingNestedSchema is the ether_lighting SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func etherLightingNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["ether_lighting"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingEtherLightingGenFields is every unifi_setting ether_lighting attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingEtherLightingGenFields() []resourcekit.Field[settingEtherLightingModel, settings.EtherLighting] {
	return []resourcekit.Field[settingEtherLightingModel, settings.EtherLighting]{}
}
