// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingNtpModel struct {
	NTPServer1        types.String `tfsdk:"ntp_server_1"`
	NTPServer2        types.String `tfsdk:"ntp_server_2"`
	NTPServer3        types.String `tfsdk:"ntp_server_3"`
	NTPServer4        types.String `tfsdk:"ntp_server_4"`
	SettingPreference types.String `tfsdk:"setting_preference"`
}

var ntpAttrTypes = map[string]attr.Type{
	"ntp_server_1":       types.StringType,
	"ntp_server_2":       types.StringType,
	"ntp_server_3":       types.StringType,
	"ntp_server_4":       types.StringType,
	"setting_preference": types.StringType,
}

// ntpNestedSchema is the ntp SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func ntpNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["ntp"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingNtpGenFields is every unifi_setting ntp attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingNtpGenFields() []resourcekit.Field[settingNtpModel, settings.Ntp] {
	return []resourcekit.Field[settingNtpModel, settings.Ntp]{
		resourcekit.StringField[settingNtpModel, settings.Ntp]{
			Wire:  "ntp_server_1",
			Model: func(m *settingNtpModel) *types.String { return &m.NTPServer1 },
			SDK:   func(s *settings.Ntp) *string { return &s.NtpServer1 },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingNtpModel, settings.Ntp]{
			Wire:  "ntp_server_2",
			Model: func(m *settingNtpModel) *types.String { return &m.NTPServer2 },
			SDK:   func(s *settings.Ntp) *string { return &s.NtpServer2 },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingNtpModel, settings.Ntp]{
			Wire:  "ntp_server_3",
			Model: func(m *settingNtpModel) *types.String { return &m.NTPServer3 },
			SDK:   func(s *settings.Ntp) *string { return &s.NtpServer3 },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingNtpModel, settings.Ntp]{
			Wire:  "ntp_server_4",
			Model: func(m *settingNtpModel) *types.String { return &m.NTPServer4 },
			SDK:   func(s *settings.Ntp) *string { return &s.NtpServer4 },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingNtpModel, settings.Ntp]{
			Wire:  "setting_preference",
			Model: func(m *settingNtpModel) *types.String { return &m.SettingPreference },
			SDK:   func(s *settings.Ntp) *string { return &s.SettingPreference },
			Elide: resourcekit.NullZero,
		},
	}
}
