// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingTeleportModel struct {
	Enabled    types.Bool   `tfsdk:"enabled"`
	SubnetCidr types.String `tfsdk:"subnet_cidr"`
}

var teleportAttrTypes = map[string]attr.Type{
	"enabled":     types.BoolType,
	"subnet_cidr": types.StringType,
}

// teleportNestedSchema is the teleport SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func teleportNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["teleport"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingTeleportGenFields is every unifi_setting teleport attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingTeleportGenFields() []resourcekit.Field[settingTeleportModel, settings.Teleport] {
	return []resourcekit.Field[settingTeleportModel, settings.Teleport]{
		resourcekit.BoolField[settingTeleportModel, settings.Teleport]{
			Wire:  "enabled",
			Model: func(m *settingTeleportModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Teleport) *bool { return &s.Enabled },
		},
		resourcekit.StringField[settingTeleportModel, settings.Teleport]{
			Wire:  "subnet_cidr",
			Model: func(m *settingTeleportModel) *types.String { return &m.SubnetCidr },
			SDK:   func(s *settings.Teleport) *string { return &s.SubnetCidr },
			Elide: resourcekit.KeepZero,
		},
	}
}

// teleportKitSpec is the teleport section's Spec: the generated field
// list over settings.Teleport, with no hook and no conditional write.
func teleportKitSpec() resourcekit.Spec[settingTeleportModel, settings.Teleport] {
	return resourcekit.Spec[settingTeleportModel, settings.Teleport]{
		TypeName: "setting_teleport",
		Subject:  "Teleport Setting",
		New:      func() *settings.Teleport { return &settings.Teleport{} },
		Fields:   settingTeleportGenFields(),
	}
}

// teleportKitBackend binds teleportKitSpec to a client: Read is
// GetSetting[*settings.Teleport], UpdateFields is the masked UpdateSettingFields --
// naming only the fields the plan set.
func teleportKitBackend(client *ui.ApiClient) resourcekit.Backend[settings.Teleport] {
	return resourcekit.Backend[settings.Teleport]{
		Read: func(ctx context.Context, site, _ string) (*settings.Teleport, error) {
			_, doc, err := ui.GetSetting[*settings.Teleport](client, ctx, site)
			if err != nil {
				return nil, err
			}
			return doc, nil
		},
		UpdateFields: func(
			ctx context.Context, site string, in *settings.Teleport, fields ...string,
		) (*settings.Teleport, error) {
			if err := client.UpdateSettingFields(ctx, site, in, fields...); err != nil {
				return nil, err
			}
			return in, nil
		},
	}
}

// teleportKitSection builds the teleport entry for settingResource's
// Sections, bound to client via settingKitSections.
func teleportKitSection(client *ui.ApiClient) resourcekit.Section[settingResourceModel] {
	spec := teleportKitSpec()
	spec.Backend = teleportKitBackend(client)
	return resourcekit.SpecSection[settingResourceModel, settingTeleportModel, settings.Teleport]{
		SectionName: "teleport",
		Get:         func(m *settingResourceModel) *types.Object { return &m.Teleport },
		Set:         func(m *settingResourceModel, o types.Object) { m.Teleport = o },
		AttrTypes:   teleportAttrTypes,
		Spec:        spec,
	}
}
