// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingSslInspectionModel struct {
	State types.String `tfsdk:"state"`
}

var sslInspectionAttrTypes = map[string]attr.Type{
	"state": types.StringType,
}

// sslInspectionNestedSchema is the ssl_inspection SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func sslInspectionNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["ssl_inspection"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingSslInspectionGenFields is every unifi_setting ssl_inspection attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingSslInspectionGenFields() []resourcekit.Field[settingSslInspectionModel, settings.SslInspection] {
	return []resourcekit.Field[settingSslInspectionModel, settings.SslInspection]{
		resourcekit.StringField[settingSslInspectionModel, settings.SslInspection]{
			Wire:  "state",
			Model: func(m *settingSslInspectionModel) *types.String { return &m.State },
			SDK:   func(s *settings.SslInspection) *string { return &s.State },
			Elide: resourcekit.NullZero,
		},
	}
}

// sslInspectionKitSpec is the ssl_inspection section's Spec: the generated field
// list over settings.SslInspection, with no hook and no conditional write.
func sslInspectionKitSpec() resourcekit.Spec[settingSslInspectionModel, settings.SslInspection] {
	return resourcekit.Spec[settingSslInspectionModel, settings.SslInspection]{
		TypeName: "setting_ssl_inspection",
		Subject:  "SSL Inspection Setting",
		New:      func() *settings.SslInspection { return &settings.SslInspection{} },
		Fields:   settingSslInspectionGenFields(),
	}
}

// sslInspectionKitBackend binds sslInspectionKitSpec to a client: Read is
// GetSetting[*settings.SslInspection], UpdateFields is the masked UpdateSettingFields --
// naming only the fields the plan set.
func sslInspectionKitBackend(client *ui.ApiClient) resourcekit.Backend[settings.SslInspection] {
	return resourcekit.Backend[settings.SslInspection]{
		Read: func(ctx context.Context, site, _ string) (*settings.SslInspection, error) {
			_, doc, err := ui.GetSetting[*settings.SslInspection](client, ctx, site)
			if err != nil {
				return nil, err
			}
			return doc, nil
		},
		UpdateFields: func(
			ctx context.Context, site string, in *settings.SslInspection, fields ...string,
		) (*settings.SslInspection, error) {
			if err := client.UpdateSettingFields(ctx, site, in, fields...); err != nil {
				return nil, err
			}
			return in, nil
		},
	}
}

// sslInspectionKitSection builds the ssl_inspection entry for settingResource's
// Sections, bound to client via settingKitSections.
func sslInspectionKitSection(client *ui.ApiClient) resourcekit.Section[settingResourceModel] {
	spec := sslInspectionKitSpec()
	spec.Backend = sslInspectionKitBackend(client)
	return resourcekit.SpecSection[settingResourceModel, settingSslInspectionModel, settings.SslInspection]{
		SectionName: "ssl_inspection",
		Get:         func(m *settingResourceModel) *types.Object { return &m.SslInspection },
		Set:         func(m *settingResourceModel, o types.Object) { m.SslInspection = o },
		AttrTypes:   sslInspectionAttrTypes,
		Spec:        spec,
	}
}
