// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingTeleportModel struct {
	Enabled    types.Bool   `tfsdk:"enabled"`
	SubnetCidr types.String `tfsdk:"subnet_cidr"`
}

var teleportAttrTypes = map[string]attr.Type{
	"enabled":     types.BoolType,
	"subnet_cidr": types.StringType,
}

// teleportNestedSchema is the teleport SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func teleportNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["teleport"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingTeleportGenFields is every unifi_setting teleport attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingTeleportGenFields() []resourcekit.Field[settingTeleportModel, settings.Teleport] {
	return []resourcekit.Field[settingTeleportModel, settings.Teleport]{
		resourcekit.BoolField[settingTeleportModel, settings.Teleport]{
			Wire:  "enabled",
			Model: func(m *settingTeleportModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Teleport) *bool { return &s.Enabled },
		},
		resourcekit.StringField[settingTeleportModel, settings.Teleport]{
			Wire:  "subnet_cidr",
			Model: func(m *settingTeleportModel) *types.String { return &m.SubnetCidr },
			SDK:   func(s *settings.Teleport) *string { return &s.SubnetCidr },
			Elide: resourcekit.KeepZero,
		},
	}
}
