// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingGlobalApModel struct {
	APExclusions  types.List   `tfsdk:"ap_exclusions"`
	NaChannelSize types.Int64  `tfsdk:"na_channel_size"`
	NaTxPower     types.Int64  `tfsdk:"na_tx_power"`
	NaTxPowerMode types.String `tfsdk:"na_tx_power_mode"`
	NgChannelSize types.Int64  `tfsdk:"ng_channel_size"`
	NgTxPower     types.Int64  `tfsdk:"ng_tx_power"`
	NgTxPowerMode types.String `tfsdk:"ng_tx_power_mode"`
}

var globalApAttrTypes = map[string]attr.Type{
	"ap_exclusions":    types.ListType{ElemType: types.StringType},
	"na_channel_size":  types.Int64Type,
	"na_tx_power":      types.Int64Type,
	"na_tx_power_mode": types.StringType,
	"ng_channel_size":  types.Int64Type,
	"ng_tx_power":      types.Int64Type,
	"ng_tx_power_mode": types.StringType,
}

// globalApNestedSchema is the global_ap SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func globalApNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["global_ap"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingGlobalApGenFields is every unifi_setting global_ap attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingGlobalApGenFields() []resourcekit.Field[settingGlobalApModel, settings.GlobalAp] {
	return []resourcekit.Field[settingGlobalApModel, settings.GlobalAp]{
		resourcekit.StringListField[settingGlobalApModel, settings.GlobalAp]{
			Wire:  "ap_exclusions",
			Model: func(m *settingGlobalApModel) *types.List { return &m.APExclusions },
			SDK:   func(s *settings.GlobalAp) *[]string { return &s.ApExclusions },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[settingGlobalApModel, settings.GlobalAp]{
			Wire:     "na_channel_size",
			Model:    func(m *settingGlobalApModel) *types.Int64 { return &m.NaChannelSize },
			SDK:      func(s *settings.GlobalAp) **int64 { return &s.NaChannelSize },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingGlobalApModel, settings.GlobalAp]{
			Wire:  "na_tx_power",
			Model: func(m *settingGlobalApModel) *types.Int64 { return &m.NaTxPower },
			SDK:   func(s *settings.GlobalAp) **int64 { return &s.NaTxPower },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGlobalApModel, settings.GlobalAp]{
			Wire:  "na_tx_power_mode",
			Model: func(m *settingGlobalApModel) *types.String { return &m.NaTxPowerMode },
			SDK:   func(s *settings.GlobalAp) *string { return &s.NaTxPowerMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[settingGlobalApModel, settings.GlobalAp]{
			Wire:     "ng_channel_size",
			Model:    func(m *settingGlobalApModel) *types.Int64 { return &m.NgChannelSize },
			SDK:      func(s *settings.GlobalAp) **int64 { return &s.NgChannelSize },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingGlobalApModel, settings.GlobalAp]{
			Wire:  "ng_tx_power",
			Model: func(m *settingGlobalApModel) *types.Int64 { return &m.NgTxPower },
			SDK:   func(s *settings.GlobalAp) **int64 { return &s.NgTxPower },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGlobalApModel, settings.GlobalAp]{
			Wire:  "ng_tx_power_mode",
			Model: func(m *settingGlobalApModel) *types.String { return &m.NgTxPowerMode },
			SDK:   func(s *settings.GlobalAp) *string { return &s.NgTxPowerMode },
			Elide: resourcekit.NullZero,
		},
	}
}

// globalApKitSpec is the global_ap section's Spec: the generated field
// list over settings.GlobalAp, with no hook and no conditional write.
func globalApKitSpec() resourcekit.Spec[settingGlobalApModel, settings.GlobalAp] {
	return resourcekit.Spec[settingGlobalApModel, settings.GlobalAp]{
		TypeName: "setting_global_ap",
		Subject:  "Global AP Setting",
		New:      func() *settings.GlobalAp { return &settings.GlobalAp{} },
		Fields:   settingGlobalApGenFields(),
	}
}

// globalApKitBackend binds globalApKitSpec to a client: Read is
// GetSetting[*settings.GlobalAp], UpdateFields is the masked UpdateSettingFields --
// naming only the fields the plan set.
func globalApKitBackend(client *ui.ApiClient) resourcekit.Backend[settings.GlobalAp] {
	return resourcekit.Backend[settings.GlobalAp]{
		Read: func(ctx context.Context, site, _ string) (*settings.GlobalAp, error) {
			_, doc, err := ui.GetSetting[*settings.GlobalAp](client, ctx, site)
			if err != nil {
				return nil, err
			}
			return doc, nil
		},
		UpdateFields: func(
			ctx context.Context, site string, in *settings.GlobalAp, fields ...string,
		) (*settings.GlobalAp, error) {
			if err := client.UpdateSettingFields(ctx, site, in, fields...); err != nil {
				return nil, err
			}
			return in, nil
		},
	}
}

// globalApKitSection builds the global_ap entry for settingResource's
// Sections, bound to client via settingKitSections.
func globalApKitSection(client *ui.ApiClient) resourcekit.Section[settingResourceModel] {
	spec := globalApKitSpec()
	spec.Backend = globalApKitBackend(client)
	return resourcekit.SpecSection[settingResourceModel, settingGlobalApModel, settings.GlobalAp]{
		SectionName: "global_ap",
		Get:         func(m *settingResourceModel) *types.Object { return &m.GlobalAp },
		Set:         func(m *settingResourceModel, o types.Object) { m.GlobalAp = o },
		AttrTypes:   globalApAttrTypes,
		Spec:        spec,
	}
}
