// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingRadiusModel struct {
	AccountingEnabled     types.Bool           `tfsdk:"accounting_enabled"`
	AcctPort              types.Int64          `tfsdk:"acct_port"`
	AuthPort              types.Int64          `tfsdk:"auth_port"`
	Enabled               types.Bool           `tfsdk:"enabled"`
	InterimUpdateInterval timetypes.GoDuration `tfsdk:"interim_update_interval"`
	Secret                types.String         `tfsdk:"secret"`
}

var radiusAttrTypes = map[string]attr.Type{
	"accounting_enabled":      types.BoolType,
	"acct_port":               types.Int64Type,
	"auth_port":               types.Int64Type,
	"enabled":                 types.BoolType,
	"interim_update_interval": timetypes.GoDurationType{},
	"secret":                  types.StringType,
}

// radiusNestedSchema is the radius SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func radiusNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["radius"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingRadiusGenFields is every unifi_setting radius attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingRadiusGenFields() []resourcekit.Field[settingRadiusModel, settings.Radius] {
	return []resourcekit.Field[settingRadiusModel, settings.Radius]{
		resourcekit.BoolField[settingRadiusModel, settings.Radius]{
			Wire:  "accounting_enabled",
			Model: func(m *settingRadiusModel) *types.Bool { return &m.AccountingEnabled },
			SDK:   func(s *settings.Radius) *bool { return &s.AccountingEnabled },
		},
		resourcekit.Int64PtrField[settingRadiusModel, settings.Radius]{
			Wire:     "acct_port",
			Model:    func(m *settingRadiusModel) *types.Int64 { return &m.AcctPort },
			SDK:      func(s *settings.Radius) **int64 { return &s.AcctPort },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[settingRadiusModel, settings.Radius]{
			Wire:     "auth_port",
			Model:    func(m *settingRadiusModel) *types.Int64 { return &m.AuthPort },
			SDK:      func(s *settings.Radius) **int64 { return &s.AuthPort },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.BoolField[settingRadiusModel, settings.Radius]{
			Wire:  "enabled",
			Model: func(m *settingRadiusModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Radius) *bool { return &s.Enabled },
		},
		resourcekit.StringField[settingRadiusModel, settings.Radius]{
			Wire:  "x_secret",
			Model: func(m *settingRadiusModel) *types.String { return &m.Secret },
			SDK:   func(s *settings.Radius) *string { return &s.Secret },
			Elide: resourcekit.NullZero,
		},
	}
}
