// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingTrafficFlowModel struct {
	EnabledAllowedTraffic        types.Bool `tfsdk:"enabled_allowed_traffic"`
	GatewayDNSEnabled            types.Bool `tfsdk:"gateway_dns_enabled"`
	UnifiDeviceManagementEnabled types.Bool `tfsdk:"unifi_device_management_enabled"`
	UnifiServicesEnabled         types.Bool `tfsdk:"unifi_services_enabled"`
}

var trafficFlowAttrTypes = map[string]attr.Type{
	"enabled_allowed_traffic":         types.BoolType,
	"gateway_dns_enabled":             types.BoolType,
	"unifi_device_management_enabled": types.BoolType,
	"unifi_services_enabled":          types.BoolType,
}

// trafficFlowNestedSchema is the traffic_flow SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func trafficFlowNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["traffic_flow"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingTrafficFlowGenFields is every unifi_setting traffic_flow attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingTrafficFlowGenFields() []resourcekit.Field[settingTrafficFlowModel, settings.TrafficFlow] {
	return []resourcekit.Field[settingTrafficFlowModel, settings.TrafficFlow]{
		resourcekit.BoolField[settingTrafficFlowModel, settings.TrafficFlow]{
			Wire:  "enabled_allowed_traffic",
			Model: func(m *settingTrafficFlowModel) *types.Bool { return &m.EnabledAllowedTraffic },
			SDK:   func(s *settings.TrafficFlow) *bool { return &s.EnabledAllowedTraffic },
		},
		resourcekit.BoolField[settingTrafficFlowModel, settings.TrafficFlow]{
			Wire:  "gateway_dns_enabled",
			Model: func(m *settingTrafficFlowModel) *types.Bool { return &m.GatewayDNSEnabled },
			SDK:   func(s *settings.TrafficFlow) *bool { return &s.GatewayDNSEnabled },
		},
		resourcekit.BoolField[settingTrafficFlowModel, settings.TrafficFlow]{
			Wire:  "unifi_device_management_enabled",
			Model: func(m *settingTrafficFlowModel) *types.Bool { return &m.UnifiDeviceManagementEnabled },
			SDK:   func(s *settings.TrafficFlow) *bool { return &s.UnifiDeviceManagementEnabled },
		},
		resourcekit.BoolField[settingTrafficFlowModel, settings.TrafficFlow]{
			Wire:  "unifi_services_enabled",
			Model: func(m *settingTrafficFlowModel) *types.Bool { return &m.UnifiServicesEnabled },
			SDK:   func(s *settings.TrafficFlow) *bool { return &s.UnifiServicesEnabled },
		},
	}
}
