// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingGlobalSwitchModel struct {
	AclL3Isolation                 types.List   `tfsdk:"acl_l3_isolation"`
	AutoSTPEdgeDetectionEnabled    types.Bool   `tfsdk:"auto_stp_edge_detection_enabled"`
	DHCPSnoop                      types.Bool   `tfsdk:"dhcp_snoop"`
	Dot1xFallbackNetworkconfID     types.String `tfsdk:"dot1x_fallback_networkconf_id"`
	Dot1xPortctrlEnabled           types.Bool   `tfsdk:"dot1x_portctrl_enabled"`
	FloodKnownProtocols            types.Bool   `tfsdk:"flood_known_protocols"`
	FlowctrlEnabled                types.Bool   `tfsdk:"flowctrl_enabled"`
	ForwardUnknownMcastRouterPorts types.Bool   `tfsdk:"forward_unknown_mcast_router_ports"`
	JumboframeEnabled              types.Bool   `tfsdk:"jumboframe_enabled"`
	LinkDebounce                   types.Int64  `tfsdk:"link_debounce"`
	PoeStagingDelayMsec            types.Int64  `tfsdk:"poe_staging_delay_msec"`
	RadiusprofileID                types.String `tfsdk:"radiusprofile_id"`
	STPVersion                     types.String `tfsdk:"stp_version"`
	SwitchExclusions               types.List   `tfsdk:"switch_exclusions"`
}

type globalSwitchAclL3IsolationModel struct {
	DestinationNetworks types.List   `tfsdk:"destination_networks"`
	SourceNetwork       types.String `tfsdk:"source_network"`
}

var globalSwitchAclL3IsolationAttrTypes = map[string]attr.Type{
	"destination_networks": types.ListType{ElemType: types.StringType},
	"source_network":       types.StringType,
}

var globalSwitchAttrTypes = map[string]attr.Type{
	"acl_l3_isolation":                   types.ListType{ElemType: types.ObjectType{AttrTypes: globalSwitchAclL3IsolationAttrTypes}},
	"auto_stp_edge_detection_enabled":    types.BoolType,
	"dhcp_snoop":                         types.BoolType,
	"dot1x_fallback_networkconf_id":      types.StringType,
	"dot1x_portctrl_enabled":             types.BoolType,
	"flood_known_protocols":              types.BoolType,
	"flowctrl_enabled":                   types.BoolType,
	"forward_unknown_mcast_router_ports": types.BoolType,
	"jumboframe_enabled":                 types.BoolType,
	"link_debounce":                      types.Int64Type,
	"poe_staging_delay_msec":             types.Int64Type,
	"radiusprofile_id":                   types.StringType,
	"stp_version":                        types.StringType,
	"switch_exclusions":                  types.ListType{ElemType: types.StringType},
}

// globalSwitchNestedSchema is the global_switch SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func globalSwitchNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["global_switch"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingGlobalSwitchGenFields is every unifi_setting global_switch attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingGlobalSwitchGenFields() []resourcekit.Field[settingGlobalSwitchModel, settings.GlobalSwitch] {
	return []resourcekit.Field[settingGlobalSwitchModel, settings.GlobalSwitch]{
		resourcekit.BoolField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "auto_stp_edge_detection_enabled",
			Model: func(m *settingGlobalSwitchModel) *types.Bool { return &m.AutoSTPEdgeDetectionEnabled },
			SDK:   func(s *settings.GlobalSwitch) *bool { return &s.AutoStpEdgeDetectionEnabled },
		},
		resourcekit.BoolField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "dhcp_snoop",
			Model: func(m *settingGlobalSwitchModel) *types.Bool { return &m.DHCPSnoop },
			SDK:   func(s *settings.GlobalSwitch) *bool { return &s.DHCPSnoop },
		},
		resourcekit.StringField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "dot1x_fallback_networkconf_id",
			Model: func(m *settingGlobalSwitchModel) *types.String { return &m.Dot1xFallbackNetworkconfID },
			SDK:   func(s *settings.GlobalSwitch) *string { return &s.Dot1XFallbackNetworkID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "dot1x_portctrl_enabled",
			Model: func(m *settingGlobalSwitchModel) *types.Bool { return &m.Dot1xPortctrlEnabled },
			SDK:   func(s *settings.GlobalSwitch) *bool { return &s.Dot1XPortctrlEnabled },
		},
		resourcekit.BoolField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "flood_known_protocols",
			Model: func(m *settingGlobalSwitchModel) *types.Bool { return &m.FloodKnownProtocols },
			SDK:   func(s *settings.GlobalSwitch) *bool { return &s.FloodKnownProtocols },
		},
		resourcekit.BoolField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "flowctrl_enabled",
			Model: func(m *settingGlobalSwitchModel) *types.Bool { return &m.FlowctrlEnabled },
			SDK:   func(s *settings.GlobalSwitch) *bool { return &s.FlowctrlEnabled },
		},
		resourcekit.BoolField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "forward_unknown_mcast_router_ports",
			Model: func(m *settingGlobalSwitchModel) *types.Bool { return &m.ForwardUnknownMcastRouterPorts },
			SDK:   func(s *settings.GlobalSwitch) *bool { return &s.ForwardUnknownMcastRouterPorts },
		},
		resourcekit.BoolField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "jumboframe_enabled",
			Model: func(m *settingGlobalSwitchModel) *types.Bool { return &m.JumboframeEnabled },
			SDK:   func(s *settings.GlobalSwitch) *bool { return &s.JumboframeEnabled },
		},
		resourcekit.Int64PtrField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "link_debounce",
			Model: func(m *settingGlobalSwitchModel) *types.Int64 { return &m.LinkDebounce },
			SDK:   func(s *settings.GlobalSwitch) **int64 { return &s.LinkDebounce },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "poe_staging_delay_msec",
			Model: func(m *settingGlobalSwitchModel) *types.Int64 { return &m.PoeStagingDelayMsec },
			SDK:   func(s *settings.GlobalSwitch) **int64 { return &s.PoeStagingDelayMsec },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "radiusprofile_id",
			Model: func(m *settingGlobalSwitchModel) *types.String { return &m.RadiusprofileID },
			SDK:   func(s *settings.GlobalSwitch) *string { return &s.RADIUSProfileID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "stp_version",
			Model: func(m *settingGlobalSwitchModel) *types.String { return &m.STPVersion },
			SDK:   func(s *settings.GlobalSwitch) *string { return &s.StpVersion },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringListField[settingGlobalSwitchModel, settings.GlobalSwitch]{
			Wire:  "switch_exclusions",
			Model: func(m *settingGlobalSwitchModel) *types.List { return &m.SwitchExclusions },
			SDK:   func(s *settings.GlobalSwitch) *[]string { return &s.SwitchExclusions },
			Elide: resourcekit.KeepZero,
		},
	}
}
