package unifi

// ownershipClass classifies how a settings field is owned and therefore how
// the provider should treat it across plan/apply: whether it is written to
// the controller's PUT payload, whether it is read back from the API into
// state, whether it holds secret material, and whether Terraform should
// preserve the prior state value when the planned value is unknown.
type ownershipClass int

const (
	// ownerManaged fields are fully owned by Terraform: written on every
	// PUT and read back from the API into state.
	ownerManaged ownershipClass = iota

	// ownerCoManaged fields are written by Terraform but may also be
	// changed by the controller or other actors; state should fall back
	// to the prior value when the plan is unknown.
	ownerCoManaged

	// ownerComputed fields are never written by Terraform, only read
	// from the API, and use the prior state when unknown.
	ownerComputed

	// ownerWriteOnlySecret fields are written to the PUT payload but
	// never read back from the API (the controller does not return
	// secret values).
	ownerWriteOnlySecret

	// ownerGeneratedSecret fields are generated by the controller,
	// never written by Terraform, read back from the API, hold secret
	// material, and use the prior state when unknown.
	ownerGeneratedSecret

	// ownerPreservedUnmanaged fields are neither written nor read by
	// Terraform; their state value is preserved as-is.
	ownerPreservedUnmanaged
)

// writesToPUT reports whether Terraform should include this field's value
// in the controller PUT payload.
func (c ownershipClass) writesToPUT() bool {
	switch c {
	case ownerManaged, ownerCoManaged, ownerWriteOnlySecret:
		return true
	default:
		return false
	}
}

// readsFromAPI reports whether Terraform should populate this field's state
// from the controller's API response.
func (c ownershipClass) readsFromAPI() bool {
	switch c {
	case ownerWriteOnlySecret, ownerPreservedUnmanaged:
		return false
	default:
		return true
	}
}

// isSecret reports whether this field holds secret material that should be
// treated with sensitive handling.
func (c ownershipClass) isSecret() bool {
	switch c {
	case ownerWriteOnlySecret, ownerGeneratedSecret:
		return true
	default:
		return false
	}
}

// usesStateForUnknown reports whether this field should preserve its prior
// state value when the planned value is unknown.
func (c ownershipClass) usesStateForUnknown() bool {
	switch c {
	case ownerCoManaged, ownerComputed, ownerGeneratedSecret:
		return true
	default:
		return false
	}
}
