// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingSnmpModel struct {
	Community types.String `tfsdk:"community"`
	Enabled   types.Bool   `tfsdk:"enabled"`
	EnabledV3 types.Bool   `tfsdk:"enabled_v3"`
	Username  types.String `tfsdk:"username"`
	Password  types.String `tfsdk:"password"`
}

var snmpAttrTypes = map[string]attr.Type{
	"community":  types.StringType,
	"enabled":    types.BoolType,
	"enabled_v3": types.BoolType,
	"password":   types.StringType,
	"username":   types.StringType,
}

// snmpNestedSchema is the snmp SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func snmpNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["snmp"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingSnmpGenFields is every unifi_setting snmp attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingSnmpGenFields() []resourcekit.Field[settingSnmpModel, settings.Snmp] {
	return []resourcekit.Field[settingSnmpModel, settings.Snmp]{
		resourcekit.StringField[settingSnmpModel, settings.Snmp]{
			Wire:  "community",
			Model: func(m *settingSnmpModel) *types.String { return &m.Community },
			SDK:   func(s *settings.Snmp) *string { return &s.Community },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[settingSnmpModel, settings.Snmp]{
			Wire:  "enabled",
			Model: func(m *settingSnmpModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Snmp) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[settingSnmpModel, settings.Snmp]{
			Wire:  "enabledV3",
			Model: func(m *settingSnmpModel) *types.Bool { return &m.EnabledV3 },
			SDK:   func(s *settings.Snmp) *bool { return &s.EnabledV3 },
		},
		resourcekit.StringField[settingSnmpModel, settings.Snmp]{
			Wire:  "username",
			Model: func(m *settingSnmpModel) *types.String { return &m.Username },
			SDK:   func(s *settings.Snmp) *string { return &s.Username },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[settingSnmpModel, settings.Snmp]{
			Wire:  "x_password",
			Model: func(m *settingSnmpModel) *types.String { return &m.Password },
			SDK:   func(s *settings.Snmp) *string { return &s.Password },
			Elide: resourcekit.NullZero,
		},
	}
}
