// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingConnectivityModel struct {
	EnableIsolatedWLAN types.Bool   `tfsdk:"enable_isolated_wlan"`
	Enabled            types.Bool   `tfsdk:"enabled"`
	MloMeshEnabled     types.Bool   `tfsdk:"mlo_mesh_enabled"`
	UplinkHost         types.String `tfsdk:"uplink_host"`
	UplinkType         types.String `tfsdk:"uplink_type"`
}

var connectivityAttrTypes = map[string]attr.Type{
	"enable_isolated_wlan": types.BoolType,
	"enabled":              types.BoolType,
	"mlo_mesh_enabled":     types.BoolType,
	"uplink_host":          types.StringType,
	"uplink_type":          types.StringType,
}

// connectivityNestedSchema is the connectivity SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func connectivityNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["connectivity"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingConnectivityGenFields is every unifi_setting connectivity attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingConnectivityGenFields() []resourcekit.Field[settingConnectivityModel, settings.Connectivity] {
	return []resourcekit.Field[settingConnectivityModel, settings.Connectivity]{
		resourcekit.BoolField[settingConnectivityModel, settings.Connectivity]{
			Wire:  "enable_isolated_wlan",
			Model: func(m *settingConnectivityModel) *types.Bool { return &m.EnableIsolatedWLAN },
			SDK:   func(s *settings.Connectivity) *bool { return &s.EnableIsolatedWLAN },
		},
		resourcekit.BoolField[settingConnectivityModel, settings.Connectivity]{
			Wire:  "enabled",
			Model: func(m *settingConnectivityModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Connectivity) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[settingConnectivityModel, settings.Connectivity]{
			Wire:  "mlo_mesh_enabled",
			Model: func(m *settingConnectivityModel) *types.Bool { return &m.MloMeshEnabled },
			SDK:   func(s *settings.Connectivity) *bool { return &s.MloMeshEnabled },
		},
		resourcekit.StringField[settingConnectivityModel, settings.Connectivity]{
			Wire:  "uplink_host",
			Model: func(m *settingConnectivityModel) *types.String { return &m.UplinkHost },
			SDK:   func(s *settings.Connectivity) *string { return &s.UplinkHost },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[settingConnectivityModel, settings.Connectivity]{
			Wire:  "uplink_type",
			Model: func(m *settingConnectivityModel) *types.String { return &m.UplinkType },
			SDK:   func(s *settings.Connectivity) *string { return &s.UplinkType },
			Elide: resourcekit.KeepZero,
		},
	}
}
