// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingLocaleModel struct {
	Timezone types.String `tfsdk:"timezone"`
}

var localeAttrTypes = map[string]attr.Type{
	"timezone": types.StringType,
}

// localeNestedSchema is the locale SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func localeNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["locale"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingLocaleGenFields is every unifi_setting locale attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingLocaleGenFields() []resourcekit.Field[settingLocaleModel, settings.Locale] {
	return []resourcekit.Field[settingLocaleModel, settings.Locale]{
		resourcekit.StringField[settingLocaleModel, settings.Locale]{
			Wire:  "timezone",
			Model: func(m *settingLocaleModel) *types.String { return &m.Timezone },
			SDK:   func(s *settings.Locale) *string { return &s.Timezone },
			Elide: resourcekit.KeepZero,
		},
	}
}
