// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingUswModel struct {
	DHCPSnoop types.Bool `tfsdk:"dhcp_snoop"`
}

var uswAttrTypes = map[string]attr.Type{
	"dhcp_snoop": types.BoolType,
}

// uswNestedSchema is the usw SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func uswNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["usw"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingUswGenFields is every unifi_setting usw attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingUswGenFields() []resourcekit.Field[settingUswModel, settings.Usw] {
	return []resourcekit.Field[settingUswModel, settings.Usw]{
		resourcekit.BoolField[settingUswModel, settings.Usw]{
			Wire:  "dhcp_snoop",
			Model: func(m *settingUswModel) *types.Bool { return &m.DHCPSnoop },
			SDK:   func(s *settings.Usw) *bool { return &s.DHCPSnoop },
		},
	}
}
