// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/go-unifi/unifi/settings"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/generated/resource_setting"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type settingDpiModel struct {
	Enabled               types.Bool `tfsdk:"enabled"`
	FingerprintingEnabled types.Bool `tfsdk:"fingerprinting_enabled"`
}

var dpiAttrTypes = map[string]attr.Type{
	"enabled":                types.BoolType,
	"fingerprinting_enabled": types.BoolType,
}

// dpiNestedSchema is the dpi SingleNestedAttribute's own Attributes,
// wrapped as a schema.Schema so resourcekit's conformance checks -- built
// for a whole resource's top-level schema -- can run against one section
// of unifi_setting.
func dpiNestedSchema(ctx context.Context) schema.Schema {
	built := resource_setting.SettingResourceSchema(ctx)
	section := built.Attributes["dpi"].(schema.SingleNestedAttribute)
	return schema.Schema{Attributes: section.Attributes}
}

// settingDpiGenFields is every unifi_setting dpi attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func settingDpiGenFields() []resourcekit.Field[settingDpiModel, settings.Dpi] {
	return []resourcekit.Field[settingDpiModel, settings.Dpi]{
		resourcekit.BoolField[settingDpiModel, settings.Dpi]{
			Wire:  "enabled",
			Model: func(m *settingDpiModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *settings.Dpi) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[settingDpiModel, settings.Dpi]{
			Wire:  "fingerprintingEnabled",
			Model: func(m *settingDpiModel) *types.Bool { return &m.FingerprintingEnabled },
			SDK:   func(s *settings.Dpi) *bool { return &s.FingerprintingEnabled },
		},
	}
}

// dpiKitSpec is the dpi section's Spec: the generated field
// list over settings.Dpi, with no hook and no conditional write.
func dpiKitSpec() resourcekit.Spec[settingDpiModel, settings.Dpi] {
	return resourcekit.Spec[settingDpiModel, settings.Dpi]{
		TypeName: "setting_dpi",
		Subject:  "DPI Setting",
		New:      func() *settings.Dpi { return &settings.Dpi{} },
		Fields:   settingDpiGenFields(),
	}
}

// dpiKitBackend binds dpiKitSpec to a client: Read is
// GetSetting[*settings.Dpi], UpdateFields is the masked UpdateSettingFields --
// naming only the fields the plan set.
func dpiKitBackend(client *ui.ApiClient) resourcekit.Backend[settings.Dpi] {
	return resourcekit.Backend[settings.Dpi]{
		Read: func(ctx context.Context, site, _ string) (*settings.Dpi, error) {
			_, doc, err := ui.GetSetting[*settings.Dpi](client, ctx, site)
			if err != nil {
				return nil, err
			}
			return doc, nil
		},
		UpdateFields: func(
			ctx context.Context, site string, in *settings.Dpi, fields ...string,
		) (*settings.Dpi, error) {
			if err := client.UpdateSettingFields(ctx, site, in, fields...); err != nil {
				return nil, err
			}
			return in, nil
		},
	}
}

// dpiKitSection builds the dpi entry for settingResource's
// Sections, bound to client via settingKitSections.
func dpiKitSection(client *ui.ApiClient) resourcekit.Section[settingResourceModel] {
	spec := dpiKitSpec()
	spec.Backend = dpiKitBackend(client)
	return resourcekit.SpecSection[settingResourceModel, settingDpiModel, settings.Dpi]{
		SectionName: "dpi",
		Get:         func(m *settingResourceModel) *types.Object { return &m.Dpi },
		Set:         func(m *settingResourceModel, o types.Object) { m.Dpi = o },
		AttrTypes:   dpiAttrTypes,
		Spec:        spec,
	}
}
