// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

// siteGenFields is every unifi_site attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func siteGenFields() []resourcekit.Field[siteKitModel, ui.Site] {
	return []resourcekit.Field[siteKitModel, ui.Site]{
		resourcekit.StringField[siteKitModel, ui.Site]{
			Wire:  "desc",
			Model: func(m *siteKitModel) *types.String { return &m.Description },
			SDK:   func(s *ui.Site) *string { return &s.Description },
			Elide: resourcekit.KeepZero,
		},
	}
}
