// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-nettypes/iptypes"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type staticRouteKitModel struct {
	ID            types.String      `tfsdk:"id"`
	Site          types.String      `tfsdk:"site"`
	Enabled       types.Bool        `tfsdk:"enabled"`
	GatewayDevice types.String      `tfsdk:"gateway_device"`
	GatewayType   types.String      `tfsdk:"gateway_type"`
	Name          types.String      `tfsdk:"name"`
	Distance      types.Int64       `tfsdk:"distance"`
	Interface     types.String      `tfsdk:"interface"`
	Network       types.String      `tfsdk:"network"`
	NextHop       iptypes.IPAddress `tfsdk:"next_hop"`
	Type          types.String      `tfsdk:"type"`
	Timeouts      timeouts.Value    `tfsdk:"timeouts"`
}

// staticRouteGenFields is every unifi_static_route attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func staticRouteGenFields() []resourcekit.Field[staticRouteKitModel, ui.Routing] {
	return []resourcekit.Field[staticRouteKitModel, ui.Routing]{
		resourcekit.BoolField[staticRouteKitModel, ui.Routing]{
			Wire:  "enabled",
			Model: func(m *staticRouteKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.Routing) *bool { return &s.Enabled },
		},
		resourcekit.StringField[staticRouteKitModel, ui.Routing]{
			Wire:  "gateway_device",
			Model: func(m *staticRouteKitModel) *types.String { return &m.GatewayDevice },
			SDK:   func(s *ui.Routing) *string { return &s.GatewayDevice },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[staticRouteKitModel, ui.Routing]{
			Wire:  "name",
			Model: func(m *staticRouteKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.Routing) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[staticRouteKitModel, ui.Routing]{
			Wire:  "static-route_distance",
			Model: func(m *staticRouteKitModel) *types.Int64 { return &m.Distance },
			SDK:   func(s *ui.Routing) **int64 { return &s.StaticRouteDistance },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[staticRouteKitModel, ui.Routing]{
			Wire:  "static-route_network",
			Model: func(m *staticRouteKitModel) *types.String { return &m.Network },
			SDK:   func(s *ui.Routing) *string { return &s.StaticRouteNetwork },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[staticRouteKitModel, ui.Routing]{
			Wire:  "static-route_type",
			Model: func(m *staticRouteKitModel) *types.String { return &m.Type },
			SDK:   func(s *ui.Routing) *string { return &s.StaticRouteType },
			Elide: resourcekit.KeepZero,
		},
	}
}
