// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-nettypes/iptypes"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type trafficRouteKitModel struct {
	ID                types.String      `tfsdk:"id"`
	Site              types.String      `tfsdk:"site"`
	Description       types.String      `tfsdk:"description"`
	Enabled           types.Bool        `tfsdk:"enabled"`
	KillSwitchEnabled types.Bool        `tfsdk:"kill_switch_enabled"`
	NetworkID         types.String      `tfsdk:"network_id"`
	NextHop           iptypes.IPAddress `tfsdk:"next_hop"`
	Destination       types.Object      `tfsdk:"destination"`
	Source            types.Object      `tfsdk:"source"`
	Timeouts          timeouts.Value    `tfsdk:"timeouts"`
}

// trafficRouteGenFields is every unifi_traffic_route attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func trafficRouteGenFields() []resourcekit.Field[trafficRouteKitModel, ui.TrafficRoute] {
	return []resourcekit.Field[trafficRouteKitModel, ui.TrafficRoute]{
		resourcekit.StringField[trafficRouteKitModel, ui.TrafficRoute]{
			Wire:  "description",
			Model: func(m *trafficRouteKitModel) *types.String { return &m.Description },
			SDK:   func(s *ui.TrafficRoute) *string { return &s.Description },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[trafficRouteKitModel, ui.TrafficRoute]{
			Wire:  "enabled",
			Model: func(m *trafficRouteKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.TrafficRoute) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[trafficRouteKitModel, ui.TrafficRoute]{
			Wire:  "kill_switch_enabled",
			Model: func(m *trafficRouteKitModel) *types.Bool { return &m.KillSwitchEnabled },
			SDK:   func(s *ui.TrafficRoute) *bool { return &s.KillSwitchEnabled },
		},
	}
}
