// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-nettypes/cidrtypes"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type vpnServerKitModel struct {
	ID              types.String         `tfsdk:"id"`
	Site            types.String         `tfsdk:"site"`
	Enabled         types.Bool           `tfsdk:"enabled"`
	Subnet          cidrtypes.IPv4Prefix `tfsdk:"subnet"`
	Name            types.String         `tfsdk:"name"`
	RadiusprofileID types.String         `tfsdk:"radiusprofile_id"`
	DNS             types.Object         `tfsdk:"dns"`
	L2TP            types.Object         `tfsdk:"l2tp"`
	Openvpn         types.Object         `tfsdk:"openvpn"`
	WAN             types.Object         `tfsdk:"wan"`
	Wireguard       types.Object         `tfsdk:"wireguard"`
	Timeouts        timeouts.Value       `tfsdk:"timeouts"`
}

// vpnServerGenFields is every unifi_vpn_server attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func vpnServerGenFields() []resourcekit.Field[vpnServerKitModel, ui.Network] {
	return []resourcekit.Field[vpnServerKitModel, ui.Network]{
		resourcekit.BoolField[vpnServerKitModel, ui.Network]{
			Wire:  "enabled",
			Model: func(m *vpnServerKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.Network) *bool { return &s.Enabled },
		},
	}
}
