// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type wanKitModel struct {
	ID                      types.String   `tfsdk:"id"`
	Site                    types.String   `tfsdk:"site"`
	Enabled                 types.Bool     `tfsdk:"enabled"`
	IPv6SettingPreference   types.String   `tfsdk:"ipv6_setting_preference"`
	MACOverrideEnabled      types.Bool     `tfsdk:"mac_override_enabled"`
	Name                    types.String   `tfsdk:"name"`
	ReportWANEvent          types.Bool     `tfsdk:"report_wan_event"`
	SettingPreference       types.String   `tfsdk:"setting_preference"`
	SingleNetworkLAN        types.String   `tfsdk:"single_network_lan"`
	WANDsliteRemoteHost     types.String   `tfsdk:"wan_dslite_remote_host"`
	WANDsliteRemoteHostAuto types.Bool     `tfsdk:"wan_dslite_remote_host_auto"`
	IPAliases               types.List     `tfsdk:"ip_aliases"`
	Networkgroup            types.String   `tfsdk:"networkgroup"`
	ProviderCapabilities    types.Object   `tfsdk:"provider_capabilities"`
	Type                    types.String   `tfsdk:"type"`
	TypeV6                  types.String   `tfsdk:"type_v6"`
	DHCP                    types.Object   `tfsdk:"dhcp"`
	DHCPv6                  types.Object   `tfsdk:"dhcpv6"`
	DNS                     types.Object   `tfsdk:"dns"`
	EgressQoS               types.Object   `tfsdk:"egress_qos"`
	IGMPProxy               types.Object   `tfsdk:"igmp_proxy"`
	LoadBalance             types.Object   `tfsdk:"load_balance"`
	Smartq                  types.Object   `tfsdk:"smartq"`
	UPnP                    types.Object   `tfsdk:"upnp"`
	VLAN                    types.Object   `tfsdk:"vlan"`
	Timeouts                timeouts.Value `tfsdk:"timeouts"`
}

// wanGenFields is every unifi_wan attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func wanGenFields() []resourcekit.Field[wanKitModel, ui.Network] {
	return []resourcekit.Field[wanKitModel, ui.Network]{
		resourcekit.BoolField[wanKitModel, ui.Network]{
			Wire:  "enabled",
			Model: func(m *wanKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.Network) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[wanKitModel, ui.Network]{
			Wire:  "report_wan_event",
			Model: func(m *wanKitModel) *types.Bool { return &m.ReportWANEvent },
			SDK:   func(s *ui.Network) *bool { return &s.ReportWANEvent },
		},
		resourcekit.BoolField[wanKitModel, ui.Network]{
			Wire:  "wan_dslite_remote_host_auto",
			Model: func(m *wanKitModel) *types.Bool { return &m.WANDsliteRemoteHostAuto },
			SDK:   func(s *ui.Network) *bool { return &s.WANDsliteRemoteHostAuto },
		},
		resourcekit.StringListField[wanKitModel, ui.Network]{
			Wire:  "wan_ip_aliases",
			Model: func(m *wanKitModel) *types.List { return &m.IPAliases },
			SDK:   func(s *ui.Network) *[]string { return &s.WANIPAliases },
			Elide: resourcekit.NullZero,
		},
	}
}
