// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type wireguardPeerKitModel struct {
	ID          types.String   `tfsdk:"id"`
	Site        types.String   `tfsdk:"site"`
	AllowedIPs  types.List     `tfsdk:"allowed_ips"`
	InterfaceIP types.String   `tfsdk:"interface_ip"`
	Name        types.String   `tfsdk:"name"`
	NetworkID   types.String   `tfsdk:"network_id"`
	PublicKey   types.String   `tfsdk:"public_key"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}

// wireguardPeerGenFields is every unifi_wireguard_peer attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func wireguardPeerGenFields() []resourcekit.Field[wireguardPeerKitModel, ui.WireGuardPeer] {
	return []resourcekit.Field[wireguardPeerKitModel, ui.WireGuardPeer]{
		resourcekit.StringListField[wireguardPeerKitModel, ui.WireGuardPeer]{
			Wire:  "allowed_ips",
			Model: func(m *wireguardPeerKitModel) *types.List { return &m.AllowedIPs },
			SDK:   func(s *ui.WireGuardPeer) *[]string { return &s.AllowedIPs },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[wireguardPeerKitModel, ui.WireGuardPeer]{
			Wire:  "interface_ip",
			Model: func(m *wireguardPeerKitModel) *types.String { return &m.InterfaceIP },
			SDK:   func(s *ui.WireGuardPeer) *string { return &s.InterfaceIP },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[wireguardPeerKitModel, ui.WireGuardPeer]{
			Wire:  "name",
			Model: func(m *wireguardPeerKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.WireGuardPeer) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[wireguardPeerKitModel, ui.WireGuardPeer]{
			Wire:  "network_id",
			Model: func(m *wireguardPeerKitModel) *types.String { return &m.NetworkID },
			SDK:   func(s *ui.WireGuardPeer) *string { return &s.NetworkID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[wireguardPeerKitModel, ui.WireGuardPeer]{
			Wire:  "public_key",
			Model: func(m *wireguardPeerKitModel) *types.String { return &m.PublicKey },
			SDK:   func(s *ui.WireGuardPeer) *string { return &s.PublicKey },
			Elide: resourcekit.KeepZero,
		},
	}
}
