package unifi

// wlanManagedWireFields lists every wire unifi_wlan can write. WLAN has no
// custom MarshalJSON, so there is no purpose discriminator to filter against:
// force-emission here is just a bare json tag, and the mask is this assigned
// set -- ownership decides membership, not encoding.
func wlanManagedWireFields() []string {
	return []string{
		"ap_group_ids",
		"ap_group_mode",
		"bc_filter_list",
		"bss_transition",
		"dtim_6e",
		"dtim_mode",
		"dtim_na",
		"dtim_ng",
		"enabled",
		"enhanced_iot",
		"fast_roaming_enabled",
		"group_rekey",
		"hide_ssid",
		"hotspot2conf_enabled",
		"iapp_enabled",
		"is_guest",
		"l2_isolation",
		"mac_filter_enabled",
		"mac_filter_list",
		"mac_filter_policy",
		"mcastenhance_enabled",
		"minrate_na_data_rate_kbps",
		"minrate_na_enabled",
		"minrate_ng_data_rate_kbps",
		"minrate_ng_enabled",
		"minrate_setting_preference",
		"mlo_enabled",
		"name",
		"name_combine_enabled",
		"nas_identifier_type",
		"networkconf_id",
		"no2ghz_oui",
		"pmf_mode",
		"private_preshared_keys",
		"private_preshared_keys_enabled",
		"proxy_arp",
		"radius_mac_auth_enabled",
		"radiusprofile_id",
		"roaming_assistant_6e_enabled",
		"roaming_assistant_6e_rssi",
		"roaming_assistant_na_enabled",
		"roaming_assistant_na_rssi",
		"schedule_enabled",
		"schedule_with_duration",
		"security",
		"uapsd_enabled",
		"usergroup_id",
		"vlan",
		"vlan_enabled",
		"wlan_band",
		"wlan_bands",
		"wlangroup_id",
		"wpa3_enhanced_192",
		"wpa3_fast_roaming",
		"wpa3_support",
		"wpa3_transition",
		"wpa_enc",
		"wpa_mode",
		"x_passphrase",
	}
}
