// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type wlanMacFilterModel struct {
	Enabled types.Bool   `tfsdk:"enabled"`
	List    types.Set    `tfsdk:"list"`
	Policy  types.String `tfsdk:"policy"`
}

var wlanMacFilterAttrTypes = map[string]attr.Type{
	"enabled": types.BoolType,
	"list":    types.SetType{ElemType: types.StringType},
	"policy":  types.StringType,
}

type wlanPrivatePresharedKeysModel struct {
	NetworkID types.String `tfsdk:"network_id"`
	Password  types.String `tfsdk:"password"`
}

var wlanPrivatePresharedKeysAttrTypes = map[string]attr.Type{
	"network_id": types.StringType,
	"password":   types.StringType,
}

// wlanGenFields is every unifi_wlan attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func wlanGenFields() []resourcekit.Field[wlanKitModel, ui.WLAN] {
	return []resourcekit.Field[wlanKitModel, ui.WLAN]{
		resourcekit.StringSetField[wlanKitModel, ui.WLAN]{
			Wire:  "ap_group_ids",
			Model: func(m *wlanKitModel) *types.Set { return &m.APGroupIDs },
			SDK:   func(s *ui.WLAN) *[]string { return &s.ApGroupIDs },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "ap_group_mode",
			Model: func(m *wlanKitModel) *types.String { return &m.APGroupMode },
			SDK:   func(s *ui.WLAN) *string { return &s.ApGroupMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringSetField[wlanKitModel, ui.WLAN]{
			Wire:  "bc_filter_list",
			Model: func(m *wlanKitModel) *types.Set { return &m.BcFilterList },
			SDK:   func(s *ui.WLAN) *[]string { return &s.BroadcastFilterList },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "bss_transition",
			Model: func(m *wlanKitModel) *types.Bool { return &m.BssTransition },
			SDK:   func(s *ui.WLAN) *bool { return &s.BssTransition },
		},
		resourcekit.Int64PtrField[wlanKitModel, ui.WLAN]{
			Wire:     "dtim_6e",
			Model:    func(m *wlanKitModel) *types.Int64 { return &m.Dtim6E },
			SDK:      func(s *ui.WLAN) **int64 { return &s.DTIM6E },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "dtim_mode",
			Model: func(m *wlanKitModel) *types.String { return &m.DtimMode },
			SDK:   func(s *ui.WLAN) *string { return &s.DTIMMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.Int64PtrField[wlanKitModel, ui.WLAN]{
			Wire:     "dtim_na",
			Model:    func(m *wlanKitModel) *types.Int64 { return &m.DtimNa },
			SDK:      func(s *ui.WLAN) **int64 { return &s.DTIMNa },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.Int64PtrField[wlanKitModel, ui.WLAN]{
			Wire:     "dtim_ng",
			Model:    func(m *wlanKitModel) *types.Int64 { return &m.DtimNg },
			SDK:      func(s *ui.WLAN) **int64 { return &s.DTIMNg },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.Enabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.Enabled },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "enhanced_iot",
			Model: func(m *wlanKitModel) *types.Bool { return &m.EnhancedIot },
			SDK:   func(s *ui.WLAN) *bool { return &s.EnhancedIot },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "fast_roaming_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.FastRoamingEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.FastRoamingEnabled },
		},
		resourcekit.Int64PtrField[wlanKitModel, ui.WLAN]{
			Wire:  "group_rekey",
			Model: func(m *wlanKitModel) *types.Int64 { return &m.GroupRekey },
			SDK:   func(s *ui.WLAN) **int64 { return &s.GroupRekey },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "hide_ssid",
			Model: func(m *wlanKitModel) *types.Bool { return &m.HideSSID },
			SDK:   func(s *ui.WLAN) *bool { return &s.HideSSID },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "hotspot2conf_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.Hotspot2confEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.Hotspot2ConfEnabled },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "iapp_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.IappEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.IappEnabled },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "is_guest",
			Model: func(m *wlanKitModel) *types.Bool { return &m.IsGuest },
			SDK:   func(s *ui.WLAN) *bool { return &s.IsGuest },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "l2_isolation",
			Model: func(m *wlanKitModel) *types.Bool { return &m.L2Isolation },
			SDK:   func(s *ui.WLAN) *bool { return &s.L2Isolation },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "mcastenhance_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.MulticastEnhance },
			SDK:   func(s *ui.WLAN) *bool { return &s.MulticastEnhanceEnabled },
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "minrate_setting_preference",
			Model: func(m *wlanKitModel) *types.String { return &m.MinrateSettingPreference },
			SDK:   func(s *ui.WLAN) *string { return &s.MinrateSettingPreference },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "mlo_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.MloEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.MloEnabled },
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "name",
			Model: func(m *wlanKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.WLAN) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "nas_identifier_type",
			Model: func(m *wlanKitModel) *types.String { return &m.NasIdentifierType },
			SDK:   func(s *ui.WLAN) *string { return &s.NasIDentifierType },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "networkconf_id",
			Model: func(m *wlanKitModel) *types.String { return &m.NetworkID },
			SDK:   func(s *ui.WLAN) *string { return &s.NetworkID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "no2ghz_oui",
			Model: func(m *wlanKitModel) *types.Bool { return &m.No2ghzOUI },
			SDK:   func(s *ui.WLAN) *bool { return &s.No2GhzOui },
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "pmf_mode",
			Model: func(m *wlanKitModel) *types.String { return &m.PMFMode },
			SDK:   func(s *ui.WLAN) *string { return &s.PMFMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "private_preshared_keys_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.PrivatePresharedKeysEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.PrivatePresharedKeysEnabled },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "proxy_arp",
			Model: func(m *wlanKitModel) *types.Bool { return &m.ProxyARP },
			SDK:   func(s *ui.WLAN) *bool { return &s.ProxyArp },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "radius_mac_auth_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.RADIUSMACAuthEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.RADIUSMACAuthEnabled },
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "radiusprofile_id",
			Model: func(m *wlanKitModel) *types.String { return &m.RADIUSProfileID },
			SDK:   func(s *ui.WLAN) *string { return &s.RADIUSProfileID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "roaming_assistant_6e_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.RoamingAssistant6EEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.RoamingAssistant6EEnabled },
		},
		resourcekit.Int64PtrField[wlanKitModel, ui.WLAN]{
			Wire:     "roaming_assistant_6e_rssi",
			Model:    func(m *wlanKitModel) *types.Int64 { return &m.RoamingAssistant6ERssi },
			SDK:      func(s *ui.WLAN) **int64 { return &s.RoamingAssistant6ERssi },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "roaming_assistant_na_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.RoamingAssistantNaEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.RoamingAssistantNaEnabled },
		},
		resourcekit.Int64PtrField[wlanKitModel, ui.WLAN]{
			Wire:     "roaming_assistant_na_rssi",
			Model:    func(m *wlanKitModel) *types.Int64 { return &m.RoamingAssistantNaRssi },
			SDK:      func(s *ui.WLAN) **int64 { return &s.RoamingAssistantNaRssi },
			Elide:    resourcekit.KeepZero,
			OmitZero: true,
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "security",
			Model: func(m *wlanKitModel) *types.String { return &m.Security },
			SDK:   func(s *ui.WLAN) *string { return &s.Security },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "uapsd_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.Uapsd },
			SDK:   func(s *ui.WLAN) *bool { return &s.UapsdEnabled },
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "usergroup_id",
			Model: func(m *wlanKitModel) *types.String { return &m.UserGroupID },
			SDK:   func(s *ui.WLAN) *string { return &s.UserGroupID },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.Int64PtrField[wlanKitModel, ui.WLAN]{
			Wire:     "vlan",
			Model:    func(m *wlanKitModel) *types.Int64 { return &m.VLAN },
			SDK:      func(s *ui.WLAN) **int64 { return &s.VLAN },
			Elide:    resourcekit.NullZero,
			OmitZero: true,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "vlan_enabled",
			Model: func(m *wlanKitModel) *types.Bool { return &m.VLANEnabled },
			SDK:   func(s *ui.WLAN) *bool { return &s.VLANEnabled },
		},
		resourcekit.StringSetField[wlanKitModel, ui.WLAN]{
			Wire:  "wlan_bands",
			Model: func(m *wlanKitModel) *types.Set { return &m.WLANBands },
			SDK:   func(s *ui.WLAN) *[]string { return &s.WLANBands },
			Elide: resourcekit.KeepZero,
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "wpa3_enhanced_192",
			Model: func(m *wlanKitModel) *types.Bool { return &m.WPA3Enhanced192 },
			SDK:   func(s *ui.WLAN) *bool { return &s.WPA3Enhanced192 },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "wpa3_fast_roaming",
			Model: func(m *wlanKitModel) *types.Bool { return &m.WPA3FastRoaming },
			SDK:   func(s *ui.WLAN) *bool { return &s.WPA3FastRoaming },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "wpa3_support",
			Model: func(m *wlanKitModel) *types.Bool { return &m.WPA3Support },
			SDK:   func(s *ui.WLAN) *bool { return &s.WPA3Support },
		},
		resourcekit.BoolField[wlanKitModel, ui.WLAN]{
			Wire:  "wpa3_transition",
			Model: func(m *wlanKitModel) *types.Bool { return &m.WPA3Transition },
			SDK:   func(s *ui.WLAN) *bool { return &s.WPA3Transition },
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "wpa_enc",
			Model: func(m *wlanKitModel) *types.String { return &m.WPAEnc },
			SDK:   func(s *ui.WLAN) *string { return &s.WPAEnc },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "wpa_mode",
			Model: func(m *wlanKitModel) *types.String { return &m.WPAMode },
			SDK:   func(s *ui.WLAN) *string { return &s.WPAMode },
			Elide: resourcekit.NullZero,
		},
		resourcekit.StringField[wlanKitModel, ui.WLAN]{
			Wire:  "x_passphrase",
			Model: func(m *wlanKitModel) *types.String { return &m.Passphrase },
			SDK:   func(s *ui.WLAN) *string { return &s.Passphrase },
			Elide: resourcekit.NullZero,
		},
	}
}
