// Code generated by cmd/descriptor-emitter. DO NOT EDIT.

package unifi

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ui "github.com/ubiquiti-community/go-unifi/unifi"
	"github.com/ubiquiti-community/terraform-provider-unifi/internal/resourcekit"
)

type wlanGroupKitModel struct {
	ID       types.String   `tfsdk:"id"`
	Site     types.String   `tfsdk:"site"`
	Name     types.String   `tfsdk:"name"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

// wlanGroupGenFields is every unifi_wlan_group attribute whose mapping the pipeline's
// artifacts fully determine. The hand descriptor lays its judgment fields
// over these with resourcekit.Override.
func wlanGroupGenFields() []resourcekit.Field[wlanGroupKitModel, ui.WLANGroup] {
	return []resourcekit.Field[wlanGroupKitModel, ui.WLANGroup]{
		resourcekit.StringField[wlanGroupKitModel, ui.WLANGroup]{
			Wire:  "name",
			Model: func(m *wlanGroupKitModel) *types.String { return &m.Name },
			SDK:   func(s *ui.WLANGroup) *string { return &s.Name },
			Elide: resourcekit.KeepZero,
		},
	}
}
