// Command firewall-capability-gen freezes the controller's measured
// firewall_policy protocol/ip_version capability matrix into a Go map the
// resource's cross-field validator reads.
//
// The behaviour artifact's capabilities.FirewallPolicy records, for each
// (ip_version, protocol) pair the go-unifi lane measured against a live
// controller, whether the controller accepts it. Names and numeric protocol
// forms are both measured; a pair the artifact does not carry was never
// measured and the validator stays silent on it, so this generator emits only
// what was measured and never invents a verdict.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type document struct {
	Behavior struct {
		Capabilities map[string]map[string]struct {
			Accepted bool `json:"accepted"`
		} `json:"capabilities"`
	} `json:"behavior"`
}

func main() {
	behaviorPath := flag.String("behavior", "", "path to the behaviour artifact (behavior.json)")
	out := flag.String("output", "", "file to write the generated matrix to")
	flag.Parse()
	if *behaviorPath == "" || *out == "" {
		fail("-behavior and -output are required")
	}

	raw, err := os.ReadFile(*behaviorPath)
	if err != nil {
		fail("read behaviour artifact: %v", err)
	}
	var doc document
	if err := json.Unmarshal(raw, &doc); err != nil {
		fail("parse %s: %v", *behaviorPath, err)
	}
	rows := doc.Behavior.Capabilities["FirewallPolicy"]
	// An empty matrix would make the validator assert nothing while looking
	// like it checks something; refuse rather than ship that.
	if len(rows) == 0 {
		fail("behaviour artifact carries no capabilities.FirewallPolicy rows")
	}

	// Each artifact key is "ip_version=V,protocol=P" or
	// "ip_version=V,protocol_number=N"; both collapse to "V|value" so the
	// validator can look up a practitioner's protocol, name or number alike,
	// with one lookup.
	matrix := make(map[string]bool, len(rows))
	for key, verdict := range rows {
		version, value, err := parseKey(key)
		if err != nil {
			fail("capabilities.FirewallPolicy key %q: %v", key, err)
		}
		matrix[version+"|"+value] = verdict.Accepted
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/firewall-capability-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "// Package firewallcapability carries the controller's measured\n")
	fmt.Fprintf(&buf, "// firewall_policy protocol/ip_version acceptance matrix, keyed\n")
	fmt.Fprintf(&buf, "// \"IP_VERSION|protocol\" where protocol is a name or a numeric form.\n")
	fmt.Fprintf(&buf, "// A pair absent from the map was never measured.\n")
	fmt.Fprintf(&buf, "package firewallcapability\n\n")
	fmt.Fprintf(&buf, "// Matrix maps \"IP_VERSION|protocol\" to whether the controller accepts it.\n")
	fmt.Fprintf(&buf, "var Matrix = map[string]bool{\n")
	keys := make([]string, 0, len(matrix))
	for k := range matrix {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&buf, "\t%q: %t,\n", k, matrix[k])
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fail("formatting the generated matrix: %v", err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil { //nolint:gosec // generated source, world-readable like its siblings
		fail("write %s: %v", *out, err)
	}
}

// parseKey splits "ip_version=V,protocol=P" or "ip_version=V,protocol_number=N"
// into the version and the protocol value (name or number).
func parseKey(key string) (version, value string, err error) {
	parts := strings.Split(key, ",")
	if len(parts) != 2 {
		return "", "", fmt.Errorf("not \"ip_version=...,protocol[_number]=...\"")
	}
	for _, p := range parts {
		field, v, found := strings.Cut(p, "=")
		if !found || v == "" {
			return "", "", fmt.Errorf("segment %q is not field=value", p)
		}
		switch field {
		case "ip_version":
			version = v
		case "protocol", "protocol_number":
			value = v
		default:
			return "", "", fmt.Errorf("unexpected field %q", field)
		}
	}
	if version == "" || value == "" {
		return "", "", fmt.Errorf("missing ip_version or protocol")
	}
	return version, value, nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
